// emc.js — Donnees EMC Terminale (Enseignement Moral et Civique)
// Format pedagogique adapte dys/TSA : phrases courtes, exemples concrets, mots difficiles expliques
(function() {
    if (!window.StudFlow || !window.StudFlow.subjects) return;

    window.StudFlow.subjects.register({
        id: 'emc',
        name: 'EMC',
        icon: '\uD83C\uDFDB\uFE0F',
        color: 'mint',
        sections: [

            // ================================================================
            // SECTION 1 : LES FONDEMENTS DE LA REPUBLIQUE
            // ================================================================
            {
                id: 'fondements-republique',
                title: 'Les fondements de la Republique',
                icon: '\uD83C\uDDEB\uD83C\uDDF7',
                content: '<h3>Valeurs, principes et symboles de la Republique francaise</h3>',
                flashcards: [
                    { question: 'C\'est quoi les valeurs de la Republique ?', answer: 'LIBERTE : chacun peut penser, s\'exprimer, croire (ou ne pas croire) librement. EGALITE : tous les citoyens ont les memes droits devant la loi, quelle que soit leur origine. FRATERNITE : solidarite entre les citoyens, vivre ensemble. La devise "Liberte, Egalite, Fraternite" est inscrite sur les mairies, les ecoles, les tribunaux. En gros : 3 mots qui definissent ce qu\'est la France en tant que Republique.' },
                    { question: 'C\'est quoi la laicite ?', answer: 'La LAICITE = la separation entre l\'ETAT et les RELIGIONS. Loi de 1905. L\'Etat ne favorise AUCUNE religion. Chacun est LIBRE de croire ou de ne pas croire. MAIS : la religion reste dans la sphere PRIVEE (pas dans les institutions publiques). A l\'ecole : pas de signes religieux OSTENSIBLES (loi de 2004 : pas de voile, kippa, grande croix). En gros : l\'Etat est neutre. Tu crois ce que tu veux, mais l\'Etat ne prend pas parti. Mots difficiles : "ostensible" = visible de facon exageree, qui se montre volontairement.' },
                    { question: 'C\'est quoi l\'Etat de droit ?', answer: 'Un ETAT DE DROIT = un Etat ou TOUT LE MONDE (y compris le president) est soumis a la LOI. Personne n\'est au-dessus des lois. Il repose sur : la CONSTITUTION (la loi supreme), la SEPARATION DES POUVOIRS (legislatif, executif, judiciaire), les DROITS FONDAMENTAUX (liberte, egalite, presomption d\'innocence). Le CONTRAIRE = la dictature (le chef decide seul, sans loi). En gros : dans un Etat de droit, c\'est la loi qui commande, pas un homme.' },
                    { question: 'C\'est quoi la separation des pouvoirs ?', answer: 'Idee de MONTESQUIEU (L\'Esprit des lois, 1748). Les 3 pouvoirs doivent etre SEPARES pour eviter la tyrannie : LEGISLATIF = faire les lois (Assemblee nationale + Senat). EXECUTIF = appliquer les lois (President + Gouvernement). JUDICIAIRE = juger ceux qui ne respectent pas les lois (tribunaux). Si UNE SEULE personne a les 3 pouvoirs → dictature. En gros : separer les pouvoirs = empecher qu\'un seul homme decide de tout.' },
                    { question: 'C\'est quoi la Constitution de la Ve Republique ?', answer: 'La CONSTITUTION = la loi SUPREME de la France. Celle de la Ve Republique date de 1958 (De Gaulle). Elle definit : le role du PRESIDENT (elu pour 5 ans, chef des armees), le GOUVERNEMENT (Premier ministre + ministres), le PARLEMENT (Assemblee nationale + Senat), le CONSEIL CONSTITUTIONNEL (verifie que les lois respectent la Constitution). En gros : la Constitution = les regles du jeu de la Republique.' },
                    { question: 'Quels sont les symboles de la Republique ?', answer: 'Le DRAPEAU tricolore (bleu, blanc, rouge). La MARSEILLAISE (hymne national, 1792). La devise : LIBERTE, EGALITE, FRATERNITE. MARIANNE (figure feminine, visage de la Republique). Le 14 JUILLET (fete nationale, prise de la Bastille). Le COQ gaulois. En gros : ces symboles representent les valeurs de la Republique. On les retrouve dans les mairies, les ecoles, les pieces de monnaie.' },
                    { question: 'C\'est quoi le contrat social ?', answer: 'Le CONTRAT SOCIAL = un accord (theorique) entre les individus et l\'Etat. HOBBES (Le Leviathan, 1651) : sans Etat, c\'est la "guerre de tous contre tous." Les hommes acceptent de ceder leur liberte a un souverain PUISSANT pour avoir la SECURITE. ROUSSEAU (Du contrat social, 1762) : les citoyens s\'unissent librement et obeissent a la LOI qu\'ils ont eux-memes choisie. La loi = la volonte generale. En gros : le contrat social explique POURQUOI on accepte de vivre sous des lois. Mots difficiles : "contrat social" = un accord theorique, pas un vrai contrat signe.' },
                    { question: 'Quelle difference entre Republique et democratie ?', answer: 'Ce n\'est PAS la meme chose ! REPUBLIQUE = un regime ou le pouvoir n\'est PAS hereditaire. Le chef de l\'Etat est ELU, pas roi. Le contraire = la monarchie. DEMOCRATIE = le pouvoir appartient au PEUPLE (il decide, directement ou via des elus). On peut etre une Republique SANS etre une democratie (ex : la Chine est une republique, mais pas une democratie). On peut etre une democratie SANS etre une republique (ex : le Royaume-Uni est une monarchie democratique). En gros : Republique = pas de roi. Democratie = le peuple decide.' },
                    { question: 'Les debats autour de la laicite aujourd\'hui', answer: 'La laicite (loi de 1905) fait l\'objet de DEBATS vifs en France. Exemples : le BURKINI sur les plages (interdit dans certaines villes, autorise dans d\'autres). Le VOILE a l\'ecole (interdit depuis 2004 pour les eleves). Les accompagnatrices scolaires VOILEES (debat non tranche). Les CRÈCHES de Noel dans les mairies (symbole religieux ou culturel ?). Deux visions : laicite STRICTE (la religion doit etre invisible dans l\'espace public) vs laicite LIBERALE (l\'Etat est neutre mais les individus s\'expriment librement). En gros : tout le monde est d\'accord sur le PRINCIPE de laicite. C\'est son APPLICATION qui fait debat.' },
                    { question: 'C\'est quoi le Conseil constitutionnel ?', answer: 'Le CONSEIL CONSTITUTIONNEL = l\'institution qui verifie que les LOIS respectent la CONSTITUTION. 9 membres nommes pour 9 ans (3 par le president, 3 par le president de l\'Assemblee, 3 par le president du Senat). Roles : controler la CONSTITUTIONNALITE des lois AVANT leur application, traiter les QPC (Questions Prioritaires de Constitutionnalite) = un citoyen peut contester une loi qu\'il juge contraire a la Constitution, valider les ELECTIONS presidentielles et legislatives. En gros : le Conseil constitutionnel est le "gardien" de la Constitution. Mots difficiles : "QPC" = un citoyen conteste une loi devant le Conseil constitutionnel.' },
                    { question: 'C\'est quoi l\'identite nationale ?', answer: 'L\'IDENTITE NATIONALE = ce qui fait qu\'on se sent "francais." C\'est un sujet COMPLEXE et sensible. Elements : la LANGUE (le francais), l\'HISTOIRE commune (Revolution, guerres, decolonisation), les VALEURS republicaines (liberte, egalite, fraternite, laicite), la CULTURE (litterature, gastronomie, art de vivre). Debat : l\'identite nationale est-elle FIGEE ou EVOLUTIVE ? Peut-on devenir francais sans etre "ne" francais ? L\'immigration enrichit-elle ou menace-t-elle l\'identite ? En gros : etre francais ne se resume pas a un passeport. C\'est un ensemble de valeurs, d\'histoire et de culture partage.' }
                ],
                quiz: [
                    { question: 'La loi de separation de l\'Eglise et de l\'Etat date de :', options: ['1789', '1848', '1905', '1958'], correctIndex: 2, explanation: 'La loi de 1905 instaure la laicite : l\'Etat ne reconnait, ne salarie ni ne subventionne aucun culte.' },
                    { question: 'La separation des pouvoirs est une idee de :', options: ['Rousseau', 'Montesquieu', 'Voltaire', 'De Gaulle'], correctIndex: 1, explanation: 'Montesquieu theorise la separation des pouvoirs dans L\'Esprit des lois (1748) pour eviter la tyrannie.' },
                    { question: 'Le pouvoir legislatif en France est exerce par :', options: ['Le President', 'Le Gouvernement', 'L\'Assemblee nationale et le Senat', 'Les juges'], correctIndex: 2, explanation: 'Le Parlement (Assemblee nationale + Senat) vote les lois. C\'est le pouvoir legislatif.' },
                    { question: 'La Constitution de la Ve Republique date de :', options: ['1789', '1848', '1946', '1958'], correctIndex: 3, explanation: 'La Ve Republique est fondee en 1958 par De Gaulle. Sa Constitution definit les institutions actuelles.' },
                    { question: 'La laicite garantit :', options: ['L\'atheisme obligatoire', 'La liberte de croire ou de ne pas croire', 'L\'interdiction des religions', 'La suprematie d\'une religion'], correctIndex: 1, explanation: 'La laicite = neutralite de l\'Etat. Chacun est libre de croire ou non. L\'Etat ne favorise aucune religion.' },
                    { question: 'Pour Rousseau, le contrat social signifie que :', options: ['Le roi decide seul', 'Les citoyens obeissent a la loi qu\'ils ont choisie ensemble', 'Chacun fait ce qu\'il veut', 'L\'Etat n\'existe pas'], correctIndex: 1, explanation: 'Rousseau dit que les citoyens acceptent la loi parce qu\'elle exprime la VOLONTE GENERALE : ils se sont mis d\'accord collectivement.' },
                    { question: 'Le Conseil constitutionnel a pour role de :', options: ['Voter les lois', 'Verifier que les lois respectent la Constitution', 'Commander l\'armee', 'Nommer les ministres'], correctIndex: 1, explanation: 'Le Conseil constitutionnel est le "gardien" de la Constitution. Il verifie que les lois votees sont conformes aux droits fondamentaux.' },
                    { question: 'Une Republique est forcement une democratie :', options: ['Vrai', 'Faux', 'Seulement en Europe', 'Seulement si le president est elu'], correctIndex: 1, explanation: 'FAUX. Une republique peut ne pas etre democratique (ex : la Chine). Republique = pas de roi. Democratie = le peuple decide.' }
                ]
            },

            // ================================================================
            // SECTION 2 : LA DEMOCRATIE ET LA CITOYENNETE
            // ================================================================
            {
                id: 'democratie-citoyennete',
                title: 'Democratie et citoyennete',
                icon: '\uD83D\uDDF3\uFE0F',
                content: '<h3>Etre citoyen dans une democratie</h3>',
                flashcards: [
                    { question: 'C\'est quoi la democratie ?', answer: 'DEMOCRATIE = le pouvoir appartient au PEUPLE. Etymologie : demos (peuple) + kratos (pouvoir). DIRECTE = les citoyens votent eux-memes les lois (Athenes antique, referendum). REPRESENTATIVE = les citoyens elisent des REPRESENTANTS qui votent les lois (deputes, senateurs). La France est une democratie REPRESENTATIVE. En gros : en democratie, c\'est le peuple qui decide, soit directement, soit via des elus.' },
                    { question: 'C\'est quoi le droit de vote en France ?', answer: 'Chronologie : 1791 = suffrage CENSITAIRE (seuls les riches votent). 1848 = suffrage universel MASCULIN. 1944 = droit de vote des FEMMES. 1974 = majorite a 18 ANS (avant : 21 ans). Conditions aujourd\'hui : avoir 18 ans, etre de nationalite francaise, etre inscrit sur les listes electorales. En gros : le droit de vote s\'est elargi progressivement. Voter est un DROIT et un DEVOIR civique.' },
                    { question: 'C\'est quoi l\'abstention ?', answer: 'L\'ABSTENTION = ne pas aller voter. En France, elle augmente : parfois plus de 50% aux elections. Causes : desinteret, sentiment que "ca ne change rien", mefiance envers les politiques, manque d\'information. Consequences : les elus representent une MINORITE de la population. En gros : l\'abstention est un probleme pour la democratie car les elus sont choisis par de moins en moins de gens.' },
                    { question: 'C\'est quoi l\'engagement citoyen ?', answer: 'Etre citoyen, ce n\'est PAS juste voter. C\'est aussi : s\'engager dans une ASSOCIATION (humanitaire, environnementale, sportive). Participer a la VIE LOCALE (conseil municipal, conseil de quartier). S\'INFORMER et debattre. RESPECTER les lois et les autres. Faire du BENEVOLAT. Exemples : Les Restos du Coeur, Amnesty International, les marches pour le climat. En gros : la citoyennete = participer activement a la vie de la societe.' },
                    { question: 'C\'est quoi les partis politiques ?', answer: 'Un PARTI = un groupe organise qui a un PROGRAMME et qui veut acceder au POUVOIR par les elections. En France : GAUCHE (PS, LFI, EELV) = egalite sociale, services publics, ecologie. CENTRE (Renaissance, MoDem) = ni gauche ni droite, liberalisme modere. DROITE (LR) = autorite, securite, economie de marche. EXTREME DROITE (RN) = immigration, identite nationale. EXTREME GAUCHE (NPA, LO) = anticapitalisme. En gros : les partis permettent aux citoyens de choisir une DIRECTION pour le pays.' },
                    { question: 'C\'est quoi les medias et la democratie ?', answer: 'Les medias = la PRESSE, la TV, la radio, Internet. Ils sont essentiels a la democratie car ils INFORMENT les citoyens. LIBERTE DE LA PRESSE = les journalistes peuvent critiquer le pouvoir (article 11 de la DDHC). Risques : la CONCENTRATION des medias (quelques milliardaires possedent les grands journaux), les FAKE NEWS (fausses informations diffusees sur Internet), la DESINFORMATION. En gros : pas de democratie sans medias libres. Mais les medias doivent etre INDEPENDANTS et les citoyens doivent etre CRITIQUES.' },
                    { question: 'C\'est quoi le populisme ?', answer: 'Le POPULISME = un discours politique qui oppose le "PEUPLE" (presente comme bon, honnete) aux "ELITES" (presentees comme corrompues, deconnectees). Ce n\'est ni de gauche ni de droite, on en trouve partout. Exemples : Trump aux USA, Bolsonaro au Bresil, certains partis europeens. Strategies : simplifier les problemes complexes, designer des BOUCS EMISSAIRES (immigres, elites, Europe), promettre des solutions FACILES. En gros : le populisme pretend parler "au nom du peuple" mais simplifie la realite. Mots difficiles : "populisme" vient de "populus" (peuple en latin). "Demagogue" = celui qui flatte le peuple pour gagner le pouvoir.' },
                    { question: 'C\'est quoi la democratie directe et le debat sur le RIC ?', answer: 'La democratie DIRECTE = les citoyens votent EUX-MEMES les lois (sans passer par des elus). Outils : le REFERENDUM (le president pose une question au peuple, oui/non). Le RIC (Referendum d\'Initiative Citoyenne) = les citoyens EUX-MEMES proposent un referendum. Revendication des Gilets Jaunes (2018). En Suisse, le referendum d\'initiative populaire existe depuis longtemps. Debat : POUR = plus de pouvoir au peuple. CONTRE = risque de manipulation, de decisions emotionnelles. En gros : la democratie directe donne plus de pouvoir aux citoyens mais pose des questions de faisabilite.' },
                    { question: 'L\'engagement des jeunes : nouvelles formes de participation', answer: 'Les jeunes s\'engagent DIFFEREMMENT des generations precedentes. Nouvelles formes : les MARCHES POUR LE CLIMAT (Greta Thunberg, Fridays for Future, depuis 2018). L\'ACTIVISME sur les reseaux sociaux (petitions en ligne, hashtags, mobilisation via Instagram/TikTok). Le BENEVOLAT et le SERVICE CIVIQUE. Les COLLECTIFS locaux (aide aux sans-abri, jardins partages). MAIS les jeunes votent MOINS que les anciens (abstention forte chez les 18-25 ans). En gros : les jeunes ne se desinteressent pas de la politique. Ils s\'engagent AUTREMENT, souvent en dehors des partis.' },
                    { question: 'Fake news et debat democratique', answer: 'Les FAKE NEWS (fausses informations) sont un danger pour la democratie. Elles circulent VITE sur les reseaux sociaux car elles sont souvent CHOQUANTES ou EMOTIONNELLES. Consequences : manipulation des ELECTIONS (trolls russes en 2016 aux USA), diffusion de THEORIES DU COMPLOT, perte de CONFIANCE dans les medias serieux. Comment lutter ? VERIFIER les sources (qui parle ? d\'ou vient l\'info ?). Utiliser des sites de FACT-CHECKING (AFP Factuel, Les Decodeurs). Developper l\'ESPRIT CRITIQUE a l\'ecole. En gros : les fake news profitent de notre paresse intellectuelle. L\'antidote = verifier avant de partager.' },
                    { question: 'C\'est quoi la citoyennete europeenne ?', answer: 'La CITOYENNETE EUROPEENNE existe depuis le traite de MAASTRICHT (1992). Tout citoyen d\'un pays de l\'UE est AUSSI citoyen europeen. Droits : CIRCULER et TRAVAILLER librement dans les 27 pays de l\'UE. VOTER aux elections europeennes et municipales dans le pays ou on reside. Etre PROTEGE par les ambassades de n\'importe quel pays de l\'UE a l\'etranger. Beneficier du programme ERASMUS (etudes a l\'etranger). En gros : la citoyennete europeenne donne des droits au-dela des frontieres nationales. Mots difficiles : "traite de Maastricht" = le traite de 1992 qui cree l\'Union europeenne telle qu\'on la connait.' }
                ],
                quiz: [
                    { question: 'Les femmes obtiennent le droit de vote en France en :', options: ['1789', '1848', '1944', '1958'], correctIndex: 2, explanation: 'Les femmes obtiennent le droit de vote en 1944 et votent pour la premiere fois en avril 1945.' },
                    { question: 'L\'abstention c\'est :', options: ['Voter blanc', 'Ne pas aller voter', 'Voter pour un petit parti', 'Annuler son vote'], correctIndex: 1, explanation: 'L\'abstention = ne pas se deplacer pour voter. C\'est different du vote blanc (se deplacer mais ne choisir aucun candidat).' },
                    { question: 'La France est une democratie :', options: ['Directe', 'Representative', 'Monarchique', 'Federale'], correctIndex: 1, explanation: 'En France, les citoyens elisent des representants (deputes, president) qui exercent le pouvoir en leur nom.' },
                    { question: 'La liberte de la presse est garantie par :', options: ['L\'article 1 de la Constitution', 'L\'article 11 de la DDHC de 1789', 'La loi de 1905', 'Le Code penal'], correctIndex: 1, explanation: 'L\'article 11 de la DDHC (1789) affirme la libre communication des pensees et des opinions.' },
                    { question: 'L\'engagement citoyen c\'est :', options: ['Uniquement voter', 'Participer activement a la vie de la societe', 'Payer ses impots', 'Regarder les infos'], correctIndex: 1, explanation: 'L\'engagement citoyen va au-dela du vote : associations, benevolat, debat, respect des lois, solidarite.' },
                    { question: 'Le populisme se caracterise par :', options: ['Un programme economique precis', 'L\'opposition entre le peuple et les elites', 'Le respect des institutions', 'L\'abstention electorale'], correctIndex: 1, explanation: 'Le populisme oppose un "bon peuple" a des "elites corrompues" et propose des solutions simplistes aux problemes complexes.' },
                    { question: 'La citoyennete europeenne existe depuis :', options: ['1957', '1992', '2002', '2015'], correctIndex: 1, explanation: 'Le traite de Maastricht (1992) cree la citoyennete europeenne : libre circulation, vote aux europeennes, protection consulaire.' },
                    { question: 'Les fake news menacent la democratie car :', options: ['Elles informent trop bien les citoyens', 'Elles manipulent l\'opinion et faussent le debat', 'Elles sont toujours vraies', 'Elles sont publiees par les journalistes'], correctIndex: 1, explanation: 'Les fake news diffusent de fausses informations qui manipulent l\'opinion, faussent les elections et detruisent la confiance dans les medias.' }
                ]
            },

            // ================================================================
            // SECTION 3 : LES GRANDS ENJEUX ETHIQUES
            // ================================================================
            {
                id: 'enjeux-ethiques',
                title: 'Les grands enjeux ethiques',
                icon: '\uD83E\uDD14',
                content: '<h3>Bioethique, environnement, numerique</h3>',
                flashcards: [
                    { question: 'C\'est quoi la bioethique ?', answer: 'La BIOETHIQUE = les questions MORALES posees par la biologie et la medecine. Exemples : la PMA (Procreation Medicalement Assistee) — qui peut en beneficier ? La GPA (Gestation Pour Autrui) — une femme peut-elle porter l\'enfant d\'une autre ? Le don d\'organes — peut-on vendre ses organes ? L\'euthanasie — a-t-on le droit de choisir sa mort ? Les lois de bioethique sont revisees tous les 7 ans en France. En gros : la bioethique = quand la science peut faire quelque chose, DOIT-ELLE le faire ?' },
                    { question: 'C\'est quoi l\'euthanasie et le debat en France ?', answer: 'EUTHANASIE = aider quelqu\'un a MOURIR pour abreger ses souffrances. ILLEGALE en France (mais legale en Belgique, Pays-Bas, Canada). En France : la loi CLAEYS-LEONETTI (2016) autorise la "sedation profonde et continue" (endormir jusqu\'a la mort naturelle) mais PAS l\'euthanasie active. Debat en cours (2024-2025) : le projet de loi sur "l\'aide a mourir." POUR : liberte, dignite, fin des souffrances. CONTRE : risque de derives, protection des personnes vulnerables. En gros : un debat entre la liberte de choisir sa mort et le devoir de proteger la vie.' },
                    { question: 'C\'est quoi l\'ethique du numerique ?', answer: 'Le NUMERIQUE pose des questions ethiques nouvelles : 1) Les DONNEES PERSONNELLES : qui a le droit de collecter tes donnees ? (RGPD 2018). 2) L\'INTELLIGENCE ARTIFICIELLE : peut-elle decider a la place de l\'homme ? (recrutement, justice, medecine). 3) Le DROIT A L\'OUBLI : peut-on faire effacer ses traces sur Internet ? 4) Le CYBERHARCELEMENT : comment proteger les victimes ? En gros : la technologie avance plus vite que les lois. L\'ethique doit poser des LIMITES.' },
                    { question: 'C\'est quoi la justice sociale ?', answer: 'La JUSTICE SOCIALE = reduire les INEGALITES entre les citoyens. Outils : les IMPOTS (les riches paient plus → redistribution). La SECURITE SOCIALE (sante, chomage, retraite pour tous). L\'EDUCATION gratuite et obligatoire. Les MINIMA SOCIAUX (RSA, APL). Debat : jusqu\'ou aller ? Trop de redistribution = moins de motivation ? Pas assez = inegalites explosent ? En gros : la justice sociale = faire en sorte que la naissance ne determine pas le destin.' },
                    { question: 'C\'est quoi la desobeissance civile ?', answer: 'La DESOBEISSANCE CIVILE = refuser de respecter une loi qu\'on juge INJUSTE, de facon NON-VIOLENTE et PUBLIQUE, en acceptant la PUNITION. Exemples : Rosa PARKS (1955, refuse de ceder sa place dans le bus aux USA → lutte contre la segregation). Gandhi (non-violence contre la colonisation britannique en Inde). Les Faucheurs d\'OGM (destruction de champs OGM en France). En gros : parfois, desobeir a la loi est un acte CITOYEN. Mais il faut assumer les consequences. Mots difficiles : "desobeissance civile" = desobeir a la loi pour des raisons de CONSCIENCE, pas d\'interet personnel.' },
                    { question: 'L\'ethique de l\'intelligence artificielle : quels problemes ?', answer: 'L\'IA pose des questions ethiques GRAVES. Les BIAIS ALGORITHMIQUES : l\'IA reproduit les prejuges de ses donnees (un algorithme de recrutement qui discrimine les femmes, un logiciel de police qui cible les minorites). Les ARMES AUTONOMES : des robots tueurs qui decident seuls de tirer. Le remplacement des EMPLOIS par les machines. La SURVEILLANCE de masse (reconnaissance faciale). En gros : l\'IA est un outil puissant mais sans ethique, elle peut devenir dangereuse. Qui est RESPONSABLE quand une IA se trompe ? Mots difficiles : "biais algorithmique" = erreur systematique dans un algorithme qui produit des resultats injustes.' },
                    { question: 'L\'ethique environnementale : les droits de la nature', answer: 'Traditionnellement, seuls les HUMAINS ont des droits. Mais de nouveaux courants disent que la NATURE aussi en merite. L\'ECOCIDE = destruction massive d\'un ecosysteme (deforestation, pollution des oceans). Certains pays reconnaissent des droits a la nature : l\'EQUATEUR (2008) donne des droits a la Pachamama (Terre-mere). La NOUVELLE-ZELANDE (2017) accorde un statut juridique a un fleuve. Debat en Europe : faut-il inscrire l\'ecocide dans le droit penal ? En gros : si la nature a des droits, detruire une foret pourrait devenir un CRIME. Mots difficiles : "ecocide" = eco (ecologie) + cide (tuer). Destruction deliberee de l\'environnement.' },
                    { question: 'La peine de mort dans le monde : ou en est-on ?', answer: 'La peine de mort est ABOLIE en France depuis 1981 (loi BADINTER). 106 pays l\'ont abolie dans le monde. MAIS elle existe encore dans certains pays : USA (dans certains Etats), Chine, Iran, Arabie Saoudite, Coree du Nord. Arguments POUR (des partisans) : dissuasion, justice pour les victimes. Arguments CONTRE : risque d\'erreur judiciaire (on ne peut pas "de-executer" un innocent), la vie est un droit fondamental, pas d\'effet prouve sur la criminalite. En gros : la peine de mort recule dans le monde mais n\'a pas disparu. L\'Europe l\'a entierement abolie.' },
                    { question: 'Le bien-etre animal et l\'ethique', answer: 'La question du BIEN-ETRE ANIMAL prend de l\'ampleur. Les animaux sont des etres SENSIBLES (ils ressentent la douleur). Problemes : l\'ELEVAGE INDUSTRIEL (poules en batterie, cochons en cages), les TESTS sur les animaux (cosmetiques, medecine), la CORRIDA, les CIRQUES avec animaux. Evolutions : la loi francaise (2015) reconnait les animaux comme des "etres vivants doues de sensibilite" (plus des "biens meubles"). L\'interdiction des animaux sauvages dans les cirques (2028). En gros : on ne peut plus traiter les animaux comme des objets. La question est : quels DROITS leur donner ?' },
                    { question: 'Rawls et le voile d\'ignorance : c\'est quoi la justice ?', answer: 'John RAWLS (Theorie de la justice, 1971) propose une experience de pensee : le VOILE D\'IGNORANCE. Imagine que tu ne sais PAS ou tu vas naitre : riche ou pauvre, homme ou femme, blanc ou noir, valide ou handicape. Quelle societe choisirais-tu ? Reponse de Rawls : tu choisirais une societe JUSTE, qui protege les plus FAIBLES (car tu pourrais etre l\'un d\'eux). En gros : la justice = organiser la societe comme si on ne savait pas quelle place on y occuperait. Mots difficiles : "voile d\'ignorance" = ne pas savoir quelle sera sa position sociale pour juger de facon impartiale.' }
                ],
                quiz: [
                    { question: 'La bioethique pose des questions sur :', options: ['L\'economie', 'Les limites morales de la biologie et de la medecine', 'L\'urbanisme', 'Le sport'], correctIndex: 1, explanation: 'La bioethique questionne : PMA, euthanasie, don d\'organes, manipulation genetique — quand la science PEUT, DOIT-elle ?' },
                    { question: 'Le RGPD (2018) protege :', options: ['Les entreprises', 'Les donnees personnelles des citoyens europeens', 'Les brevets', 'Les droits d\'auteur'], correctIndex: 1, explanation: 'Le RGPD oblige les entreprises a proteger les donnees personnelles et donne aux citoyens un droit de controle sur leurs donnees.' },
                    { question: 'La desobeissance civile est :', options: ['Violente et secrete', 'Non-violente et publique, avec acceptation de la punition', 'Un crime', 'Reservee aux politiciens'], correctIndex: 1, explanation: 'La desobeissance civile est pacifique, publique et le citoyen accepte les sanctions. C\'est un acte de conscience.' },
                    { question: 'Rosa Parks est connue pour :', options: ['Avoir vote la premiere', 'Avoir refuse de ceder sa place dans un bus segregue', 'Avoir ete presidente', 'Avoir invente Internet'], correctIndex: 1, explanation: 'En 1955, Rosa Parks refuse de ceder sa place a un Blanc dans un bus de Montgomery (Alabama). Son geste lance le mouvement des droits civiques.' },
                    { question: 'L\'euthanasie en France est :', options: ['Legale sans condition', 'Illegale mais le debat est en cours', 'Autorisee depuis 2020', 'Autorisee pour les mineurs'], correctIndex: 1, explanation: 'L\'euthanasie active est illegale en France. La loi Claeys-Leonetti (2016) permet la sedation profonde. Un projet de loi sur "l\'aide a mourir" est en discussion.' },
                    { question: 'Un biais algorithmique c\'est :', options: ['Un bug informatique', 'Une erreur systematique qui produit des resultats injustes', 'Un virus', 'Un type de programme'], correctIndex: 1, explanation: 'Un biais algorithmique = l\'IA reproduit des prejuges presents dans ses donnees d\'entrainement (discrimination, stereotypes).' },
                    { question: 'Le "voile d\'ignorance" de Rawls invite a :', options: ['Porter un voile religieux', 'Choisir une societe juste sans savoir quelle place on y occuperait', 'Ignorer les problemes', 'Voter sans information'], correctIndex: 1, explanation: 'Rawls dit : si tu ne savais pas si tu serais riche ou pauvre, tu choisirais une societe qui protege les plus faibles.' },
                    { question: 'La peine de mort en France a ete abolie en :', options: ['1968', '1981', '1995', '2002'], correctIndex: 1, explanation: 'Robert Badinter fait abolir la peine de mort en France en 1981. La France est le dernier grand pays d\'Europe occidentale a l\'abolir.' }
                ]
            },

            // ================================================================
            // SECTION 4 : DEFENDRE LA PAIX ET LES DROITS DE L'HOMME
            // ================================================================
            {
                id: 'paix-droits-homme',
                title: 'Defendre la paix et les droits de l\'homme',
                icon: '\uD83D\uDD4A\uFE0F',
                content: '<h3>Institutions internationales, droit humanitaire, responsabilite de proteger</h3>',
                flashcards: [
                    { question: 'C\'est quoi l\'ONU ?', answer: 'L\'ONU (Organisation des Nations Unies) est creee en 1945 apres la Seconde Guerre mondiale. But : MAINTENIR LA PAIX dans le monde et defendre les droits de l\'homme. 193 Etats membres. Organes principaux : l\'ASSEMBLEE GENERALE (tous les Etats, 1 voix chacun), le CONSEIL DE SECURITE (15 membres dont 5 permanents avec droit de VETO : USA, Russie, Chine, France, Royaume-Uni). Limites : le veto BLOQUE souvent les decisions (exemple : guerre en Syrie). En gros : l\'ONU est le lieu ou les pays du monde essaient de regler leurs problemes sans faire la guerre.' },
                    { question: 'C\'est quoi l\'OTAN ?', answer: 'L\'OTAN (Organisation du Traite de l\'Atlantique Nord) est une alliance MILITAIRE creee en 1949. But : les pays membres se DEFENDENT mutuellement. Article 5 : si un membre est attaque, TOUS les autres doivent l\'aider. 31 pays membres (Europe + USA + Canada). Contexte : creee pendant la Guerre froide contre l\'URSS. Debat actuel : faut-il une defense europeenne independante de l\'OTAN ? L\'adhesion de la Finlande et de la Suede apres l\'invasion de l\'Ukraine (2022). En gros : l\'OTAN = les pays occidentaux se protegent ensemble militairement.' },
                    { question: 'C\'est quoi le droit international humanitaire ?', answer: 'Le droit international humanitaire (DIH) = les regles qui s\'appliquent PENDANT LES GUERRES pour limiter les souffrances. Base sur les Conventions de GENEVE (1949). Regles principales : ne pas attaquer les CIVILS (hopitaux, ecoles), traiter les PRISONNIERS de guerre dignement, ne pas utiliser certaines ARMES (chimiques, biologiques, mines antipersonnel), proteger la CROIX-ROUGE qui porte secours. En gros : meme en guerre, il y a des regles. Les violer = CRIME DE GUERRE. Mots difficiles : "conventions" = accords entre Etats. "DIH" = droit international humanitaire.' },
                    { question: 'C\'est quoi la responsabilite de proteger (R2P) ?', answer: 'La R2P (Responsibility to Protect) = un principe adopte par l\'ONU en 2005. Idee : quand un Etat ne PROTEGE PAS sa population (genocide, crimes de guerre, nettoyage ethnique), la COMMUNAUTE INTERNATIONALE a le devoir d\'intervenir. Exemples : intervention en Libye (2011) pour proteger les civils. Limites : qui decide d\'intervenir ? Risque d\'ingérence (s\'imposer dans les affaires d\'un autre pays). Certains pays refusent ce principe (Russie, Chine). En gros : la R2P dit que la souverainete d\'un Etat a des LIMITES. Si un Etat massacre son peuple, le monde doit agir. Mots difficiles : "souverainete" = le droit d\'un Etat a decider seul de ses affaires. "Ingerence" = s\'occuper des affaires d\'un autre pays.' },
                    { question: 'Paix vs securite : c\'est quoi le debat ?', answer: 'La PAIX = absence de guerre, de conflit arme. La SECURITE = protection contre les menaces (terrorisme, cyberattaques, criminalite). Le debat : peut-on SACRIFIER des libertes pour plus de securite ? Exemples : apres les attentats de 2015, la France a declare l\'ETAT D\'URGENCE (fouilles, assignations a residence, surveillance). La loi RENSEIGNEMENT (2015) permet la surveillance des communications. POUR : il faut proteger les citoyens. CONTRE : trop de securite tue la liberte (Big Brother). En gros : l\'equilibre entre liberte et securite est un defi permanent pour la democratie.' },
                    { question: 'C\'est quoi la Cour penale internationale (CPI) ?', answer: 'La CPI est creee en 2002 (Statut de Rome, 1998). But : juger les personnes accusees de CRIMES INTERNATIONAUX : genocide, crimes contre l\'humanite, crimes de guerre. Siege : La Haye (Pays-Bas). Limites : les USA, la Russie et la Chine n\'ont PAS ratifie le statut. La CPI ne peut pas forcer les Etats a livrer les accuses. Exemples : mandats d\'arret contre des dirigeants (Omar el-Bechir, Soudan). En gros : la CPI est le tribunal du monde, mais il n\'a pas assez de pouvoir pour punir tout le monde.' },
                    { question: 'C\'est quoi la Declaration universelle des droits de l\'homme (DUDH) ?', answer: 'Adoptee le 10 decembre 1948 par l\'Assemblee generale de l\'ONU. 30 articles qui definissent les droits FONDAMENTAUX de TOUT etre humain. Article 1 : "Tous les etres humains naissent libres et egaux en dignite et en droits." Droits proteges : vie, liberte, education, travail, asile, pas de torture ni d\'esclavage. C\'est une DECLARATION (pas un traite), donc pas juridiquement contraignante. Mais elle inspire toutes les constitutions modernes. En gros : la DUDH dit ce que chaque humain merite, partout dans le monde. Mots difficiles : "contraignant" = qui oblige legalement.' },
                    { question: 'C\'est quoi les Casques bleus ?', answer: 'Les CASQUES BLEUS = les forces de MAINTIEN DE LA PAIX de l\'ONU. Ils portent un casque bleu (couleur de l\'ONU). Leur mission : s\'interposer entre les belligerants, proteger les CIVILS, surveiller les CESSEZ-LE-FEU. Ils ne font PAS la guerre, ils maintiennent la paix. Exemples : missions au Liban (FINUL), en RDC, au Mali. Limites : ils ne peuvent pas toujours empecher les massacres (echec au Rwanda en 1994, a Srebrenica en 1995). En gros : les Casques bleus sont les "soldats de la paix" de l\'ONU, mais leur pouvoir est limite.' },
                    { question: 'La dissuasion nucleaire : c\'est quoi le debat ?', answer: 'La DISSUASION NUCLEAIRE = posseder la bombe atomique pour DECOURAGER l\'ennemi d\'attaquer. Principe : "si tu m\'attaques, je te detruis aussi." C\'est la "destruction mutuelle assuree" (MAD). 9 pays ont la bombe : USA, Russie, Chine, France, Royaume-Uni, Inde, Pakistan, Israel, Coree du Nord. POUR : la bombe a empeche une 3e guerre mondiale (la "paix par la terreur"). CONTRE : un accident ou un dirigeant fou pourrait detruire le monde. Le TIAN (2021) = traite d\'interdiction des armes nucleaires (non signe par les puissances nucleaires). En gros : la dissuasion nucleaire = parier que la PEUR empeche la guerre.' },
                    { question: 'C\'est quoi un couloir humanitaire et la protection des refugies ?', answer: 'Un COULOIR HUMANITAIRE = un passage securise pour evacuer des CIVILS d\'une zone de guerre. Il doit etre respecte par TOUTES les parties en conflit. Probleme : ils sont souvent violes (Syrie, Ukraine). Les REFUGIES = des personnes qui fuient leur pays a cause de la guerre, de la persecution. La CONVENTION DE GENEVE (1951) oblige les pays a les accueillir et a ne pas les renvoyer vers le danger (principe de "non-refoulement"). En gros : les refugies ont des DROITS. Les couloirs humanitaires sont leur bouee de sauvetage. Mots difficiles : "non-refoulement" = interdiction de renvoyer un refugie vers un pays ou sa vie est en danger.' },
                    { question: 'Exemples historiques de reconciliation entre ennemis', answer: 'La reconciliation FRANCO-ALLEMANDE : apres 3 guerres (1870, 1914, 1939), la France et l\'Allemagne construisent la PAIX. Le traite de l\'ELYSEE (1963, De Gaulle-Adenauer) scelle l\'amitie. L\'UE est nee de cette reconciliation. Le RWANDA : apres le genocide de 1994 (800 000 morts), les tribunaux GACACA (justice traditionnelle) permettent aux bourreaux et aux victimes de se parler. L\'Afrique du Sud : apres l\'apartheid, la Commission VERITE ET RECONCILIATION (Mandela, Tutu). En gros : la reconciliation est POSSIBLE, meme apres les pires horreurs. Elle demande du temps, du courage et de la justice.' },
                    { question: 'Soft power vs hard power : c\'est quoi la difference ?', answer: 'Le HARD POWER = la puissance MILITAIRE et ECONOMIQUE. Forcer les autres par les armes ou les sanctions. Exemple : une guerre, un embargo. Le SOFT POWER = l\'INFLUENCE culturelle, diplomatique, ideologique. Convaincre les autres sans les forcer. Exemples : Hollywood (cinema americain), la K-pop (Coree du Sud), la gastronomie francaise, l\'aide humanitaire. Concept invente par Joseph NYE (1990). En gros : le hard power = la force. Le soft power = la seduction. Les grandes puissances utilisent les DEUX. Mots difficiles : "soft" = doux. "Hard" = dur. Le soft power attire, le hard power contraint.' }
                ],
                quiz: [
                    { question: 'L\'ONU a ete creee en :', options: ['1918', '1939', '1945', '1948'], correctIndex: 2, explanation: 'L\'ONU est creee en 1945 apres la Seconde Guerre mondiale pour maintenir la paix et defendre les droits de l\'homme.' },
                    { question: 'Les Conventions de Geneve protegent :', options: ['Le commerce international', 'Les civils et les prisonniers de guerre', 'Les frontières des Etats', 'Les entreprises'], correctIndex: 1, explanation: 'Les Conventions de Geneve (1949) fixent les regles pour proteger les civils et les prisonniers pendant les guerres.' },
                    { question: 'La R2P signifie :', options: ['Right to Protest', 'Responsabilite de proteger', 'Reglement de police', 'Reserve de puissance'], correctIndex: 1, explanation: 'La R2P (Responsibility to Protect) = la communaute internationale doit intervenir si un Etat ne protege pas son peuple.' },
                    { question: 'La CPI juge les crimes de :', options: ['Vol et escroquerie', 'Genocide, crimes de guerre et crimes contre l\'humanite', 'Infractions routieres', 'Fraude fiscale'], correctIndex: 1, explanation: 'La CPI (Cour penale internationale, 2002) juge les crimes les plus graves : genocide, crimes de guerre, crimes contre l\'humanite.' },
                    { question: 'La DUDH a ete adoptee en :', options: ['1789', '1945', '1948', '1958'], correctIndex: 2, explanation: 'La Declaration universelle des droits de l\'homme a ete adoptee le 10 decembre 1948 par l\'Assemblee generale de l\'ONU.' },
                    { question: 'Les Casques bleus sont :', options: ['L\'armee de l\'OTAN', 'Les forces de maintien de la paix de l\'ONU', 'La police internationale', 'Les gardes du corps des presidents'], correctIndex: 1, explanation: 'Les Casques bleus sont les soldats de la paix de l\'ONU. Ils s\'interposent entre belligerants et protegent les civils.' },
                    { question: 'Le soft power c\'est :', options: ['La puissance militaire', 'L\'influence par la culture, la diplomatie et l\'image', 'Les armes nucleaires', 'Les sanctions economiques'], correctIndex: 1, explanation: 'Le soft power (Joseph Nye) = influencer les autres par la culture, les valeurs, la diplomatie. Le contraire du hard power (la force).' },
                    { question: 'La dissuasion nucleaire repose sur le principe de :', options: ['Premiere frappe', 'Destruction mutuelle assuree', 'Desarmement total', 'Superiority technologique'], correctIndex: 1, explanation: 'La dissuasion nucleaire = "si tu m\'attaques, je te detruis aussi." La peur de la destruction mutuelle empeche l\'attaque.' }
                ]
            },

            // ================================================================
            // SECTION 5 : S'ENGAGER ET DEBATTRE EN DEMOCRATIE
            // ================================================================
            {
                id: 'engagement-debat',
                title: 'S\'engager et debattre en democratie',
                icon: '\uD83D\uDCE2',
                content: '<h3>Formes d\'engagement, desobeissance civile, debat democratique</h3>',
                flashcards: [
                    { question: 'Quelles sont les formes d\'engagement citoyen ?', answer: 'Il y a BEAUCOUP de facons de s\'engager : le VOTE (le plus basique, un droit et un devoir civique). Les ASSOCIATIONS (humanitaires, ecologiques, sportives, culturelles). Les SYNDICATS (defendre les droits des travailleurs : CGT, CFDT, FO). Les PETITIONS (demander un changement par des signatures, desormais en ligne). Les MANIFESTATIONS (marcher dans la rue pour exprimer une opinion). Le BENEVOLAT (donner de son temps gratuitement). Le SERVICE CIVIQUE (mission d\'interet general pour les 16-25 ans). En gros : s\'engager = agir pour que la societe change. Ca ne se limite pas au vote.' },
                    { question: 'C\'est quoi un syndicat et a quoi ca sert ?', answer: 'Un SYNDICAT = une organisation qui defend les DROITS DES TRAVAILLEURS. Reconnu en France depuis la loi WALDECK-ROUSSEAU (1884). Roles : negocier les SALAIRES et les conditions de travail, organiser des GREVES si necessaire, representer les salaries face aux patrons. Principaux syndicats : CGT, CFDT, FO, SUD, UNSA. Le taux de syndicalisation en France est FAIBLE (environ 8%, un des plus bas d\'Europe). En gros : les syndicats sont les "avocats" des travailleurs. Mots difficiles : "syndicalisation" = le fait d\'adherer a un syndicat.' },
                    { question: 'La desobeissance civile : rappel et approfondissement', answer: 'Rappel : DESOBEIR a une loi jugee INJUSTE, de facon NON-VIOLENTE et PUBLIQUE. Henry David THOREAU (1849) invente le concept en refusant de payer l\'impot qui finance la guerre contre le Mexique. APPROFONDISSEMENT pour le Bac : quand la desobeissance civile est-elle LEGITIME ? Arguments POUR : la loi n\'est pas toujours juste (lois racistes, loi de Vichy). Le citoyen a un devoir de CONSCIENCE. Arguments CONTRE : si chacun desobeit a la loi qu\'il n\'aime pas, c\'est le CHAOS. L\'Etat de droit suppose le respect de la loi. En gros : la desobeissance civile = un DERNIER RECOURS quand la loi est injuste et que les voies legales ne marchent pas.' },
                    { question: 'Comment structurer un argument pour le debat EMC ?', answer: 'Methode en 4 etapes : 1) THESE : enoncer clairement sa position ("Je pense que..."). 2) ARGUMENT : donner une raison ("parce que..."). 3) EXEMPLE : illustrer avec un fait precis, une loi, un evenement historique. 4) NUANCE : reconnaitre la complexite ("cependant, on peut aussi penser que..."). Connecteurs utiles : "d\'une part / d\'autre part", "certes... mais", "en revanche", "toutefois." En gros : un bon argument = une idee + une raison + un exemple + de la nuance. Ne JAMAIS dire juste "je pense que c\'est bien / c\'est mal" sans developper.' },
                    { question: 'C\'est quoi la laicite dans le debat actuel ?', answer: 'La LAICITE est un sujet de debat BRULANT en France. Rappel : la loi de 1905 separe l\'Eglise et l\'Etat. Debats actuels : les SIGNES RELIGIEUX a l\'ecole (loi de 2004 : pas de voile, kippa, grande croix). Le voile dans l\'ESPACE PUBLIC (interdit pour les fonctionnaires, autorise dans la rue). Les MENUS dans les cantines scolaires. Le financement des LIEUX DE CULTE. Deux visions : LAICITE STRICTE = la religion doit etre totalement invisible dans l\'espace public. LAICITE OUVERTE = l\'Etat est neutre mais les individus sont libres de montrer leur religion. En gros : la laicite est un PRINCIPE partage, mais son application fait debat.' },
                    { question: 'Liberte d\'expression : ou sont les limites ?', answer: 'La LIBERTE D\'EXPRESSION est un droit fondamental (article 11 de la DDHC, 1789). MAIS elle a des LIMITES : l\'INJURE et la DIFFAMATION (insulter ou mentir sur quelqu\'un). L\'INCITATION A LA HAINE (racisme, antisemitisme, homophobie). Le NEGATIONNISME (nier les crimes contre l\'humanite, loi Gayssot 1990). L\'APPEL A LA VIOLENCE. Debat post-Charlie Hebdo (2015) : peut-on tout dessiner, tout caricaturer ? La liberte d\'expression protege-t-elle le droit de CHOQUER ? En gros : on peut dire beaucoup de choses, mais pas TOUT. La liberte s\'arrete ou commence celle des autres.' },
                    { question: 'C\'est quoi le referendum d\'initiative citoyenne (RIC) ?', answer: 'Le RIC = une proposition portee par les Gilets Jaunes (2018-2019). Idee : les CITOYENS pourraient proposer eux-memes des lois ou des referendums, sans passer par les elus. 4 types proposes : RIC LEGISLATIF (proposer une loi), RIC ABROGATOIRE (supprimer une loi), RIC REVOCATOIRE (destituer un elu), RIC CONSTITUANT (modifier la Constitution). POUR : plus de pouvoir au peuple, democratie directe. CONTRE : risque de populisme, manipulation de l\'opinion, decisions trop emotionnelles. En gros : le RIC = donner plus de pouvoir aux citoyens. Un debat entre democratie representative et democratie directe.' },
                    { question: 'C\'est quoi un lanceur d\'alerte ?', answer: 'Un LANCEUR D\'ALERTE = une personne qui revele au public des informations CACHEES sur des activites illegales, dangereuses ou immorales. Exemples : Edward SNOWDEN (2013) revele la surveillance de masse par la NSA (agence de renseignement americaine). Julian ASSANGE (WikiLeaks) publie des documents secrets de l\'armee americaine. En France : la loi SAPIN 2 (2016) protege les lanceurs d\'alerte contre les represailles. Debat : HEROS ou TRAITRE ? Ils violent la loi (secret) mais servent l\'interet general. En gros : un lanceur d\'alerte sacrifie souvent sa carriere et sa liberte pour informer le public. Mots difficiles : "lanceur d\'alerte" = en anglais "whistleblower" (celui qui souffle dans le sifflet).' },
                    { question: 'Le droit de greve et ses limites', answer: 'Le DROIT DE GREVE = un droit constitutionnel en France (preambule de 1946). Les salaries peuvent CESSER le travail pour defendre leurs revendications. C\'est un outil de PRESSION sur l\'employeur ou l\'Etat. MAIS il a des LIMITES : il doit etre COLLECTIF (pas tout seul), il ne doit pas etre ABUSIF (ex : greve avec occupation violente). Certains secteurs ont un SERVICE MINIMUM obligatoire (hopitaux, transports, ecoles). Les fonctionnaires de police et les militaires n\'ont PAS le droit de greve. En gros : faire greve est un droit, mais il faut respecter certaines regles.' },
                    { question: 'C\'est quoi la democratie participative ?', answer: 'La democratie PARTICIPATIVE = associer les citoyens aux decisions ENTRE les elections. Pas seulement voter tous les 5 ans, mais participer TOUT LE TEMPS. Outils : les BUDGETS PARTICIPATIFS (les habitants choisissent comment depenser une partie du budget de la ville. Ex : Paris depuis 2014). Les CONSEILS DE QUARTIER. Les CONSULTATIONS CITOYENNES en ligne. La CONVENTION CITOYENNE pour le climat (2019 : 150 citoyens tires au sort pour proposer des mesures). En gros : la democratie participative = combler le vide entre deux elections.' },
                    { question: 'C\'est quoi l\'education aux medias (EMI) ?', answer: 'L\'EMI (Education aux Medias et a l\'Information) = apprendre a DECRYPTER les medias et a developper son ESPRIT CRITIQUE. Competences : distinguer une INFO d\'une OPINION. Identifier les SOURCES (qui parle ? pourquoi ?). Reperer les FAKE NEWS et la desinformation. Comprendre comment les ALGORITHMES selectionnent ce qu\'on voit sur Internet. Savoir VERIFIER une information (fact-checking). L\'EMI est enseignee a l\'ecole en France (programmes officiels). En gros : dans un monde sature d\'informations, savoir TRIER est une competence essentielle.' },
                    { question: 'C\'est quoi l\'entrepreneuriat social ?', answer: 'L\'ENTREPRENEURIAT SOCIAL = creer une entreprise dont le but principal n\'est PAS le profit, mais la RESOLUTION d\'un probleme social ou environnemental. Exemples : les AMAP (paniers de legumes locaux pour les agriculteurs). Emmaüs (recuperation et revente solidaire, fondee par l\'Abbe Pierre). Les entreprises d\'INSERTION (qui embauchent des personnes eloignees de l\'emploi). Difference avec une association : l\'entreprise sociale a une activite ECONOMIQUE (elle vend) mais son objectif est SOCIAL. En gros : on peut entreprendre pour changer le monde, pas seulement pour gagner de l\'argent. Mots difficiles : "ESS" = Economie Sociale et Solidaire.' }
                ],
                quiz: [
                    { question: 'Les syndicats sont legaux en France depuis :', options: ['1789', '1848', '1884', '1936'], correctIndex: 2, explanation: 'La loi Waldeck-Rousseau de 1884 autorise les syndicats en France. Avant, ils etaient interdits.' },
                    { question: 'La desobeissance civile est d\'abord theorisee par :', options: ['Gandhi', 'Martin Luther King', 'Henry David Thoreau', 'Rosa Parks'], correctIndex: 2, explanation: 'Thoreau ecrit "La Desobeissance civile" en 1849 en refusant de payer l\'impot finançant la guerre contre le Mexique.' },
                    { question: 'La loi Gayssot (1990) interdit :', options: ['La greve', 'Le negationnisme (nier les crimes contre l\'humanite)', 'Les manifestations', 'Le port du voile'], correctIndex: 1, explanation: 'La loi Gayssot punit la negation des crimes contre l\'humanite, notamment la Shoah.' },
                    { question: 'Le RIC (Referendum d\'Initiative Citoyenne) est une revendication des :', options: ['Syndicats', 'Partis politiques', 'Gilets Jaunes', 'Journalistes'], correctIndex: 2, explanation: 'Le RIC est une des revendications phares du mouvement des Gilets Jaunes (2018-2019) : donner plus de pouvoir direct aux citoyens.' },
                    { question: 'Un bon argument pour le debat EMC contient :', options: ['Juste une opinion personnelle', 'Une these, un argument, un exemple et une nuance', 'Des insultes pour convaincre', 'Des slogans faciles'], correctIndex: 1, explanation: 'Un argument structure = these (position) + argument (raison) + exemple (fait precis) + nuance (complexite). C\'est la methode du Bac.' },
                    { question: 'Edward Snowden est connu pour avoir revele :', options: ['Des fraudes bancaires', 'La surveillance de masse par la NSA', 'Des scandales sportifs', 'Des secrets militaires'], correctIndex: 1, explanation: 'En 2013, Snowden revele que la NSA americaine surveillait massivement les communications mondiales. Il est considere comme un lanceur d\'alerte.' },
                    { question: 'Un budget participatif c\'est :', options: ['Le budget de l\'Etat', 'Une part du budget decidee directement par les habitants', 'Le budget d\'un parti politique', 'Le budget de l\'UE'], correctIndex: 1, explanation: 'Les budgets participatifs permettent aux citoyens de choisir comment depenser une partie du budget de leur ville.' },
                    { question: 'L\'EMI (Education aux Medias et a l\'Information) apprend a :', options: ['Devenir journaliste', 'Decrypter les medias et developper l\'esprit critique', 'Utiliser les reseaux sociaux', 'Ecrire des articles'], correctIndex: 1, explanation: 'L\'EMI apprend a verifier les sources, reperer les fake news, distinguer info et opinion. C\'est une competence citoyenne essentielle.' }
                ]
            }
        ]
    });
})();
