// francais.js — Donnees Litterature francaise (3 sections)
(function() {
    if (!window.StudFlow || !window.StudFlow.subjects) return;

    window.StudFlow.subjects.register({
        id: 'francais',
        name: 'Litterature',
        icon: '\uD83D\uDCDA',
        color: 'peach',
        sections: [
            {
                id: 'theatre',
                title: 'Le Theatre',
                icon: '\uD83C\uDFAD',
                content: '<h3>Les grands genres theatraux</h3>'
                    + '<ul>'
                    + '<li><strong>La tragedie</strong> : genre noble mettant en scene des personnages de haut rang confrontes a la fatalite. Elle vise la catharsis, c\'est-a-dire la purgation des passions chez le spectateur (Racine, Corneille).</li>'
                    + '<li><strong>La comedie</strong> : genre visant a faire rire et a corriger les moeurs par le ridicule. "Castigat ridendo mores" — elle corrige les moeurs en riant (Moliere, Marivaux, Beaumarchais).</li>'
                    + '<li><strong>Le drame romantique</strong> : genre apparu au XIXe siecle, melant tragique et comique, refusant les regles classiques. Hugo en definit les principes dans la Preface de Cromwell (1827).</li>'
                    + '<li><strong>Le theatre de l\'absurde</strong> : courant du XXe siecle qui met en scene l\'absence de sens de la condition humaine, a travers un langage desarticule et des situations illogiques (Beckett, Ionesco).</li>'
                    + '</ul>'
                    + '<h3>Les regles du theatre classique</h3>'
                    + '<ul>'
                    + '<li><strong>La regle des trois unites</strong> : unite d\'action (une seule intrigue principale), unite de temps (l\'action se deroule en 24 heures), unite de lieu (un seul decor).</li>'
                    + '<li><strong>La bienseance</strong> : interdiction de montrer sur scene ce qui pourrait choquer (violence, mort). On en fait le recit par un personnage.</li>'
                    + '<li><strong>La vraisemblance</strong> : l\'action representee doit paraitre credible et plausible aux yeux du spectateur.</li>'
                    + '</ul>'
                    + '<h3>Les procedes theatraux essentiels</h3>'
                    + '<ul>'
                    + '<li><strong>Le monologue</strong> : discours d\'un personnage seul en scene, revelant ses pensees intimes au spectateur.</li>'
                    + '<li><strong>La tirade</strong> : longue replique d\'un personnage au sein d\'un dialogue, souvent argumentative ou lyrique.</li>'
                    + '<li><strong>L\'aparte</strong> : replique prononcee a l\'insu des autres personnages mais entendue par le public, creant une complicite.</li>'
                    + '<li><strong>La didascalie</strong> : indication scenique de l\'auteur (decor, gestes, ton) qui n\'est pas prononcee par les acteurs.</li>'
                    + '<li><strong>Le coup de theatre</strong> : retournement de situation inattendu qui bouleverse le cours de l\'intrigue.</li>'
                    + '<li><strong>Le denouement</strong> : resolution finale de l\'intrigue. Heureux dans la comedie, tragique dans la tragedie.</li>'
                    + '<li><strong>Le noeud dramatique</strong> : moment ou les tensions et conflits de l\'intrigue atteignent leur point culminant.</li>'
                    + '<li><strong>La double enonciation</strong> : au theatre, tout dialogue est a la fois adresse a un personnage sur scene et au spectateur dans la salle.</li>'
                    + '</ul>'
                    + '<h3>Les fonctions du theatre</h3>'
                    + '<ul>'
                    + '<li><strong>Divertir</strong> : le theatre procure du plaisir par le spectacle, le rire ou l\'emotion esthetique.</li>'
                    + '<li><strong>Instruire</strong> : le theatre transmet des lecons morales ou philosophiques ("plaire et instruire" selon Horace).</li>'
                    + '<li><strong>Emouvoir</strong> : la tragedie suscite terreur et pitie, provoquant la catharsis (Aristote, Poetique).</li>'
                    + '<li><strong>Critiquer la societe</strong> : le theatre denonce les travers sociaux, les injustices, les abus de pouvoir (Beaumarchais, Le Mariage de Figaro).</li>'
                    + '</ul>'
                    + '<h3>Les grands auteurs et leurs oeuvres</h3>'
                    + '<ul>'
                    + '<li><strong>Moliere</strong> : Tartuffe, Le Misanthrope, L\'Avare, Dom Juan. Maitre de la comedie classique, il peint les travers humains.</li>'
                    + '<li><strong>Racine</strong> : Phedre, Andromaque, Berenice. Tragedie classique, passion destructrice, fatalite.</li>'
                    + '<li><strong>Corneille</strong> : Le Cid, Horace, Cinna. Tragedie du devoir et de l\'honneur, le heros cornelien choisit la gloire.</li>'
                    + '<li><strong>Marivaux</strong> : Le Jeu de l\'amour et du hasard, Les Fausses Confidences. Le "marivaudage" : jeu subtil du langage amoureux.</li>'
                    + '<li><strong>Beaumarchais</strong> : Le Barbier de Seville, Le Mariage de Figaro. Comedie satirique prerevolutionnaire.</li>'
                    + '<li><strong>Hugo</strong> : Hernani, Ruy Blas. Fondateur du drame romantique, rupture avec les regles classiques.</li>'
                    + '<li><strong>Musset</strong> : Lorenzaccio, On ne badine pas avec l\'amour. Theatre romantique, conflit entre ideal et realite.</li>'
                    + '<li><strong>Beckett</strong> : En attendant Godot. Theatre de l\'absurde, attente sans fin, langage vide de sens.</li>'
                    + '<li><strong>Ionesco</strong> : La Cantatrice chauve, Rhinoceros. Deconstruction du langage, denonciation du conformisme.</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Qu\'est-ce que la catharsis selon Aristote ?', answer: 'La catharsis est la purgation des passions chez le spectateur. En eprouvant terreur et pitie devant le spectacle tragique, le spectateur se libere de ses propres emotions negatives. Aristote definit ce concept dans la Poetique.' },
                    { question: 'Quelles sont les trois unites du theatre classique ?', answer: 'Unite d\'action (une seule intrigue principale), unite de temps (l\'action se deroule en 24 heures maximum), unite de lieu (un seul decor). Ces regles visent la vraisemblance et la concentration dramatique.' },
                    { question: 'Qu\'est-ce que la bienseance au theatre classique ?', answer: 'La bienseance interdit de montrer sur scene ce qui pourrait choquer le spectateur : violence, mort, scenes intimes. Ces evenements sont rapportes par un recit (comme la mort d\'Hippolyte dans Phedre de Racine).' },
                    { question: 'Qu\'est-ce que la double enonciation au theatre ?', answer: 'Au theatre, toute parole est simultanement adressee a un personnage sur scene et au spectateur dans la salle. Le public recoit donc un sens supplementaire que les personnages ne percoivent pas toujours.' },
                    { question: 'Qu\'est-ce qu\'un aparte au theatre ?', answer: 'Un aparte est une replique qu\'un personnage prononce a l\'insu des autres personnages presents sur scene, mais que le public entend. Il cree une complicite entre le personnage et le spectateur.' },
                    { question: 'Que sont les didascalies ?', answer: 'Les didascalies sont les indications sceniques ecrites par l\'auteur dans le texte theatral. Elles precisent le decor, les gestes, les deplacements, le ton des personnages. Elles ne sont pas prononcees sur scene.' },
                    { question: 'Qu\'est-ce que le drame romantique ?', answer: 'Genre theatral du XIXe siecle qui melange tragique et comique, refuse les unites classiques et met en scene des heros passionnes. Victor Hugo en definit les principes dans la Preface de Cromwell (1827). Exemples : Hernani, Ruy Blas.' },
                    { question: 'Qu\'est-ce que le theatre de l\'absurde ?', answer: 'Courant theatral du XXe siecle qui represente l\'absurdite de la condition humaine par un langage desarticule, des situations illogiques et une intrigue reduite au minimum. Principaux auteurs : Beckett (En attendant Godot), Ionesco (La Cantatrice chauve).' },
                    { question: 'Quelles sont les principales caracteristiques de la tragedie classique ?', answer: 'La tragedie met en scene des personnages nobles confrontes a un destin funeste. Elle respecte les trois unites, la bienseance et la vraisemblance. Elle vise la catharsis par la terreur et la pitie. Le denouement est toujours malheureux.' },
                    { question: 'Quelle est la difference entre un monologue et une tirade ?', answer: 'Le monologue est un discours prononce par un personnage seul sur scene, revelant ses pensees intimes. La tirade est une longue replique adressee a un ou plusieurs interlocuteurs au sein d\'un dialogue, souvent argumentative ou lyrique.' },
                    { question: 'Qu\'est-ce que le "marivaudage" ?', answer: 'Le marivaudage designe le jeu subtil et raffine du langage amoureux dans les comedies de Marivaux. Les personnages hesitent, se testent et se derobent avant d\'avouer leurs sentiments. C\'est un badinage elegant et psychologiquement fin.' },
                    { question: 'Quels sont les principaux traits du heros cornelien ?', answer: 'Le heros cornelien est un personnage noble qui fait preuve de volonte et de grandeur d\'ame. Confronte a un dilemme entre devoir et passion, il choisit l\'honneur et la gloire. Rodrigue dans Le Cid en est l\'archetype.' },
                    { question: 'Qu\'est-ce qu\'un coup de theatre ?', answer: 'Un coup de theatre est un evenement inattendu qui renverse brusquement le cours de l\'intrigue. Il surprend a la fois les personnages et le spectateur, relancant l\'action dramatique. Il peut etre une revelation, une arrivee imprevue ou un retournement de situation.' },
                    { question: 'En quoi Le Mariage de Figaro est-il une piece subversive ?', answer: 'Beaumarchais y denonce les privileges de la noblesse a travers le personnage de Figaro, valet qui s\'oppose a son maitre le Comte Almaviva. La piece critique l\'injustice sociale et annonce les idees revolutionnaires. Elle fut censuree avant d\'etre jouee en 1784.' },
                    { question: 'Qu\'est-ce que le noeud dramatique ?', answer: 'Le noeud dramatique est le moment central de l\'intrigue ou les tensions et les conflits atteignent leur maximum. Il constitue l\'obstacle principal que le heros doit surmonter avant le denouement. Il concentre l\'interet dramatique de la piece.' },
                    { question: 'Quelle est la structure d\'une piece de theatre classique ?', answer: 'Une piece classique se divise en cinq actes : exposition (presentation de la situation), noeud (complication de l\'intrigue), peripeties (rebondissements), crise (point culminant), denouement (resolution). Chaque acte contient plusieurs scenes.' },
                    { question: 'Quelle est la specificite du theatre de Racine ?', answer: 'Racine excelle dans la tragedie de la passion. Ses personnages sont dechires par des sentiments violents et destructeurs (amour, jalousie). Le style est sobre, musical et d\'une grande purete. Exemples : Phedre, amoureuse de son beau-fils Hippolyte.' },
                    { question: 'Pourquoi dit-on que Moliere "corrige les moeurs par le rire" ?', answer: 'Moliere utilise la comedie pour denoncer les vices et les travers de la societe : l\'hypocrisie (Tartuffe), l\'avarice (L\'Avare), la vanite bourgeoise (Le Bourgeois gentilhomme). En ridiculisant ces defauts, il incite le spectateur a s\'en corriger.' },
                    { question: 'Qu\'est-ce que la vraisemblance au theatre classique ?', answer: 'La vraisemblance exige que l\'action representee paraisse credible aux yeux du spectateur. Ce qui est montre doit etre conforme a l\'opinion commune de ce qui est possible. C\'est un critere esthetique central du classicisme.' },
                    { question: 'Comment Ionesco deconstruit-il le langage dans La Cantatrice chauve ?', answer: 'Ionesco montre l\'absurdite du langage quotidien en le vidant de son sens : les personnages echangent des banalites, des proverbes deformes et des repliques incoherentes. Le langage ne sert plus a communiquer mais revele le neant de la vie bourgeoise.' },
                    { question: 'Quel est le sujet d\'En attendant Godot de Beckett ?', answer: 'Deux personnages, Vladimir et Estragon, attendent un certain Godot qui ne viendra jamais. La piece represente l\'attente absurde comme condition humaine fondamentale. L\'intrigue est presque inexistante, le temps est circulaire et repetitif.' },
                    { question: 'Qu\'est-ce que le denouement dans une piece de theatre ?', answer: 'Le denouement est la partie finale de la piece qui resout l\'intrigue et les conflits. Dans la tragedie, il est malheureux (mort du heros). Dans la comedie, il est heureux (mariage, reconciliation). Il peut intervenir par un coup de theatre ou un deus ex machina.' },
                    { question: 'Quels sont les registres du theatre ?', answer: 'Les principaux registres theatraux sont : le tragique (fatalite, terreur, pitie), le comique (rire, quiproquo, satire), le pathetique (emotion, compassion), le lyrique (expression des sentiments), le polemique (denonciation, critique sociale).' },
                    { question: 'Comment Hugo definit-il le drame romantique dans la Preface de Cromwell ?', answer: 'Hugo prone le melange des genres (grotesque et sublime), le rejet des trois unites classiques, la representation de la totalite de la vie. Il veut un theatre libre, qui peigne la nature et la societe sans les contraintes artificielles du classicisme.' },
                    { question: 'Qu\'est-ce que le quiproquo au theatre ?', answer: 'Le quiproquo est un malentendu entre personnages qui ne parlent pas de la meme chose sans le savoir. C\'est un ressort comique frequent, notamment chez Moliere et Marivaux. Il cree un decalage drole entre ce que le public sait et ce que les personnages comprennent.' },
                    { question: 'Qu\'est-ce que l\'exposition dans une piece de theatre ?', answer: 'L\'exposition est la premiere partie de la piece (generalement l\'acte I) qui fournit au spectateur les informations necessaires a la comprehension de l\'intrigue : personnages, situation initiale, lieu, epoque. Elle doit etre claire, rapide et naturelle.' },
                    { question: 'Quelle est la particularite du theatre de Musset ?', answer: 'Musset ecrit un "theatre dans un fauteuil", concu pour la lecture plus que pour la scene. Ses pieces melent lyrisme et desenchantement, idealisme et cynisme. Lorenzaccio est un drame romantique sur l\'impossibilite d\'agir et la corruption du pouvoir.' },
                    { question: 'Qu\'est-ce qu\'un deus ex machina ?', answer: 'Litteralement "dieu sorti de la machine", c\'est un procede de denouement ou un element exterieur intervient de facon inopinee pour resoudre l\'intrigue. Dans le theatre antique, un dieu descendait sur scene par une machinerie. Ce procede est souvent critique comme artificiel.' },
                    { question: 'En quoi la tragedie racineenne differe-t-elle de la tragedie cornelienne ?', answer: 'Chez Corneille, le heros triomphe par sa volonte et choisit le devoir. Chez Racine, le personnage est victime de passions incontrolables qui le menent a la destruction. La tragedie cornelienne est heroique, la racinienne est psychologique et fataliste.' },
                    { question: 'Qu\'est-ce que Rhinoceros d\'Ionesco denonce ?', answer: 'Rhinoceros est une allegorie du totalitarisme et du conformisme. Les habitants d\'une ville se transforment un a un en rhinoceros, symbole de la pensee de masse. Seul Berenger resiste, incarnant la defense de l\'humanite et de la liberte individuelle.' }
                ],
                quiz: [
                    { question: 'Quelle figure de style theatrale designe une replique entendue du public mais pas des autres personnages ?', options: ['L\'aparte', 'Le monologue', 'La tirade', 'La stichomythie'], correctIndex: 0, explanation: 'L\'aparte est une convention theatrale ou un personnage s\'adresse au public a l\'insu des autres personnages sur scene.' },
                    { question: 'Qui a ecrit la Preface de Cromwell, manifeste du drame romantique ?', options: ['Musset', 'Stendhal', 'Hugo', 'Vigny'], correctIndex: 2, explanation: 'Victor Hugo publie la Preface de Cromwell en 1827, ou il theorise le drame romantique et le melange des genres.' },
                    { question: 'La catharsis est un concept defini par :', options: ['Aristote', 'Platon', 'Sophocle', 'Horace'], correctIndex: 0, explanation: 'Aristote definit la catharsis dans la Poetique comme la purgation des passions (terreur et pitie) par le spectacle tragique.' },
                    { question: 'Quelle piece de Moliere denonce l\'hypocrisie religieuse ?', options: ['L\'Avare', 'Le Misanthrope', 'Tartuffe', 'Les Femmes savantes'], correctIndex: 2, explanation: 'Tartuffe (1664) met en scene un faux devot qui abuse de la credulite d\'Orgon. La piece fut censuree a sa creation.' },
                    { question: 'Quel dramaturge est associe au "marivaudage" ?', options: ['Marivaux', 'Beaumarchais', 'Moliere', 'Corneille'], correctIndex: 0, explanation: 'Le "marivaudage" designe le jeu subtil du langage amoureux dans les comedies de Marivaux, comme Le Jeu de l\'amour et du hasard.' },
                    { question: 'Quelle est la regle de bienseance au theatre classique ?', options: ['L\'action doit durer 24 heures', 'On ne montre pas la violence sur scene', 'Il faut un seul lieu', 'Les personnages doivent etre nobles'], correctIndex: 1, explanation: 'La bienseance interdit de representer sur scene ce qui pourrait choquer : mort, violence, scenes inconvenantes.' },
                    { question: 'En attendant Godot est une oeuvre de :', options: ['Ionesco', 'Sartre', 'Beckett', 'Camus'], correctIndex: 2, explanation: 'Samuel Beckett ecrit En attendant Godot (1952), piece emblematique du theatre de l\'absurde ou deux personnages attendent indefiniment.' },
                    { question: 'Quelle piece de Racine met en scene l\'amour interdit de Phedre pour Hippolyte ?', options: ['Phedre', 'Berenice', 'Andromaque', 'Britannicus'], correctIndex: 0, explanation: 'Dans Phedre (1677), l\'heroine eprouve une passion coupable pour son beau-fils Hippolyte, passion qui la mene a la mort.' },
                    { question: 'Qu\'est-ce que la double enonciation au theatre ?', options: ['Un dialogue entre deux personnages', 'Une replique adressee a la fois aux personnages et au public', 'Un monologue suivi d\'un dialogue', 'Une didascalie lue a voix haute'], correctIndex: 1, explanation: 'La double enonciation est le fait que toute parole theatrale est simultanement destinee aux personnages sur scene et au spectateur.' },
                    { question: 'Dans Le Cid de Corneille, quel est le dilemme de Rodrigue ?', options: ['Honneur familial ou amour', 'Amour ou ambition', 'Foi ou raison', 'Pouvoir ou justice'], correctIndex: 0, explanation: 'Rodrigue doit choisir entre venger l\'honneur de son pere (en tuant le pere de Chimene) et son amour pour Chimene. C\'est le dilemme cornelien par excellence.' },
                    { question: 'Quel auteur a ecrit Rhinoceros ?', options: ['Beckett', 'Sartre', 'Genet', 'Ionesco'], correctIndex: 3, explanation: 'Eugene Ionesco ecrit Rhinoceros (1959), une allegorie du conformisme et du totalitarisme ou les humains se transforment en rhinoceros.' },
                    { question: 'Quelle piece de Beaumarchais annonce la Revolution francaise ?', options: ['Le Barbier de Seville', 'Le Mariage de Figaro', 'La Mere coupable', 'L\'Autre Tartuffe'], correctIndex: 1, explanation: 'Le Mariage de Figaro (1784) critique les privileges de la noblesse a travers le conflit entre Figaro et le Comte Almaviva.' },
                    { question: 'Qu\'est-ce qu\'une stichomythie ?', options: ['Un monologue tragique', 'Un recit fait par un messager', 'Une indication scenique', 'Un echange de repliques courtes et rapides'], correctIndex: 3, explanation: 'La stichomythie est un echange de repliques tres courtes (souvent vers par vers) qui traduit un conflit, une tension ou un debat vif entre deux personnages.' },
                    { question: 'Comment s\'appelle l\'acte I d\'une piece classique ?', options: ['Le noeud', 'Le denouement', 'L\'exposition', 'La peripetie'], correctIndex: 2, explanation: 'L\'exposition (acte I) presente les personnages, la situation initiale et les enjeux de l\'intrigue au spectateur.' },
                    { question: 'Quel registre theatral cherche a provoquer terreur et pitie ?', options: ['Le comique', 'Le tragique', 'Le lyrique', 'Le satirique'], correctIndex: 1, explanation: 'Le registre tragique, defini par Aristote, vise a provoquer terreur et pitie chez le spectateur afin d\'obtenir la catharsis.' },
                    { question: 'Lorenzaccio est une piece de :', options: ['Hugo', 'Dumas', 'Vigny', 'Musset'], correctIndex: 3, explanation: 'Alfred de Musset ecrit Lorenzaccio (1834), drame romantique sur l\'assassinat du duc Alexandre de Medicis par son cousin Lorenzo.' },
                    { question: 'Qu\'est-ce qu\'un deus ex machina ?', options: ['Un personnage divin', 'Un coup de theatre', 'Une intervention exterieure qui resout l\'intrigue', 'Un decor mecanique'], correctIndex: 2, explanation: 'Le deus ex machina est un procede ou un element exterieur (dieu, personnage inattendu) intervient pour denouer l\'intrigue de facon souvent jugee artificielle.' },
                    { question: 'La Cantatrice chauve d\'Ionesco est qualifiee d\'"anti-piece" car :', options: ['Elle n\'a pas de personnages', 'Elle dure plus de cinq heures', 'Elle est ecrite en vers', 'Elle deconstruit les conventions theatrales'], correctIndex: 3, explanation: 'Ionesco qualifie La Cantatrice chauve d\'"anti-piece" car elle detruit les conventions : pas d\'intrigue, dialogues absurdes, fin qui recommence au debut.' },
                    { question: 'Dans la tragedie classique, le denouement est generalement :', options: ['Heureux', 'Malheureux', 'Ouvert', 'Comique'], correctIndex: 1, explanation: 'Le denouement de la tragedie est malheureux : il aboutit a la mort ou a la ruine du heros, consequence de la fatalite ou de ses passions.' },
                    { question: 'Quel personnage de Moliere est devenu synonyme d\'avarice ?', options: ['Tartuffe', 'Alceste', 'Sganarelle', 'Harpagon'], correctIndex: 3, explanation: 'Harpagon, personnage principal de L\'Avare (1668), est devenu un archetype de l\'avarice. Sa celebre replique "Ma cassette !" illustre son obsession pour l\'argent.' },
                    { question: 'Combien de syllabes comporte un alexandrin ?', options: ['8', '10', '12', '14'], correctIndex: 2, explanation: 'L\'alexandrin est un vers de 12 syllabes, coupe a l\'hemistiche (6/6). C\'est le vers noble de la tragedie classique, utilise par Racine et Corneille. Son nom vient du Roman d\'Alexandre (XIIe siecle).' },
                    { question: 'Quelle regle du theatre classique impose que l\'action se deroule en un seul jour ?', options: ['L\'unite d\'action', 'L\'unite de lieu', 'L\'unite de temps', 'La bienseance'], correctIndex: 2, explanation: 'L\'unite de temps exige que l\'action de la piece ne depasse pas 24 heures. Avec l\'unite d\'action et l\'unite de lieu, elle forme les trois unites du theatre classique, codifiees par Boileau dans l\'Art poetique (1674).' },
                    { question: 'Dans quelle comedie Moliere met-il en scene un bourgeois ridicule qui veut imiter la noblesse ?', options: ['Les Fourberies de Scapin', 'Le Bourgeois gentilhomme', 'Le Malade imaginaire', 'Les Precieuses ridicules'], correctIndex: 1, explanation: 'Le Bourgeois gentilhomme (1670) est une comedie-ballet ou Monsieur Jourdain, riche bourgeois, tente d\'imiter les manieres de la noblesse. Il decouvre avec stupeur qu\'il "fait de la prose sans le savoir".' },
                    { question: 'Quel registre comique repose sur des jeux de mots et des quiproquos verbaux ?', options: ['Le comique de geste', 'Le comique de situation', 'Le comique de caractere', 'Le comique de mots'], correctIndex: 3, explanation: 'Le comique de mots exploite les jeux sur le langage : calembours, quiproquos, repetitions, neologismes, deformations. Moliere l\'utilise abondamment dans ses farces et comedies.' }
                ]
            },
            {
                id: 'roman',
                title: 'Le Roman',
                icon: '\uD83D\uDCD6',
                content: '<h3>Les genres romanesques</h3>'
                    + '<ul>'
                    + '<li><strong>Le roman realiste</strong> : represente la societe de facon fidele et objective. Les personnages sont ancres dans un milieu social precis (Balzac, Flaubert, Stendhal).</li>'
                    + '<li><strong>Le roman naturaliste</strong> : prolonge le realisme en s\'appuyant sur les sciences (heredite, milieu social). Zola applique une methode experimentale au roman.</li>'
                    + '<li><strong>Le roman epistolaire</strong> : raconte l\'histoire par un echange de lettres entre personnages (Laclos, Les Liaisons dangereuses ; Montesquieu, Lettres persanes).</li>'
                    + '<li><strong>Le roman autobiographique</strong> : recit ou l\'auteur raconte sa propre vie, avec un pacte de verite entre auteur et lecteur (Rousseau, Les Confessions).</li>'
                    + '<li><strong>Le nouveau roman</strong> : mouvement des annees 1950-60 qui rejette les codes traditionnels du roman : intrigue, personnage, chronologie (Robbe-Grillet, Sarraute, Duras, Perec).</li>'
                    + '<li><strong>Le roman picaresque</strong> : recit d\'aventures d\'un heros de basse condition traversant differents milieux sociaux (Lesage, Gil Blas).</li>'
                    + '</ul>'
                    + '<h3>Les techniques narratives</h3>'
                    + '<ul>'
                    + '<li><strong>Le narrateur</strong> : celui qui raconte l\'histoire. Il peut etre un personnage (narrateur interne, "je") ou exterieur a l\'histoire (narrateur externe).</li>'
                    + '<li><strong>Le narrateur omniscient</strong> : il sait tout des personnages (pensees, passe, avenir). Frequemment utilise par Balzac et Zola.</li>'
                    + '<li><strong>La focalisation interne</strong> : le lecteur percoit les evenements a travers les yeux et les pensees d\'un personnage.</li>'
                    + '<li><strong>La focalisation externe</strong> : le lecteur observe les personnages de l\'exterieur, sans acceder a leurs pensees.</li>'
                    + '<li><strong>La focalisation zero</strong> : point de vue omniscient, le narrateur connait tout de tous les personnages.</li>'
                    + '</ul>'
                    + '<h3>Les elements du recit romanesque</h3>'
                    + '<ul>'
                    + '<li><strong>L\'incipit</strong> : debut du roman. Il doit capter l\'attention du lecteur et fournir les premieres informations (lieu, epoque, personnages).</li>'
                    + '<li><strong>L\'explicit</strong> : derniere page du roman. Il peut etre ferme (tout est resolu) ou ouvert (fin ambigue).</li>'
                    + '<li><strong>La description</strong> : passage qui depeint un lieu, un objet ou une atmosphere. Chez Balzac, elle revele le milieu social et le caractere des personnages.</li>'
                    + '<li><strong>Le portrait</strong> : description physique et morale d\'un personnage, qui eclaire sa psychologie et son role dans l\'intrigue.</li>'
                    + '</ul>'
                    + '<h3>Les discours rapportes</h3>'
                    + '<ul>'
                    + '<li><strong>Le discours direct</strong> : les paroles sont reproduites telles quelles, entre guillemets. "Je viendrai demain", dit-il.</li>'
                    + '<li><strong>Le discours indirect</strong> : les paroles sont integrees au recit par une proposition subordonnee. Il dit qu\'il viendrait le lendemain.</li>'
                    + '<li><strong>Le discours indirect libre</strong> : les paroles ou pensees sont rapportees sans verbe introducteur ni guillemets, melant voix du narrateur et du personnage. Flaubert en fait un usage magistral.</li>'
                    + '</ul>'
                    + '<h3>Les temps du recit</h3>'
                    + '<ul>'
                    + '<li><strong>L\'analepse</strong> (retour en arriere) : le recit revient sur des evenements anterieurs.</li>'
                    + '<li><strong>La prolepse</strong> (anticipation) : le recit evoque des evenements futurs.</li>'
                    + '<li><strong>L\'ellipse</strong> : le recit passe sous silence une periode de temps.</li>'
                    + '<li><strong>La scene</strong> : le temps du recit correspond au temps de l\'histoire (dialogues).</li>'
                    + '<li><strong>Le sommaire</strong> : le recit resume rapidement une longue periode.</li>'
                    + '</ul>'
                    + '<h3>Evolution du genre romanesque</h3>'
                    + '<ul>'
                    + '<li><strong>XVIIe siecle</strong> : naissance du roman moderne avec La Princesse de Cleves (Mme de Lafayette), premier roman d\'analyse psychologique.</li>'
                    + '<li><strong>XVIIIe siecle</strong> : essor du roman epistolaire et du roman philosophique (Voltaire, Montesquieu, Rousseau).</li>'
                    + '<li><strong>XIXe siecle</strong> : age d\'or du roman avec le realisme (Balzac, Stendhal, Flaubert) et le naturalisme (Zola). Le roman devient le miroir de la societe.</li>'
                    + '<li><strong>XXe siecle</strong> : eclatement des formes avec Proust (monologue interieur), Camus (roman philosophique), le Nouveau Roman (deconstruction des codes narratifs).</li>'
                    + '</ul>'
                    + '<h3>Les grands auteurs et leurs oeuvres</h3>'
                    + '<ul>'
                    + '<li><strong>Mme de Lafayette</strong> : La Princesse de Cleves (1678). Premier roman d\'analyse psychologique, conflit entre passion et devoir moral.</li>'
                    + '<li><strong>Balzac</strong> : La Comedie humaine. Fresque sociale monumentale depeignant toutes les classes de la societe francaise (Le Pere Goriot, Illusions perdues).</li>'
                    + '<li><strong>Stendhal</strong> : Le Rouge et le Noir, La Chartreuse de Parme. Roman d\'apprentissage, ambition sociale, psychologie des personnages.</li>'
                    + '<li><strong>Flaubert</strong> : Madame Bovary, L\'Education sentimentale. Style impersonnel, discours indirect libre, critique de la mediocrite bourgeoise.</li>'
                    + '<li><strong>Zola</strong> : Les Rougon-Macquart (20 romans). Roman experimental, determinisme (heredite et milieu). Germinal, L\'Assommoir, Nana.</li>'
                    + '<li><strong>Proust</strong> : A la recherche du temps perdu. Exploration de la memoire, du temps et de la subjectivite. La madeleine comme declencheur de la memoire involontaire.</li>'
                    + '<li><strong>Camus</strong> : L\'Etranger, La Peste. Roman philosophique, sentiment de l\'absurde, revolte contre l\'injustice.</li>'
                    + '<li><strong>Duras</strong> : L\'Amant, Moderato cantabile. Ecriture minimaliste, fragments, silence entre les mots.</li>'
                    + '<li><strong>Perec</strong> : La Vie mode d\'emploi, La Disparition. Jeux formels, contraintes oulipiennes, inventivite structurelle.</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Qu\'est-ce que l\'incipit d\'un roman ?', answer: 'L\'incipit est le debut du roman, ses premieres lignes ou premieres pages. Il doit capter l\'attention du lecteur, presenter le cadre (lieu, epoque) et eventuellement le personnage principal. C\'est un moment strategique du recit.' },
                    { question: 'Quels sont les trois types de focalisation ?', answer: 'Focalisation interne : le lecteur voit a travers les yeux d\'un personnage. Focalisation externe : le lecteur observe de l\'exterieur sans acceder aux pensees. Focalisation zero (omnisciente) : le narrateur sait tout de tous les personnages.' },
                    { question: 'Qu\'est-ce que le discours indirect libre ?', answer: 'Le discours indirect libre rapporte les paroles ou pensees d\'un personnage sans guillemets ni verbe introducteur, fondant la voix du narrateur et celle du personnage. Flaubert en fait un usage celebre dans Madame Bovary.' },
                    { question: 'Qu\'est-ce que le roman naturaliste ?', answer: 'Le roman naturaliste, theorise par Zola dans Le Roman experimental, prolonge le realisme en appliquant la methode scientifique au roman. Il etudie l\'influence de l\'heredite et du milieu social sur les individus. Les Rougon-Macquart en sont l\'exemple majeur.' },
                    { question: 'Quelle est l\'importance de La Princesse de Cleves ?', answer: 'Ecrit par Mme de Lafayette en 1678, c\'est considere comme le premier roman d\'analyse psychologique francais. Il explore le conflit entre passion amoureuse et devoir moral, posant les bases du roman moderne centre sur l\'interiorite des personnages.' },
                    { question: 'Qu\'est-ce qu\'une analepse et une prolepse ?', answer: 'L\'analepse est un retour en arriere dans le recit (flashback). La prolepse est une anticipation d\'evenements futurs (flash-forward). Ces deux procedes permettent au romancier de jouer avec la temporalite du recit.' },
                    { question: 'Qu\'est-ce que le Nouveau Roman ?', answer: 'Mouvement litteraire des annees 1950-60 qui rejette les conventions du roman traditionnel : intrigue lineaire, personnage psychologiquement coherent, narrateur omniscient. Auteurs principaux : Robbe-Grillet, Sarraute, Duras, Butor, Perec.' },
                    { question: 'En quoi Balzac est-il un auteur majeur du realisme ?', answer: 'Balzac a cree La Comedie humaine, une fresque de plus de 90 romans depeignant toutes les couches de la societe francaise. Il utilise le retour des personnages d\'un roman a l\'autre et des descriptions minutieuses revelant le milieu social.' },
                    { question: 'Quel est le projet des Rougon-Macquart de Zola ?', answer: 'Cycle de 20 romans racontant l\'histoire naturelle et sociale d\'une famille sous le Second Empire. Zola y etudie l\'influence de l\'heredite (la "felure" familiale) et du milieu social sur les destins individuels, avec une methode se voulant scientifique.' },
                    { question: 'Qu\'est-ce que la memoire involontaire chez Proust ?', answer: 'C\'est le surgissement imprevu d\'un souvenir declenche par une sensation (gout, odeur, son). L\'episode de la madeleine dans Du cote de chez Swann en est l\'exemple le plus celebre : le gout d\'un gateau trempe dans du the fait ressurgir tout un monde enfoui.' },
                    { question: 'Qu\'est-ce qu\'un roman epistolaire ?', answer: 'Un roman compose de lettres echangees entre les personnages. Ce genre permet de multiplier les points de vue et de creer des effets dramatiques. Exemples celebres : Les Liaisons dangereuses de Laclos, Les Lettres persanes de Montesquieu.' },
                    { question: 'Qu\'est-ce que L\'Etranger de Camus illustre ?', answer: 'L\'Etranger (1942) illustre la philosophie de l\'absurde. Meursault, le narrateur, est etranger au monde et a ses propres emotions. Le recit, ecrit au passe compose, traduit un detachement existentiel face a la societe et ses conventions.' },
                    { question: 'Qu\'est-ce que le roman d\'apprentissage ?', answer: 'Genre romanesque retracant l\'evolution d\'un jeune heros qui decouvre le monde, fait des experiences et murit. Le Rouge et le Noir de Stendhal (Julien Sorel) et Illusions perdues de Balzac (Lucien de Rubempre) en sont des exemples classiques.' },
                    { question: 'Qu\'est-ce que le realisme en litterature ?', answer: 'Courant du XIXe siecle visant a representer la realite de facon fidele et objective, sans idealisation. Il s\'interesse a tous les milieux sociaux, utilise des descriptions precises et un style impersonnel. Principaux auteurs : Balzac, Flaubert, Stendhal.' },
                    { question: 'Qu\'est-ce que l\'explicit d\'un roman ?', answer: 'L\'explicit est la fin du roman, ses dernieres lignes ou dernieres pages. Il peut etre ferme (denouement clair, resolution de l\'intrigue) ou ouvert (fin ambigue laissant le lecteur interpreter). C\'est un moment strategique symetrique de l\'incipit.' },
                    { question: 'Quelle est la particularite du style de Flaubert ?', answer: 'Flaubert recherche le "mot juste" et un style impersonnel ou l\'auteur s\'efface. Il maitrise le discours indirect libre et travaille la prose avec une exigence musicale. Madame Bovary illustre son art de la distance ironique.' },
                    { question: 'Qu\'est-ce qu\'une ellipse narrative ?', answer: 'L\'ellipse est un procede narratif qui passe sous silence une periode de temps dans le recit. Le narrateur saute des jours, des mois ou des annees sans les raconter. Cela permet d\'accelerer le rythme et de se concentrer sur les moments essentiels.' },
                    { question: 'Qu\'est-ce que le roman picaresque ?', answer: 'Genre narratif d\'origine espagnole mettant en scene un heros de basse condition (le "picaro") qui traverse differents milieux sociaux au fil de ses aventures. C\'est un regard satirique sur la societe. Exemple francais : Gil Blas de Lesage.' },
                    { question: 'Comment le personnage de roman a-t-il evolue du XVIIe au XXe siecle ?', answer: 'Du heros idealise (XVIIe) au personnage psychologiquement complexe (XVIIIe-XIXe), puis au anti-heros desenchante (XXe). Meursault (Camus) est indifferent au monde, les personnages du Nouveau Roman perdent meme leur identite et leur coherence psychologique.' },
                    { question: 'Qu\'est-ce que Madame Bovary de Flaubert raconte ?', answer: 'L\'histoire d\'Emma Bovary, femme d\'un medecin de campagne qui reve d\'une vie romanesque et passionnee. Decue par la mediocrite de son existence, elle s\'engage dans des aventures amoureuses et des depenses ruineuses qui la menent au suicide.' },
                    { question: 'Qu\'est-ce que La Comedie humaine de Balzac ?', answer: 'Un ensemble de plus de 90 romans et nouvelles qui forme une fresque complete de la societe francaise sous la Restauration et la monarchie de Juillet. Balzac y utilise le retour des personnages et classe ses oeuvres en etudes de moeurs, philosophiques et analytiques.' },
                    { question: 'Quel est le role de la description dans le roman realiste ?', answer: 'La description n\'est pas un simple ornement : elle revele le milieu social des personnages, exprime leur psychologie et cree une atmosphere. Chez Balzac, decrire la pension Vauquer c\'est expliquer le caractere de ses habitants.' },
                    { question: 'Quelle est la difference entre scene et sommaire dans le recit ?', answer: 'La scene reproduit les evenements en temps reel (dialogue, action detaillee) : le temps du recit egale le temps de l\'histoire. Le sommaire resume rapidement une longue periode en quelques lignes. Ces deux vitesses rythment le recit.' },
                    { question: 'Qu\'est-ce que le pacte autobiographique selon Lejeune ?', answer: 'Philippe Lejeune definit le pacte autobiographique comme l\'engagement de l\'auteur que l\'auteur, le narrateur et le personnage sont une seule et meme personne. C\'est un contrat de verite entre l\'auteur et le lecteur, propre au genre autobiographique.' },
                    { question: 'Qu\'est-ce que La Disparition de Perec ?', answer: 'Roman lipogrammatique ecrit en 1969, entierement redige sans la lettre "e". C\'est une prouesse oulipienne qui transforme la contrainte formelle en moteur de creation. Le livre raconte une disparition, metaphore de l\'absence meme de la lettre.' },
                    { question: 'En quoi L\'Education sentimentale de Flaubert est-elle un roman desenchante ?', answer: 'Frederic Moreau, jeune homme ambitieux, traverse la societe parisienne sans jamais realiser ses reves amoureux ni sociaux. Le roman decrit l\'echec des ideaux face a la mediocrite du reel, sur fond de revolution de 1848.' },
                    { question: 'Qu\'est-ce que le narrateur omniscient ?', answer: 'Un narrateur qui sait tout : les pensees de tous les personnages, leur passe, leur avenir, ce qui se passe en plusieurs lieux simultanement. Il est exterieur a l\'histoire et la domine entierement. Balzac et Zola l\'utilisent frequemment.' },
                    { question: 'Qu\'est-ce que Germinal de Zola raconte ?', answer: 'L\'histoire d\'Etienne Lantier, un mineur qui organise une greve dans le Nord de la France sous le Second Empire. Le roman decrit les conditions de vie miserables des mineurs et constitue un tableau puissant de la lutte des classes.' },
                    { question: 'Quelle est la contribution de Duras au roman contemporain ?', answer: 'Marguerite Duras developpe une ecriture minimaliste, fragmentee, ou le silence et le non-dit sont aussi importants que les mots. L\'Amant (1984) mele autobiographie et fiction dans un style depouille et poetique. Elle influence le Nouveau Roman.' },
                    { question: 'Qu\'est-ce que le "bovarysme" ?', answer: 'Terme derive du personnage d\'Emma Bovary (Flaubert), designant le pouvoir de se concevoir autrement qu\'on est. C\'est l\'insatisfaction chronique nee du decalage entre les reves romanesques et la realite mediocre de l\'existence quotidienne.' }
                ],
                quiz: [
                    { question: 'Quel roman est considere comme le premier roman d\'analyse psychologique francais ?', options: ['La Princesse de Cleves', 'Manon Lescaut', 'Les Liaisons dangereuses', 'Paul et Virginie'], correctIndex: 0, explanation: 'La Princesse de Cleves de Mme de Lafayette (1678) est considere comme le premier roman d\'analyse psychologique, explorant le conflit interieur entre passion et devoir.' },
                    { question: 'Quel auteur a theorise le "roman experimental" ?', options: ['Balzac', 'Flaubert', 'Zola', 'Stendhal'], correctIndex: 2, explanation: 'Emile Zola theorise le roman experimental en 1880, appliquant la methode scientifique au roman pour etudier l\'influence de l\'heredite et du milieu.' },
                    { question: 'Qu\'est-ce que le discours indirect libre ?', options: ['Des paroles entre guillemets', 'Des paroles avec verbe introducteur', 'Des pensees rapportees sans marque typographique ni verbe introducteur', 'Un dialogue theatral'], correctIndex: 2, explanation: 'Le discours indirect libre mele la voix du narrateur et celle du personnage sans guillemets ni verbe introducteur. Flaubert en est le maitre.' },
                    { question: 'La focalisation interne signifie que :', options: ['Le narrateur sait tout', 'Le lecteur voit a travers les yeux d\'un personnage', 'Le lecteur observe de l\'exterieur', 'L\'auteur intervient dans le recit'], correctIndex: 1, explanation: 'En focalisation interne, le lecteur ne percoit que ce que voit, pense et ressent un personnage particulier.' },
                    { question: 'Quel est l\'episode le plus celebre d\'A la recherche du temps perdu ?', options: ['La madeleine', 'Le bal de la duchesse', 'La mort de Swann', 'Le voyage a Venise'], correctIndex: 0, explanation: 'L\'episode de la madeleine trempee dans du the est emblematique de la memoire involontaire chez Proust : une sensation fait resurgir tout un monde de souvenirs enfouis.' },
                    { question: 'Quel courant litteraire rejette l\'intrigue et le personnage traditionnel ?', options: ['Le realisme', 'Le naturalisme', 'Le romantisme', 'Le Nouveau Roman'], correctIndex: 3, explanation: 'Le Nouveau Roman (annees 1950-60) rejette les conventions narratives traditionnelles : intrigue lineaire, personnage coherent, narrateur omniscient.' },
                    { question: 'Qu\'est-ce qu\'une analepse ?', options: ['Un retour en arriere', 'Une anticipation', 'Une acceleration du recit', 'Un passage descriptif'], correctIndex: 0, explanation: 'L\'analepse (ou flashback) est un retour en arriere dans le recit : le narrateur revient sur des evenements anterieurs au moment present de l\'histoire.' },
                    { question: 'Quel est le titre du cycle romanesque de Zola ?', options: ['La Comedie humaine', 'Les Rougon-Macquart', 'Les Thibault', 'Les Hommes de bonne volonte'], correctIndex: 1, explanation: 'Les Rougon-Macquart est un cycle de 20 romans racontant "l\'histoire naturelle et sociale d\'une famille sous le Second Empire".' },
                    { question: 'Qui a ecrit L\'Etranger ?', options: ['Sartre', 'Gide', 'Malraux', 'Camus'], correctIndex: 3, explanation: 'Albert Camus publie L\'Etranger en 1942. Meursault, le narrateur, incarne l\'homme absurde, etranger au monde et a ses propres sentiments.' },
                    { question: 'Qu\'est-ce que le "bovarysme" ?', options: ['Le pouvoir de se concevoir autrement qu\'on est', 'L\'amour du luxe', 'La passion pour la lecture', 'Le desir d\'aventure'], correctIndex: 0, explanation: 'Le bovarysme, derive d\'Emma Bovary (Flaubert), designe l\'insatisfaction chronique nee du decalage entre les reves romanesques et la mediocrite du reel.' },
                    { question: 'Quel roman de Balzac depeint le sacrifice d\'un pere pour ses filles ?', options: ['Illusions perdues', 'Le Lys dans la vallee', 'Eugenie Grandet', 'Le Pere Goriot'], correctIndex: 3, explanation: 'Le Pere Goriot (1835) raconte l\'histoire d\'un ancien vermicellier qui se ruine pour ses deux filles ingrates, dans la pension Vauquer.' },
                    { question: 'Quel procede narratif passe sous silence une periode de temps ?', options: ['La scene', 'Le sommaire', 'L\'ellipse', 'La pause descriptive'], correctIndex: 2, explanation: 'L\'ellipse est un saut dans le temps : le narrateur omet une periode sans la raconter, accelerant ainsi le rythme du recit.' },
                    { question: 'Les Liaisons dangereuses est un roman :', options: ['Picaresque', 'Epistolaire', 'Autobiographique', 'Naturaliste'], correctIndex: 1, explanation: 'Les Liaisons dangereuses de Choderlos de Laclos (1782) est un roman epistolaire compose de lettres echangees entre les personnages, revelant leurs manipulations.' },
                    { question: 'Quel romancier est celebre pour sa recherche du "mot juste" ?', options: ['Balzac', 'Zola', 'Flaubert', 'Hugo'], correctIndex: 2, explanation: 'Gustave Flaubert est obsede par le travail du style et la recherche du mot juste. Il reecrivait inlassablement ses phrases (ses manuscrits temoignent de ce labeur).' },
                    { question: 'Quel roman de Stendhal suit l\'ascension de Julien Sorel ?', options: ['La Chartreuse de Parme', 'Armance', 'Lucien Leuwen', 'Le Rouge et le Noir'], correctIndex: 3, explanation: 'Le Rouge et le Noir (1830) raconte l\'ascension et la chute de Julien Sorel, fils de charpentier ambitieux, dans la societe de la Restauration.' },
                    { question: 'Qu\'est-ce que le pacte autobiographique selon Lejeune ?', options: ['Un contrat entre editeur et auteur', 'Un accord entre auteur et lecteur que le recit est veridique', 'Une promesse de fiction', 'Un serment juridique'], correctIndex: 1, explanation: 'Philippe Lejeune definit le pacte autobiographique comme l\'engagement que l\'auteur, le narrateur et le personnage sont une meme personne, garantissant la sincerite du recit.' },
                    { question: 'La Disparition de Georges Perec est un lipogramme car :', options: ['Il est ecrit sans la lettre e', 'Il n\'a pas de chapitres', 'Il est ecrit en vers', 'Il n\'a pas de personnages'], correctIndex: 0, explanation: 'La Disparition (1969) est un roman entier ecrit sans utiliser la lettre "e", la plus frequente en francais. C\'est une contrainte oulipienne.' },
                    { question: 'Quel narrateur connait les pensees de tous les personnages ?', options: ['Le narrateur interne', 'Le narrateur externe', 'Le narrateur omniscient', 'Le narrateur temoin'], correctIndex: 2, explanation: 'Le narrateur omniscient (focalisation zero) sait tout : pensees, passe, avenir de tous les personnages. C\'est le point de vue le plus courant dans le roman realiste du XIXe siecle.' },
                    { question: 'Quel auteur est associe au monologue interieur ?', options: ['Balzac', 'Proust', 'Zola', 'Maupassant'], correctIndex: 1, explanation: 'Marcel Proust, dans A la recherche du temps perdu, developpe le monologue interieur, flux de conscience qui explore les meandres de la pensee et de la memoire.' },
                    { question: 'Quel roman de Camus est une allegorie de l\'occupation nazie ?', options: ['L\'Etranger', 'Le Premier Homme', 'La Chute', 'La Peste'], correctIndex: 3, explanation: 'La Peste (1947) raconte une epidemie a Oran mais est lue comme une allegorie de l\'occupation nazie et de la resistance. Elle pose la question de la solidarite face au mal.' },
                    { question: 'Quelle figure de style consiste a reunir deux termes contradictoires ?', options: ['La metaphore', 'L\'hyperbole', 'L\'oxymore', 'La litote'], correctIndex: 2, explanation: 'L\'oxymore associe deux mots de sens opposes dans une meme expression : "cette obscure clarte" (Corneille), "un silence assourdissant". Il cree un effet de surprise et met en lumiere une tension ou un paradoxe.' },
                    { question: 'Quel mouvement litteraire du XIXe siecle exalte les sentiments, la nature et la liberte individuelle ?', options: ['Le classicisme', 'Le realisme', 'Le romantisme', 'Le naturalisme'], correctIndex: 2, explanation: 'Le romantisme (1820-1850) valorise l\'expression des sentiments personnels, la communion avec la nature, la liberte de l\'artiste et le refus des regles classiques. Hugo, Lamartine, Musset et Chateaubriand en sont les figures majeures.' },
                    { question: 'Quelle forme poetique fixe comporte 14 vers repartis en deux quatrains et deux tercets ?', options: ['La ballade', 'L\'ode', 'Le rondeau', 'Le sonnet'], correctIndex: 3, explanation: 'Le sonnet est une forme fixe de 14 vers, compose de deux quatrains (4 vers) et deux tercets (3 vers). Introduit en France par la Pleiade (Ronsard, Du Bellay), il est repris par Baudelaire et les symbolistes.' },
                    { question: 'Quel recueil de Baudelaire explore la tension entre ideal et spleen ?', options: ['Les Contemplations', 'Alcools', 'Les Fleurs du mal', 'Les Illuminations'], correctIndex: 2, explanation: 'Les Fleurs du mal (1857) de Charles Baudelaire est structure autour de la dualite entre le Spleen (l\'ennui, l\'angoisse existentielle) et l\'Ideal (la beaute, l\'elevation). Ce recueil fonde la modernite poetique et annonce le symbolisme.' }
                ]
            },
            {
                id: 'argumentation',
                title: 'L\'Argumentation',
                icon: '\uD83D\uDDE3\uFE0F',
                content: '<h3>Les formes de l\'argumentation</h3>'
                    + '<ul>'
                    + '<li><strong>L\'essai</strong> : texte en prose ou l\'auteur expose ses idees et reflexions de maniere personnelle. Genre fonde par Montaigne (Essais, 1580).</li>'
                    + '<li><strong>L\'apologue</strong> : court recit a visee morale ou didactique (fable, conte philosophique, parabole).</li>'
                    + '<li><strong>La fable</strong> : recit bref, souvent en vers, mettant en scene des animaux pour delivrer une morale (La Fontaine).</li>'
                    + '<li><strong>Le conte philosophique</strong> : recit fictif et divertissant qui vehicule une critique sociale ou philosophique (Voltaire, Candide, Zadig, Micromegas).</li>'
                    + '<li><strong>Le dialogue</strong> : forme argumentative ou deux interlocuteurs confrontent leurs points de vue (dialogue philosophique de Diderot).</li>'
                    + '<li><strong>Le pamphlet</strong> : texte court et violent qui attaque une personne, une institution ou une idee.</li>'
                    + '<li><strong>Le discours</strong> : texte oratoire destine a etre prononce devant un public, visant a convaincre ou emouvoir (Hugo, discours contre la peine de mort).</li>'
                    + '</ul>'
                    + '<h3>Convaincre, persuader, deliberer</h3>'
                    + '<ul>'
                    + '<li><strong>Convaincre</strong> : s\'adresser a la raison du destinataire par des arguments logiques et des preuves. L\'objectif est de faire adherer l\'interlocuteur par la demonstration.</li>'
                    + '<li><strong>Persuader</strong> : s\'adresser aux emotions et aux sentiments du destinataire pour l\'amener a adherer. Utilise les figures de style, les images, les appels aux sentiments.</li>'
                    + '<li><strong>Deliberer</strong> : peser le pour et le contre d\'une question, examiner les differents points de vue avant de se forger une opinion. C\'est la demarche de l\'essai et du dialogue.</li>'
                    + '</ul>'
                    + '<h3>Argumentation directe et indirecte</h3>'
                    + '<ul>'
                    + '<li><strong>Argumentation directe</strong> : l\'auteur expose explicitement sa these, sans detour narratif. Formes : essai, discours, article, lettre ouverte, pamphlet. L\'auteur assume sa position.</li>'
                    + '<li><strong>Argumentation indirecte</strong> : l\'auteur passe par la fiction (recit, personnages) pour defendre implicitement une these. Formes : fable, conte philosophique, roman a these, utopie. Le lecteur doit deduire la lecon.</li>'
                    + '</ul>'
                    + '<h3>Les strategies argumentatives</h3>'
                    + '<ul>'
                    + '<li><strong>Le syllogisme</strong> : raisonnement logique en trois propositions (majeure, mineure, conclusion). Exemple : Tous les hommes sont mortels ; Socrate est un homme ; donc Socrate est mortel.</li>'
                    + '<li><strong>L\'argument d\'autorite</strong> : invoquer une source reconnue (expert, scientifique, penseur) pour appuyer sa these.</li>'
                    + '<li><strong>L\'analogie</strong> : comparer une situation a une autre pour rendre l\'argument plus parlant et accessible.</li>'
                    + '<li><strong>La concession</strong> : admettre partiellement le point de vue adverse avant de le refuter. "Certes... mais..." Renforce la credibilite de l\'argumentateur.</li>'
                    + '<li><strong>La refutation</strong> : reponse directe a un argument adverse, en demontrant sa faiblesse ou son erreur.</li>'
                    + '</ul>'
                    + '<h3>Les registres de l\'argumentation</h3>'
                    + '<ul>'
                    + '<li><strong>Le registre polemique</strong> : ton agressif, vocabulaire devalorisant, attaque directe de l\'adversaire (pamphlet, requisitoire). Exemple : J\'accuse de Zola.</li>'
                    + '<li><strong>Le registre didactique</strong> : ton pedagogique, explication claire, volonte d\'instruire le lecteur. Exemple : les articles de l\'Encyclopedie.</li>'
                    + '<li><strong>Le registre satirique</strong> : utilisation du rire et de la moquerie pour denoncer les travers. La Fontaine, Voltaire.</li>'
                    + '<li><strong>Le registre ironique</strong> : dire le contraire de ce que l\'on pense pour denoncer une situation. Procede favori de Voltaire.</li>'
                    + '</ul>'
                    + '<h3>L\'ironie comme arme argumentative</h3>'
                    + '<ul>'
                    + '<li><strong>L\'ironie</strong> : figure de style consistant a dire le contraire de ce que l\'on pense. Le lecteur doit decoder le sens veritable. Voltaire en est le maitre inconteste.</li>'
                    + '<li><strong>L\'antiphrase</strong> : forme la plus simple de l\'ironie, ou le mot employe signifie exactement le contraire de ce qu\'il dit.</li>'
                    + '<li><strong>L\'ironie voltairienne</strong> : dans Candide, Voltaire feint de presenter comme normal ce qui est revoltant (guerre, esclavage, fanatisme) pour mieux le denoncer.</li>'
                    + '</ul>'
                    + '<h3>Les grands auteurs de l\'argumentation</h3>'
                    + '<ul>'
                    + '<li><strong>Montaigne</strong> : Essais (1580-1595). Fondateur de l\'essai, il examine les grandes questions humaines avec scepticisme et tolerance. "Que sais-je ?"</li>'
                    + '<li><strong>La Fontaine</strong> : Fables (1668-1694). Recits brefs mettant en scene des animaux pour critiquer la societe et delivrer des lecons morales. Argumentation indirecte par excellence.</li>'
                    + '<li><strong>Voltaire</strong> : Candide, Zadig, Dictionnaire philosophique, Traite sur la tolerance. Maitre de l\'ironie, il combat le fanatisme, l\'injustice et l\'intolerance.</li>'
                    + '<li><strong>Rousseau</strong> : Discours sur l\'origine de l\'inegalite, Du contrat social, Emile. Il pense l\'etat de nature, le contrat social et l\'education selon la nature.</li>'
                    + '<li><strong>Montesquieu</strong> : Lettres persanes (regard decentre), De l\'esprit des lois (separation des pouvoirs). Il utilise le regard etranger pour critiquer la societe francaise.</li>'
                    + '<li><strong>Hugo</strong> : discours politiques (abolition de la peine de mort, contre la misere), Les Chatiments. Eloquence engagee au service de la justice sociale.</li>'
                    + '<li><strong>Zola</strong> : J\'accuse (1898). Lettre ouverte au President de la Republique en faveur de Dreyfus. Chef-d\'oeuvre du registre polemique, engagement de l\'intellectuel.</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Quelle est la difference entre convaincre et persuader ?', answer: 'Convaincre s\'adresse a la raison par des arguments logiques et des preuves. Persuader s\'adresse aux emotions et aux sentiments par des procedes rhetoriques. Les deux visent l\'adhesion du destinataire mais par des voies differentes.' },
                    { question: 'Quelle est la difference entre argumentation directe et indirecte ?', answer: 'L\'argumentation directe expose explicitement la these de l\'auteur (essai, discours, pamphlet). L\'argumentation indirecte passe par la fiction pour defendre implicitement une these (fable, conte philosophique, roman a these). Le lecteur doit decoder le message.' },
                    { question: 'Qu\'est-ce qu\'un apologue ?', answer: 'Un apologue est un court recit a visee morale ou didactique. La fable (La Fontaine), le conte philosophique (Voltaire) et la parabole en sont les formes principales. Il releve de l\'argumentation indirecte : la lecon se degage du recit.' },
                    { question: 'Qu\'est-ce que l\'ironie en argumentation ?', answer: 'L\'ironie consiste a dire le contraire de ce que l\'on pense pour denoncer une situation. Le lecteur doit decoder le sens veritable. Voltaire en est le maitre : dans Candide, il feint de presenter comme normal ce qui est revoltant pour mieux le critiquer.' },
                    { question: 'Qu\'est-ce qu\'un syllogisme ?', answer: 'Un raisonnement logique en trois propositions : une majeure (regle generale), une mineure (cas particulier) et une conclusion. Exemple : Tous les hommes sont mortels (majeure) ; Socrate est un homme (mineure) ; donc Socrate est mortel (conclusion).' },
                    { question: 'Qu\'est-ce que l\'argument d\'autorite ?', answer: 'L\'argument d\'autorite consiste a invoquer une source reconnue (expert, scientifique, penseur celebre) pour appuyer sa these. Il repose sur le prestige ou la competence de la personne citee plutot que sur un raisonnement logique autonome.' },
                    { question: 'Qu\'est-ce que la concession en argumentation ?', answer: 'La concession consiste a admettre partiellement le point de vue adverse avant de le refuter. Structure typique : "Certes... mais..." Elle renforce la credibilite de l\'argumentateur en montrant qu\'il connait et prend en compte les objections.' },
                    { question: 'En quoi Candide de Voltaire est-il un conte philosophique ?', answer: 'Candide utilise un recit d\'aventures fictif et divertissant pour critiquer l\'optimisme de Leibniz ("tout est pour le mieux dans le meilleur des mondes possibles"), le fanatisme religieux, la guerre et l\'esclavage. C\'est de l\'argumentation indirecte par l\'ironie.' },
                    { question: 'Qu\'est-ce que le registre polemique ?', answer: 'Le registre polemique se caracterise par un ton agressif, un vocabulaire devalorisant et une attaque directe de l\'adversaire. Il vise a disqualifier la these adverse. J\'accuse de Zola et les pamphlets de Hugo en sont des exemples celebres.' },
                    { question: 'Qu\'est-ce que le registre didactique ?', answer: 'Le registre didactique se caracterise par un ton pedagogique, des explications claires et une volonte d\'instruire le lecteur. Il utilise des definitions, des exemples, une progression logique. Les articles de l\'Encyclopedie en sont un modele.' },
                    { question: 'Pourquoi Montaigne est-il le fondateur de l\'essai ?', answer: 'Montaigne invente le genre de l\'essai avec ses Essais (1580-1595) : un texte en prose ou l\'auteur "s\'essaie", c\'est-a-dire examine librement les questions humaines a partir de son experience personnelle. Sa devise "Que sais-je ?" incarne le doute fecond.' },
                    { question: 'Comment La Fontaine utilise-t-il la fable pour argumenter ?', answer: 'La Fontaine utilise l\'argumentation indirecte : des recits brefs mettant en scene des animaux pour critiquer la societe de son temps (la cour, l\'injustice, les puissants). La morale, explicite ou implicite, invite le lecteur a la reflexion.' },
                    { question: 'Qu\'est-ce que le regard decentre dans les Lettres persanes ?', answer: 'Montesquieu fait observer la societe francaise par des Persans fictifs (Rica et Usbek). Ce regard etranger permet de rendre etrange ce qui semble naturel et de denoncer les travers sociaux, religieux et politiques de la France avec une ironie efficace.' },
                    { question: 'Qu\'est-ce qu\'une utopie en argumentation ?', answer: 'L\'utopie est un recit qui decrit une societe ideale imaginaire pour critiquer la societe reelle par contraste. Thomas More invente le genre (Utopia, 1516). Voltaire (Eldorado dans Candide) et Rabelais (Abbaye de Theleme) l\'utilisent aussi.' },
                    { question: 'Qu\'est-ce que J\'accuse de Zola ?', answer: 'Lettre ouverte publiee le 13 janvier 1898 dans L\'Aurore, adressee au President de la Republique, en faveur du capitaine Dreyfus injustement accuse. C\'est un modele de registre polemique et l\'acte fondateur de l\'intellectuel engage en France.' },
                    { question: 'Qu\'est-ce que deliberer en argumentation ?', answer: 'Deliberer consiste a peser le pour et le contre d\'une question, a examiner differents points de vue avant de se forger une opinion. C\'est la demarche de l\'essai (Montaigne) et du dialogue philosophique (Diderot). Elle suppose ouverture d\'esprit et examen critique.' },
                    { question: 'Quelle est la these de Rousseau dans le Discours sur l\'origine de l\'inegalite ?', answer: 'Rousseau soutient que l\'homme est naturellement bon et que c\'est la societe qui le corrompt. L\'inegalite n\'est pas naturelle mais resulte de la propriete privee et de l\'organisation sociale. "L\'homme nait bon, c\'est la societe qui le deprave."' },
                    { question: 'Qu\'est-ce qu\'une antiphrase ?', answer: 'L\'antiphrase est la forme la plus simple de l\'ironie : elle consiste a employer un mot ou une expression dans un sens contraire a sa signification reelle. Exemple : dire "Quel beau temps !" sous une pluie battante. Voltaire l\'utilise abondamment.' },
                    { question: 'Comment Hugo argumente-t-il contre la peine de mort ?', answer: 'Hugo utilise l\'eloquence du discours politique, les appels a la pitie et a l\'humanite, les exemples concrets d\'erreurs judiciaires, et un registre pathetique. Dans Le Dernier Jour d\'un condamne (roman), il utilise aussi l\'argumentation indirecte par la fiction.' },
                    { question: 'Qu\'est-ce que la refutation en argumentation ?', answer: 'La refutation est la reponse directe a un argument adverse : on en demontre la faiblesse, l\'erreur logique ou l\'insuffisance. Elle peut prendre la forme d\'un contre-exemple, d\'une objection logique ou d\'une deconstruction du raisonnement adverse.' },
                    { question: 'Qu\'est-ce que l\'Encyclopedie de Diderot et d\'Alembert ?', answer: 'Oeuvre collective des Lumieres (1751-1772), l\'Encyclopedie vise a rassembler tout le savoir humain. Elle utilise le registre didactique mais aussi l\'ironie et la critique pour combattre les prejuges, le despotisme et le fanatisme religieux.' },
                    { question: 'Qu\'est-ce qu\'un pamphlet ?', answer: 'Un pamphlet est un texte court et virulent qui attaque une personne, une institution ou une idee avec vehemence. Il releve du registre polemique et vise a indigner le lecteur. Les Chatiments de Hugo contre Napoleon III en sont un exemple.' },
                    { question: 'Comment Voltaire utilise-t-il le conte philosophique pour combattre le fanatisme ?', answer: 'Voltaire cree des personnages naifs qui decouvrent les horreurs du monde (guerres de religion, Inquisition, intolerance). L\'ironie du narrateur souligne l\'absurdite du fanatisme. Le lecteur rit puis reflechit. Candide et Zadig illustrent cette methode.' },
                    { question: 'Qu\'est-ce que l\'analogie en argumentation ?', answer: 'L\'analogie consiste a comparer une situation a une autre, connue et acceptee, pour rendre l\'argument plus accessible et convaincant. Elle facilite la comprehension en s\'appuyant sur le familier pour eclairer le nouveau ou le complexe.' },
                    { question: 'Quel est le role de l\'exemple en argumentation ?', answer: 'L\'exemple illustre et renforce un argument abstrait en le rendant concret. Il peut etre reel (fait historique, temoignage), fictif (anecdote inventee) ou litteraire (reference a une oeuvre). Il rend l\'argumentation plus vivante et plus convaincante.' },
                    { question: 'Qu\'est-ce que le contrat social selon Rousseau ?', answer: 'Dans Du contrat social (1762), Rousseau definit un pacte par lequel les individus renoncent a leur liberte naturelle pour obtenir la liberte civile et l\'egalite. La souverainete appartient au peuple qui exprime la "volonte generale".' },
                    { question: 'Qu\'est-ce que la separation des pouvoirs selon Montesquieu ?', answer: 'Dans De l\'esprit des lois (1748), Montesquieu theorise la separation des pouvoirs legislatif, executif et judiciaire pour eviter le despotisme. "Pour qu\'on ne puisse abuser du pouvoir, il faut que le pouvoir arrete le pouvoir."' },
                    { question: 'En quoi la fable est-elle une forme d\'argumentation efficace ?', answer: 'La fable argue indirectement : le recit plaisant capte l\'attention, les animaux personnifies creent une distance qui facilite la critique, la morale delivre une lecon universelle. Elle "instruit en amusant", selon le principe du "placere et docere".' },
                    { question: 'Qu\'est-ce que le registre satirique ?', answer: 'Le registre satirique utilise le rire, la moquerie et la caricature pour denoncer les travers de la societe. Il peut recourir a l\'ironie, a l\'exageration et au comique. La Fontaine critique les puissants, Voltaire se moque du fanatisme.' },
                    { question: 'Comment les philosophes des Lumieres ont-ils utilise l\'argumentation ?', answer: 'Les Lumieres combinent argumentation directe (essais, articles, discours) et indirecte (contes, fables, dialogues). Ils utilisent la raison pour combattre les prejuges, le fanatisme et le despotisme. Voltaire, Rousseau, Montesquieu et Diderot en sont les figures majeures.' }
                ],
                quiz: [
                    { question: 'Qui est considere comme le fondateur du genre de l\'essai ?', options: ['Voltaire', 'Rousseau', 'Montaigne', 'Diderot'], correctIndex: 2, explanation: 'Montaigne invente le genre de l\'essai avec ses Essais (1580-1595), ou il examine librement les grandes questions humaines.' },
                    { question: 'Candide de Voltaire est un exemple de :', options: ['Conte philosophique', 'Roman realiste', 'Essai', 'Fable'], correctIndex: 0, explanation: 'Candide (1759) est un conte philosophique : un recit fictif et divertissant qui vehicule une critique de l\'optimisme et du fanatisme.' },
                    { question: 'Quelle est la difference entre argumentation directe et indirecte ?', options: ['Directe = orale, indirecte = ecrite', 'Directe = explicite, indirecte = par la fiction', 'Directe = courte, indirecte = longue', 'Directe = logique, indirecte = emotionnelle'], correctIndex: 1, explanation: 'L\'argumentation directe expose la these explicitement (essai, discours). L\'indirecte passe par la fiction (fable, conte) et le lecteur doit decoder la these.' },
                    { question: 'J\'accuse de Zola est :', options: ['Une lettre ouverte polemique', 'Un conte philosophique', 'Un roman naturaliste', 'Un essai didactique'], correctIndex: 0, explanation: 'J\'accuse (1898) est une lettre ouverte au President de la Republique, texte polemique en defense du capitaine Dreyfus.' },
                    { question: 'Qu\'est-ce qu\'un syllogisme ?', options: ['Un raisonnement en trois propositions', 'Une figure de style', 'Un type de pamphlet', 'Un procede ironique'], correctIndex: 0, explanation: 'Le syllogisme est un raisonnement logique compose d\'une majeure, une mineure et une conclusion. Ex : Tous les hommes sont mortels ; Socrate est un homme ; donc Socrate est mortel.' },
                    { question: 'Quel procede Voltaire utilise-t-il le plus dans ses contes ?', options: ['L\'ironie', 'Le syllogisme', 'La concession', 'L\'argument d\'autorite'], correctIndex: 0, explanation: 'Voltaire est le maitre de l\'ironie : il feint de presenter comme normal ce qui est revoltant pour mieux le denoncer (guerre, fanatisme, esclavage dans Candide).' },
                    { question: 'Quel auteur a ecrit les Fables ?', options: ['Voltaire', 'Montaigne', 'Perrault', 'La Fontaine'], correctIndex: 3, explanation: 'Jean de La Fontaine publie ses Fables entre 1668 et 1694, mettant en scene des animaux pour delivrer des lecons morales et critiquer la societe.' },
                    { question: 'Le regard decentre des Lettres persanes est un procede de :', options: ['Montaigne', 'Voltaire', 'Diderot', 'Montesquieu'], correctIndex: 3, explanation: 'Montesquieu utilise le regard de Persans fictifs pour observer et critiquer la societe francaise avec distance et ironie dans les Lettres persanes (1721).' },
                    { question: 'La concession en argumentation sert a :', options: ['Admettre l\'argument adverse pour le refuter ensuite', 'Attaquer directement l\'adversaire', 'Donner un exemple concret', 'Citer une autorite'], correctIndex: 0, explanation: 'La concession ("Certes... mais...") montre que l\'on connait le point de vue adverse, ce qui renforce la credibilite avant de le refuter.' },
                    { question: 'Quel philosophe soutient que "l\'homme nait bon, c\'est la societe qui le deprave" ?', options: ['Voltaire', 'Montesquieu', 'Diderot', 'Rousseau'], correctIndex: 3, explanation: 'Jean-Jacques Rousseau developpe cette these dans le Discours sur l\'origine de l\'inegalite (1755) et Emile (1762).' },
                    { question: 'L\'Encyclopedie de Diderot et d\'Alembert utilise principalement le registre :', options: ['Polemique', 'Tragique', 'Lyrique', 'Didactique'], correctIndex: 3, explanation: 'L\'Encyclopedie (1751-1772) adopte un registre didactique : elle vise a instruire le lecteur en rassemblant tout le savoir humain de maniere raisonnee.' },
                    { question: 'Qu\'est-ce qu\'une antiphrase ?', options: ['Une repetition insistante', 'Une comparaison', 'Une exageration', 'Un mot employe dans le sens contraire'], correctIndex: 3, explanation: 'L\'antiphrase est la forme la plus simple de l\'ironie : dire le contraire de ce que l\'on pense. Ex : "Quel beau temps !" quand il pleut.' },
                    { question: 'Montesquieu theorise la separation des pouvoirs dans :', options: ['Les Lettres persanes', 'De l\'esprit des lois', 'Le Contrat social', 'L\'Encyclopedie'], correctIndex: 1, explanation: 'Dans De l\'esprit des lois (1748), Montesquieu distingue les pouvoirs legislatif, executif et judiciaire pour prevenir le despotisme.' },
                    { question: 'Les Chatiments de Hugo sont un exemple de :', options: ['Conte philosophique', 'Fable', 'Poesie polemique', 'Essai didactique'], correctIndex: 2, explanation: 'Les Chatiments (1853) sont un recueil de poemes polemiques ou Hugo attaque violemment Napoleon III apres le coup d\'Etat du 2 decembre 1851.' },
                    { question: 'Qu\'est-ce que persuader, par opposition a convaincre ?', options: ['S\'adresser a la raison', 'S\'adresser aux emotions', 'Donner des preuves', 'Utiliser un syllogisme'], correctIndex: 1, explanation: 'Persuader fait appel aux sentiments et aux emotions du destinataire, tandis que convaincre s\'adresse a sa raison par des arguments logiques.' },
                    { question: 'Quel texte de Rousseau theorise le pacte entre les citoyens ?', options: ['Emile', 'Les Confessions', 'Du contrat social', 'Discours sur les sciences et les arts'], correctIndex: 2, explanation: 'Du contrat social (1762) definit un pacte ou les individus abandonnent leur liberte naturelle pour obtenir la liberte civile et l\'egalite sous la volonte generale.' },
                    { question: 'La devise "Que sais-je ?" est celle de :', options: ['Descartes', 'Voltaire', 'Montaigne', 'Pascal'], correctIndex: 2, explanation: 'Montaigne adopte cette devise sceptique qui exprime le doute philosophique et la conscience des limites de la connaissance humaine.' },
                    { question: 'Quel est le but principal de l\'argumentation indirecte ?', options: ['Informer le lecteur objectivement', 'Faire adherer par le plaisir du recit', 'Attaquer un adversaire', 'Donner des ordres'], correctIndex: 1, explanation: 'L\'argumentation indirecte utilise le plaisir de la fiction (recit, personnages, aventures) pour faire passer un message sans l\'imposer frontalement.' },
                    { question: 'Dans quel texte Voltaire defend-il la tolerance religieuse ?', options: ['Candide', 'Zadig', 'Traite sur la tolerance', 'Lettres philosophiques'], correctIndex: 2, explanation: 'Le Traite sur la tolerance (1763) est un plaidoyer de Voltaire pour la tolerance religieuse, ecrit apres l\'affaire Calas.' },
                    { question: 'Quelle strategie argumentative utilise "Certes... mais..." ?', options: ['L\'analogie', 'La concession', 'Le syllogisme', 'L\'argument d\'autorite'], correctIndex: 1, explanation: 'La structure "Certes... mais..." est typique de la concession : on admet l\'argument adverse pour mieux le depasser et le refuter ensuite.' },
                    { question: 'Quelle figure de style consiste a attenuer l\'expression pour suggerer davantage (dire moins pour signifier plus) ?', options: ['L\'hyperbole', 'La litote', 'La metonymie', 'L\'anaphore'], correctIndex: 1, explanation: 'La litote consiste a dire moins pour exprimer plus. L\'exemple le plus celebre est "Va, je ne te hais point" (Chimene a Rodrigue dans Le Cid), qui signifie en realite "je t\'aime".' },
                    { question: 'Quel mouvement litteraire du XVIIIe siecle fait de la raison l\'outil principal de lutte contre les prejuges ?', options: ['Le romantisme', 'Le classicisme', 'Les Lumieres', 'Le symbolisme'], correctIndex: 2, explanation: 'Les Lumieres (XVIIIe siecle) placent la raison au centre de leur demarche pour combattre l\'obscurantisme, le fanatisme et le despotisme. Voltaire, Rousseau, Montesquieu et Diderot en sont les figures majeures.' },
                    { question: 'Dans une dissertation litteraire, quelle partie suit l\'introduction et developpe les arguments ?', options: ['La conclusion', 'L\'ouverture', 'Le developpement', 'L\'amorce'], correctIndex: 2, explanation: 'La dissertation suit un plan en trois parties : introduction (amorce, problematique, annonce du plan), developpement (en deux ou trois parties argumentees avec exemples litteraires) et conclusion (bilan et ouverture). Le developpement est le coeur de l\'argumentation.' },
                    { question: 'Quelle figure de style consiste a repeter un meme mot ou groupe de mots en debut de vers ou de phrase ?', options: ['La metaphore', 'L\'anaphore', 'La metonymie', 'L\'hyperbole'], correctIndex: 1, explanation: 'L\'anaphore est la repetition d\'un meme mot ou groupe de mots au debut de phrases ou de vers successifs. Elle cree un effet d\'insistance et de rythme. Hugo l\'utilise dans "Demain, des l\'aube..." et Zola dans "J\'accuse...".' }
                ]
            }
        ]
    });
})();
