// hggsp.js — Donnees HGGSP Terminale (6 themes du programme officiel BO)
// Format pedagogique adapte dys/TSA : phrases courtes, exemples concrets, mots difficiles expliques
(function() {
    if (!window.StudFlow || !window.StudFlow.subjects) return;

    window.StudFlow.subjects.register({
        id: 'hggsp',
        name: 'HGGSP',
        icon: '\uD83C\uDF0D',
        color: 'sky',
        sections: [

            // ================================================================
            // SECTION 1 : DE NOUVEAUX ESPACES DE CONQUETE
            // ================================================================
            {
                id: 'espaces-conquete',
                title: 'De nouveaux espaces de conquete',
                icon: '\uD83D\uDE80',
                content: '<h3>Conquete spatiale et ocean</h3>'
                    + '<ul>'
                    + '<li><strong>L\'espace</strong> : enjeu de puissance (course spatiale, satellites, exploration)</li>'
                    + '<li><strong>Les oceans</strong> : enjeu geopolitique (ressources, routes maritimes, ZEE)</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Pourquoi l\'espace est un enjeu de puissance ?', answer: 'L\'espace = POUVOIR. Celui qui controle l\'espace controle les COMMUNICATIONS (satellites), le RENSEIGNEMENT (espionnage), le MILITAIRE (missiles). Pendant la guerre froide : course spatiale USA vs URSS. Spoutnik (1957, URSS) puis Apollo 11 (1969, USA, premier homme sur la Lune). Aujourd\'hui : Chine, Inde, SpaceX (Elon Musk) = nouveaux acteurs. En gros : l\'espace n\'est plus reserve aux Etats, les entreprises privees y entrent. Mots difficiles : "course spatiale" = competition entre pays pour etre le premier dans l\'espace.' },
                    { question: 'C\'est quoi la "course spatiale" pendant la guerre froide ?', answer: '1957 : URSS lance SPOUTNIK (1er satellite). Les USA paniquent. 1961 : URSS envoie GAGARINE (1er homme dans l\'espace). 1969 : USA repondent avec APOLLO 11 (Neil Armstrong, 1er homme sur la Lune). La course spatiale = une vitrine de PUISSANCE. Le vainqueur prouve que son systeme (capitalisme ou communisme) est superieur. En gros : l\'espace etait un champ de bataille SYMBOLIQUE entre USA et URSS.' },
                    { question: 'Quels sont les nouveaux acteurs de l\'espace ?', answer: 'CHINE : station spatiale Tiangong, face cachee de la Lune (2019), objectif Mars. INDE : mission Chandrayaan (Lune, 2023, a moindre cout). SPACEX (Elon Musk) : fusees reutilisables, projet Starlink (Internet par satellite). BLUE ORIGIN (Jeff Bezos) : tourisme spatial. En gros : l\'espace n\'est plus un duopole USA-Russie. Les entreprises PRIVEES et les pays EMERGENTS changent la donne. Mots difficiles : "New Space" = l\'industrie spatiale privee (startups, milliardaires).' },
                    { question: 'Pourquoi les oceans sont un enjeu geopolitique ?', answer: 'Les oceans couvrent 70% de la planete. Enjeux : 1) RESSOURCES : petrole, gaz, minerais sous-marins, peche. 2) ROUTES MARITIMES : 90% du commerce mondial passe par la mer (detroits, canaux). 3) ZEE : zone de 200 milles nautiques ou un Etat a des droits exclusifs. 4) MILITAIRE : sous-marins nucleaires, bases navales. En gros : qui controle la mer, controle le commerce mondial. Mots difficiles : "ZEE" (Zone Economique Exclusive) = la zone maritime d\'un pays ou il peut exploiter les ressources.' },
                    { question: 'C\'est quoi les detroits et canaux strategiques ?', answer: 'Les DETROITS = passages naturels entre deux mers. ORMUZ (Golfe persique, 30% du petrole mondial). MALACCA (entre Asie et Oceanie, route Chine-Europe). Les CANAUX = passages artificiels. SUEZ (1869, relie Mediterranee et mer Rouge, evite de contourner l\'Afrique). PANAMA (1914, relie Atlantique et Pacifique). En gros : bloquer un detroit = bloquer le commerce mondial. C\'est pourquoi ces zones sont ultra-surveillees.' },
                    { question: 'C\'est quoi l\'Arctique comme enjeu ?', answer: 'L\'Arctique FOND a cause du rechauffement climatique. Consequences : 1) De nouvelles ROUTES MARITIMES s\'ouvrent (passage du Nord-Est, plus court que Suez). 2) Des RESSOURCES deviennent accessibles (petrole, gaz, minerais). 3) TENSIONS entre la Russie, le Canada, les USA, la Norvege, le Danemark — chacun revendique une partie. En gros : l\'Arctique est le "nouveau Far West" — un espace qui s\'ouvre et que tout le monde veut. Mots difficiles : "revendiquer" = dire que quelque chose vous appartient.' },
                    { question: 'C\'est quoi le droit de la mer ?', answer: 'La Convention de Montego Bay (1982) definit les regles : EAUX TERRITORIALES = 12 milles, souverainete totale. ZEE = 200 milles, droits d\'exploitation des ressources. HAUTE MER = au-dela, LIBRE pour tous (peche, navigation). PLATEAU CONTINENTAL = le fond marin prolongeant le continent, exploitable. Probleme : la Chine en mer de Chine du Sud IGNORE le droit de la mer et construit des iles artificielles. En gros : le droit de la mer existe, mais pas tous les pays le respectent.' },
                    { question: 'C\'est quoi la militarisation de l\'espace ?', answer: 'Les Etats developpent des ARMES SPATIALES : satellites espions, armes antisatellites (ASAT), systemes de defense antimissile. USA : creation de la Space Force (2019, Trump). Chine et Russie : tests d\'armes antisatellites. Traite de l\'espace (1967) : interdit les armes nucleaires dans l\'espace, mais PAS les autres armes. En gros : l\'espace est le prochain champ de bataille. Mots difficiles : "ASAT" = Anti-Satellite, arme qui detruit les satellites ennemis.' }
                ],
                quiz: [
                    { question: 'Le premier satellite mis en orbite est :', options: ['Apollo 11', 'Spoutnik', 'Hubble', 'Starlink'], correctIndex: 1, explanation: 'Spoutnik, lance par l\'URSS en 1957, est le premier satellite artificiel. Il marque le debut de la course spatiale.' },
                    { question: 'La ZEE s\'etend sur :', options: ['12 milles', '50 milles', '200 milles', '500 milles'], correctIndex: 2, explanation: 'La ZEE (Zone Economique Exclusive) s\'etend sur 200 milles nautiques (environ 370 km) a partir des cotes.' },
                    { question: 'Le detroit d\'Ormuz est strategique car :', options: ['Il relie l\'Atlantique au Pacifique', '30% du petrole mondial y transite', 'Il est le plus large du monde', 'Il appartient aux USA'], correctIndex: 1, explanation: 'Le detroit d\'Ormuz relie le golfe Persique a l\'ocean Indien. 30% du petrole mondial y passe.' },
                    { question: 'SpaceX est une entreprise de :', options: ['Jeff Bezos', 'Elon Musk', 'La NASA', 'L\'ESA europeenne'], correctIndex: 1, explanation: 'SpaceX, fondee par Elon Musk, est pionniere des fusees reutilisables et du projet Starlink.' },
                    { question: 'L\'Arctique est un enjeu a cause :', options: ['De sa population', 'De la fonte des glaces ouvrant routes et ressources', 'De ses villes', 'De son agriculture'], correctIndex: 1, explanation: 'Le rechauffement climatique fait fondre l\'Arctique, ouvrant de nouvelles routes maritimes et rendant des ressources accessibles.' },
                    { question: 'La Convention de Montego Bay date de :', options: ['1945', '1967', '1982', '2001'], correctIndex: 2, explanation: 'La Convention de Montego Bay (1982) definit le droit de la mer : eaux territoriales, ZEE, haute mer, plateau continental.' },
                    { question: 'La Space Force americaine a ete creee en :', options: ['2001', '2010', '2019', '2023'], correctIndex: 2, explanation: 'La Space Force a ete creee par Trump en 2019 comme branche militaire dediee a l\'espace.' }
                ]
            },

            // ================================================================
            // SECTION 2 : FAIRE LA GUERRE, FAIRE LA PAIX
            // ================================================================
            {
                id: 'guerre-paix',
                title: 'Faire la guerre, faire la paix',
                icon: '\u2694\uFE0F',
                content: '<h3>Les formes de conflits et la construction de la paix</h3>'
                    + '<ul>'
                    + '<li><strong>Clausewitz</strong> : "La guerre est la continuation de la politique par d\'autres moyens"</li>'
                    + '<li><strong>La paix</strong> : traites, organisations internationales, justice internationale</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'C\'est quoi la guerre selon Clausewitz ?', answer: 'Carl von CLAUSEWITZ (general prussien, XIXe siecle) dit : "La guerre est la continuation de la politique par d\'autres moyens." Ca veut dire : quand la diplomatie echoue, on passe aux armes. La guerre a un OBJECTIF POLITIQUE (conquete, defense, liberation). En gros : la guerre n\'est pas juste de la violence, c\'est un outil politique. Mots difficiles : "Clausewitz" = le theoricien de la guerre le plus cite au monde.' },
                    { question: 'Comment les guerres ont evolue ?', answer: 'AVANT : guerres entre ETATS, armees regulieres, batailles rangees (Napoleoniennes, 14-18). MAINTENANT : guerres ASYMETRIQUES (un Etat vs un groupe arme : terrorisme, guerilla), guerres CIVILES (Syrie, Libye), cyberguerres (attaques informatiques), guerres hybrides (Russie en Ukraine : armees + desinformation + cyberattaques). En gros : la guerre classique (deux armees face a face) est devenue RARE. Les conflits modernes sont flous et complexes. Mots difficiles : "asymetrique" = quand les deux camps ne sont pas du meme niveau (un Etat vs un groupe arme).' },
                    { question: 'C\'est quoi le terrorisme ?', answer: 'Le terrorisme = l\'utilisation de la VIOLENCE contre des CIVILS pour creer la PEUR et atteindre un objectif politique ou religieux. Exemples : 11 septembre 2001 (Al-Qaida, USA), 13 novembre 2015 (Daech, Paris), attentat de Nice (2016). Le terrorisme est ASYMETRIQUE : un petit groupe peut frapper un Etat puissant. En gros : le terrorisme vise a TERRORISER pour obtenir du pouvoir. Mots difficiles : "Daech" = nom de l\'Etat islamique en arabe.' },
                    { question: 'C\'est quoi le Traite de Versailles (1919) ?', answer: 'Le traite qui met fin a la Premiere Guerre mondiale. Il punit l\'ALLEMAGNE : perte de territoires (Alsace-Lorraine), armee reduite, reparations financieres enormes. L\'Allemagne est humiliee. Resultat : montee du NAZISME (Hitler utilise cette humiliation). Le traite de Versailles est considere comme une "PAIX RATEE" car il a prepare la Deuxieme Guerre mondiale. En gros : une paix qui punit trop cree de la rancune et prepare la guerre suivante.' },
                    { question: 'C\'est quoi l\'ONU ?', answer: 'L\'Organisation des Nations Unies, creee en 1945 apres la Seconde Guerre mondiale. Objectif : EMPECHER les guerres par le dialogue. 193 pays membres. Le CONSEIL DE SECURITE (5 membres permanents : USA, Russie, Chine, France, Royaume-Uni) peut decider de sanctions ou d\'interventions militaires. Chaque permanent a un droit de VETO (peut bloquer seul une decision). En gros : l\'ONU = le parlement du monde. Mais le veto paralyse souvent les decisions.' },
                    { question: 'C\'est quoi la CPI ?', answer: 'La Cour Penale Internationale, creee en 2002 (Statut de Rome, 1998). Elle juge les INDIVIDUS (pas les Etats) pour : GENOCIDE (exterminer un peuple), CRIMES CONTRE L\'HUMANITE, CRIMES DE GUERRE. Siege a La Haye (Pays-Bas). Probleme : les USA, la Russie et la Chine ne reconnaissent PAS la CPI. En gros : la CPI essaie de punir les pires criminels, mais les plus puissants lui echappent. Mots difficiles : "genocide" = extermination volontaire d\'un groupe ethnique, religieux ou national.' },
                    { question: 'C\'est quoi le conflit israelo-palestinien ?', answer: 'Un conflit qui dure depuis 1948 (creation de l\'Etat d\'Israel). Les Palestiniens veulent leur propre ETAT sur des territoires occupes par Israel (Cisjordanie, Gaza). Accords d\'Oslo (1993) : tentative de paix, echouee. Depuis : violences des deux cotes, colonies israeliennes, blocus de Gaza, attaques du Hamas. En gros : deux peuples qui revendiquent le meme territoire. Aucune solution de paix n\'a fonctionne. Mots difficiles : "colonies" = implantations israeliennes en territoire palestinien, considerees illegales par l\'ONU.' },
                    { question: 'C\'est quoi la guerre en Ukraine ?', answer: 'En fevrier 2022, la Russie de Poutine ENVAHIT l\'Ukraine. Raisons invoquees : elargissement de l\'OTAN, protection des russophones, refus de l\'Ukraine dans le camp occidental. L\'Ukraine resiste (Zelensky). L\'Occident soutient l\'Ukraine (armes, sanctions contre la Russie). C\'est la premiere guerre d\'invasion en Europe depuis 1945. En gros : la Russie veut empecher l\'Ukraine de se rapprocher de l\'Europe et de l\'OTAN. Mots difficiles : "OTAN" = alliance militaire occidentale (30 pays, menee par les USA).' },
                    { question: 'C\'est quoi une guerre hybride ?', answer: 'Une guerre qui MELANGE : 1) Actions MILITAIRES classiques (troupes, bombes). 2) CYBERATTAQUES (piratage, paralysie des systemes). 3) DESINFORMATION (fake news, propagande, manipulation des reseaux sociaux). 4) Pressions ECONOMIQUES (sanctions, coupure du gaz). Exemple : la Russie en Ukraine utilise toutes ces methodes en meme temps. En gros : la guerre moderne ne se fait plus seulement avec des armes, mais aussi avec des ECRANS.' }
                ],
                quiz: [
                    { question: 'Clausewitz definit la guerre comme :', options: ['Un acte de barbarie', 'La continuation de la politique par d\'autres moyens', 'Un echec de l\'humanite', 'Un crime contre l\'humanite'], correctIndex: 1, explanation: 'Pour Clausewitz, la guerre est un OUTIL POLITIQUE : on fait la guerre quand la diplomatie echoue.' },
                    { question: 'Le traite de Versailles (1919) est considere comme :', options: ['Une paix juste', 'Une paix ratee qui a prepare la Deuxieme Guerre mondiale', 'Un succes diplomatique', 'Un traite sans consequence'], correctIndex: 1, explanation: 'L\'humiliation de l\'Allemagne a nourri le ressentiment et facilite la montee du nazisme.' },
                    { question: 'Les 5 membres permanents du Conseil de securite de l\'ONU sont :', options: ['USA, Russie, Chine, Allemagne, Japon', 'USA, Russie, Chine, France, Royaume-Uni', 'USA, France, Allemagne, Italie, Espagne', 'USA, Chine, Inde, Bresil, Afrique du Sud'], correctIndex: 1, explanation: 'Les 5 permanents (P5) sont les vainqueurs de 1945 : USA, Russie, Chine, France, Royaume-Uni. Chacun a un droit de veto.' },
                    { question: 'La CPI juge :', options: ['Les Etats', 'Les entreprises', 'Les individus pour genocide, crimes de guerre et crimes contre l\'humanite', 'Les conflits commerciaux'], correctIndex: 2, explanation: 'La CPI juge des INDIVIDUS (chefs d\'Etat, commandants militaires) pour les crimes les plus graves.' },
                    { question: 'La guerre en Ukraine a commence en :', options: ['2014', '2020', '2022', '2023'], correctIndex: 2, explanation: 'L\'invasion russe a grande echelle de l\'Ukraine date de fevrier 2022 (les tensions et l\'annexion de la Crimee datent de 2014).' },
                    { question: 'Une guerre asymetrique oppose :', options: ['Deux armees egales', 'Un Etat et un groupe arme non-etatique', 'Deux pays voisins', 'Deux alliances militaires'], correctIndex: 1, explanation: 'La guerre asymetrique oppose des forces de niveaux differents (ex : un Etat puissant vs un groupe terroriste).' },
                    { question: 'Une guerre hybride combine :', options: ['Infanterie et cavalerie', 'Actions militaires, cyber, desinformation et pressions economiques', 'Mer et air uniquement', 'Diplomatie et commerce'], correctIndex: 1, explanation: 'La guerre hybride melange tous les moyens : militaire, cyberattaques, fake news, sanctions economiques.' }
                ]
            },

            // ================================================================
            // SECTION 3 : HISTOIRE ET MEMOIRES
            // ================================================================
            {
                id: 'histoire-memoires',
                title: 'Histoire et memoires',
                icon: '\uD83D\uDDFF',
                content: '<h3>Comment les societes se souviennent et reconstruisent leur passe</h3>'
                    + '<ul>'
                    + '<li><strong>Memoire</strong> = subjectif, vecu, emotions</li>'
                    + '<li><strong>Histoire</strong> = objectif, methode, preuves</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Quelle difference entre HISTOIRE et MEMOIRE ?', answer: 'L\'HISTOIRE = une discipline SCIENTIFIQUE. L\'historien cherche la verite avec des preuves, des archives, une methode critique. Il doit etre OBJECTIF. La MEMOIRE = le SOUVENIR vecu par un groupe. Elle est SUBJECTIVE, emotionnelle, parfois deformee. Elle sert a construire une identite. En gros : l\'histoire dit "ce qui s\'est passe." La memoire dit "comment on s\'en souvient." Les deux peuvent etre differentes. Mots difficiles : "subjectif" = influence par les emotions et les opinions personnelles.' },
                    { question: 'C\'est quoi un "lieu de memoire" ?', answer: 'Concept invente par l\'historien Pierre NORA. Un lieu de memoire, c\'est un endroit, un objet ou un symbole qui REPRESENTE la memoire d\'un groupe. Exemples : le Pantheon (grands hommes de la Republique), le 11 novembre (memoire de 14-18), le drapeau tricolore, Auschwitz (memoire de la Shoah). En gros : un lieu de memoire = un symbole qui rappelle le passe a toute une societe. Mots difficiles : "lieu de memoire" = pas forcement un lieu physique, ca peut etre une date, un hymne, un monument.' },
                    { question: 'C\'est quoi la memoire de la Shoah ?', answer: 'La SHOAH = le genocide de 6 millions de Juifs par les nazis pendant la Seconde Guerre mondiale (1941-1945). Apres la guerre : SILENCE pendant des annees (les survivants ne parlent pas, la societe ne veut pas entendre). A partir des annees 1970-80 : les temoignages arrivent, les proces (Eichmann 1961, Barbie 1987, Papon 1998). Aujourd\'hui : "devoir de memoire" pour que ca ne se reproduise JAMAIS. En gros : la memoire de la Shoah a mis des decennies a s\'imposer. Mots difficiles : "genocide" = extermination volontaire et organisee d\'un peuple entier.' },
                    { question: 'C\'est quoi le devoir de memoire ?', answer: 'C\'est l\'obligation MORALE de se souvenir des crimes du passe pour qu\'ils ne se repetent pas. Ca passe par : les COMMEMORATIONS (ceremonies, minutes de silence), les MEMORIAUX (musees, monuments), l\'ENSEIGNEMENT (cours d\'histoire sur la Shoah, l\'esclavage, la colonisation), les LOIS MEMORIELLES (loi Gayssot 1990 qui punit la negation de la Shoah). En gros : le devoir de memoire = ne jamais oublier pour ne jamais recommencer.' },
                    { question: 'Memoire de la guerre d\'Algerie : pourquoi c\'est complique ?', answer: 'La guerre d\'Algerie (1954-1962) est une MEMOIRE DIVISEE en France : les PIEDS-NOIRS (Francais d\'Algerie) ont tout perdu. Les HARKIS (Algeriens pro-France) ont ete abandonnes. L\'ARMEE a pratique la torture (longtemps niee). Les ALGERIENS gardent la memoire de la colonisation. Pendant des decennies : SILENCE officiel. Ce n\'est qu\'en 1999 que la France reconnait le terme "GUERRE" (avant on disait "evenements"). En gros : une memoire a plusieurs voix, chacune avec sa souffrance. Mots difficiles : "pieds-noirs" = Francais nes en Algerie. "Harkis" = Algeriens qui ont combattu aux cotes de l\'armee francaise.' },
                    { question: 'C\'est quoi la justice transitionnelle ?', answer: 'Quand un pays sort d\'une guerre ou d\'une dictature, il doit faire face au PASSE. La justice transitionnelle = les outils pour ca : 1) PROCES des coupables (Nuremberg 1945-46, TPI pour le Rwanda). 2) COMMISSIONS VERITE (Afrique du Sud apres l\'apartheid, Commission Verite et Reconciliation de Mandela). 3) REPARATIONS (indemnisations des victimes). 4) REFORMES (changer les lois pour que ca ne se reproduise pas). En gros : comment faire justice apres l\'horreur.' },
                    { question: 'C\'est quoi le proces de Nuremberg ?', answer: 'Apres la Seconde Guerre mondiale (1945-46), les ALLIES jugent les principaux chefs nazis a Nuremberg (Allemagne). C\'est la PREMIERE FOIS qu\'on juge des dirigeants pour crimes contre l\'humanite. 12 condamnes a mort, 7 emprisonnes. Nuremberg cree un PRECEDENT : un chef d\'Etat peut etre juge pour ses crimes. Ca mene plus tard a la creation de la CPI. En gros : Nuremberg = le premier proces international de l\'histoire.' },
                    { question: 'Memoire et histoire sont-elles toujours d\'accord ?', answer: 'NON. La memoire peut DEFORMER le passe : elle oublie ce qui derange, elle glorifie ce qui arrange. Exemple : la memoire GAULLISTE dit que "tous les Francais ont resiste" pendant l\'Occupation. L\'HISTOIRE montre que beaucoup ont collabore (regime de Vichy). L\'historien Robert Paxton (1973) a montre le role actif de Vichy dans la deportation des Juifs. En gros : la memoire est un CHOIX (on decide de quoi se souvenir). L\'histoire est une RECHERCHE (on cherche la verite, meme desagreable).' }
                ],
                quiz: [
                    { question: 'La difference entre histoire et memoire :', options: ['Il n\'y en a pas', 'L\'histoire est objective et scientifique, la memoire est subjective et vecue', 'La memoire est plus fiable que l\'histoire', 'L\'histoire est plus ancienne que la memoire'], correctIndex: 1, explanation: 'L\'histoire utilise des sources et une methode critique. La memoire est le souvenir vecu, subjectif et emotionnel.' },
                    { question: 'Un "lieu de memoire" selon Pierre Nora est :', options: ['Uniquement un monument physique', 'Un symbole, lieu, date ou objet qui represente la memoire d\'un groupe', 'Un musee officiel', 'Un cimetiere militaire'], correctIndex: 1, explanation: 'Pour Pierre Nora, un lieu de memoire peut etre un monument, une date, un hymne, un drapeau — tout ce qui cristallise la memoire collective.' },
                    { question: 'La guerre d\'Algerie est officiellement reconnue comme "guerre" en France en :', options: ['1962', '1975', '1999', '2012'], correctIndex: 2, explanation: 'Ce n\'est qu\'en 1999 que le Parlement francais reconnait le terme "guerre" pour les "evenements d\'Algerie".' },
                    { question: 'Le proces de Nuremberg juge :', options: ['Les soldats allemands', 'Les dirigeants nazis pour crimes contre l\'humanite', 'Les collaborateurs francais', 'Les prisonniers de guerre'], correctIndex: 1, explanation: 'Nuremberg (1945-46) est le premier proces international jugeant des dirigeants pour crimes contre l\'humanite.' },
                    { question: 'La Commission Verite et Reconciliation est associee a :', options: ['L\'Allemagne nazie', 'L\'Afrique du Sud post-apartheid', 'La France de Vichy', 'Le Japon apres Hiroshima'], correctIndex: 1, explanation: 'Mandela cree cette commission en 1995 pour faire face aux crimes de l\'apartheid par la verite plutot que la vengeance.' },
                    { question: 'La loi Gayssot (1990) punit :', options: ['Le racisme en general', 'La negation de la Shoah', 'L\'apologie du terrorisme', 'La diffamation'], correctIndex: 1, explanation: 'La loi Gayssot (1990) est la premiere loi memorielle francaise : elle punit la negation du genocide des Juifs.' }
                ]
            },

            // ================================================================
            // SECTION 4 : PATRIMOINE
            // ================================================================
            {
                id: 'patrimoine',
                title: 'Identifier, proteger et valoriser le patrimoine',
                icon: '\uD83C\uDFDB\uFE0F',
                content: '<h3>Le patrimoine : un heritage a proteger</h3>'
                    + '<ul>'
                    + '<li><strong>Patrimoine</strong> = ce qu\'on herite du passe et qu\'on transmet</li>'
                    + '<li><strong>UNESCO</strong> = organisation qui protege le patrimoine mondial</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'C\'est quoi le patrimoine ?', answer: 'Le patrimoine = tout ce que le passe nous a LAISSE et qu\'on veut TRANSMETTRE aux generations futures. PATRIMOINE MATERIEL : monuments (Notre-Dame, Versailles), sites (Mont-Saint-Michel), objets (tableaux, sculptures). PATRIMOINE IMMATERIEL : traditions, savoir-faire, langues, musique, cuisine. En gros : le patrimoine = notre heritage collectif, ce qui fait notre identite. Mots difficiles : "patrimoine immateriel" = ce qu\'on ne peut pas toucher mais qui a une valeur culturelle (une recette, une fete, une langue).' },
                    { question: 'C\'est quoi l\'UNESCO et le patrimoine mondial ?', answer: 'L\'UNESCO (Nations Unies pour l\'education, la science et la culture) gere la LISTE DU PATRIMOINE MONDIAL. Un site est inscrit s\'il a une "valeur universelle exceptionnelle." En 2024 : environ 1 200 sites classes. Exemples francais : Mont-Saint-Michel, Versailles, rives de la Seine a Paris, cité de Carcassonne. Probleme : etre classe UNESCO attire du TOURISME, ce qui peut DEGRADER le site. En gros : l\'UNESCO classe les sites les plus precieux du monde. Mais la protection a un cout.' },
                    { question: 'Pourquoi proteger le patrimoine ?', answer: '1) IDENTITE : le patrimoine dit "d\'ou on vient." Detruire un monument, c\'est effacer une memoire. 2) TOURISME : les sites patrimoniaux attirent des millions de visiteurs (economie). 3) TRANSMISSION : on herite du passe pour le donner au futur. 4) EDUCATION : comprendre le passe pour comprendre le present. En gros : proteger le patrimoine = proteger qui on est.' },
                    { question: 'C\'est quoi les menaces sur le patrimoine ?', answer: 'GUERRES : destruction de Palmyre par Daech (Syrie, 2015), bombardement de sites en Ukraine. URBANISATION : construction qui detruit des quartiers historiques. TOURISME DE MASSE : erosion, pollution, degradation (Venise, Machu Picchu). CHANGEMENT CLIMATIQUE : montee des eaux, erosion, incendies (Notre-Dame 2019). PILLAGE : trafic d\'oeuvres d\'art et d\'antiquites. En gros : le patrimoine est fragile. Les menaces sont multiples et croissantes.' },
                    { question: 'C\'est quoi l\'affaire Notre-Dame (2019) ?', answer: 'Le 15 avril 2019, la cathedrale Notre-Dame de Paris prend FEU. La fleche s\'effondre. Emotion mondiale. En quelques jours, 1 MILLIARD d\'euros de dons sont reunis pour la reconstruction. Debat : reconstruire a l\'identique ou MODERNISER ? Decision : reconstruction a l\'identique. Reouverture en decembre 2024. En gros : Notre-Dame montre a quel point le patrimoine touche les gens. L\'incendie a provoque un elan de solidarite mondial.' },
                    { question: 'C\'est quoi la restitution du patrimoine ?', answer: 'De nombreuses oeuvres d\'art africaines sont dans des MUSEES EUROPEENS (Louvre, British Museum). Elles ont ete PILLEES pendant la colonisation. Les pays africains demandent leur RETOUR. En 2017, Macron annonce la restitution d\'oeuvres au Benin (bronzes d\'Abomey, restitues en 2021). Debat : faut-il rendre TOUTES les oeuvres ? Les musees europeens peuvent-ils les conserver "au nom de l\'humanite" ? En gros : qui possede le patrimoine ? Celui qui l\'a cree ou celui qui l\'a pris ?' },
                    { question: 'Patrimoine et soft power : quel lien ?', answer: 'Le SOFT POWER = influencer par la CULTURE (pas par la force). Le patrimoine est un outil de soft power : la France utilise ses musees, sa gastronomie, ses monuments pour attirer le monde. La Chine reconstruit sa Grande Muraille pour le tourisme ET le prestige national. L\'Arabie Saoudite investit dans des megaprojets culturels (AlUla, NEOM). En gros : un beau patrimoine = du prestige, du tourisme, de l\'influence. C\'est du pouvoir DOUX. Mots difficiles : "soft power" = puissance douce, influencer sans forcer (culture, image, attractivite).' }
                ],
                quiz: [
                    { question: 'Le patrimoine immateriel c\'est :', options: ['Les monuments', 'Les traditions, langues, savoir-faire', 'Les tableaux', 'Les sites naturels'], correctIndex: 1, explanation: 'Le patrimoine immateriel = ce qu\'on ne touche pas : traditions, fetes, cuisine, artisanat, langues.' },
                    { question: 'L\'UNESCO gere :', options: ['L\'armee des Nations Unies', 'La liste du patrimoine mondial', 'Le commerce international', 'Les JO'], correctIndex: 1, explanation: 'L\'UNESCO classe et protege les sites ayant une "valeur universelle exceptionnelle".' },
                    { question: 'L\'incendie de Notre-Dame a eu lieu en :', options: ['2015', '2017', '2019', '2021'], correctIndex: 2, explanation: 'Le 15 avril 2019, un incendie ravage la cathedrale. La fleche s\'effondre. Reconstruction achevee en 2024.' },
                    { question: 'La restitution du patrimoine concerne surtout :', options: ['Des oeuvres volees pendant la Revolution', 'Des oeuvres pillees pendant la colonisation', 'Des oeuvres modernes', 'Des livres anciens'], correctIndex: 1, explanation: 'De nombreux pays africains demandent le retour d\'oeuvres pillees pendant la colonisation et conservees dans des musees europeens.' },
                    { question: 'Palmyre (Syrie) a ete detruite par :', options: ['Un seisme', 'L\'armee americaine', 'Daech', 'Le gouvernement syrien'], correctIndex: 2, explanation: 'En 2015, Daech detruit deliberement des temples antiques de Palmyre, site classe UNESCO, pour des raisons ideologiques.' },
                    { question: 'Le soft power c\'est :', options: ['La force militaire', 'L\'influence par la culture et l\'attractivite', 'La pression economique', 'La cyberguerre'], correctIndex: 1, explanation: 'Le soft power (Joseph Nye) = influencer les autres par la culture, les valeurs, l\'image — sans utiliser la force.' }
                ]
            },

            // ================================================================
            // SECTION 5 : L'ENVIRONNEMENT
            // ================================================================
            {
                id: 'environnement',
                title: 'L\'environnement, entre exploitation et protection',
                icon: '\uD83C\uDF0D',
                content: '<h3>L\'environnement : exploiter ou proteger ?</h3>'
                    + '<ul>'
                    + '<li><strong>Exploitation</strong> : l\'homme utilise les ressources naturelles pour se developper</li>'
                    + '<li><strong>Protection</strong> : limiter les degats, proteger la biodiversite, lutter contre le rechauffement</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Pourquoi l\'environnement est un sujet geopolitique ?', answer: 'L\'environnement n\'est PAS qu\'un sujet de sciences. C\'est un enjeu de POUVOIR : 1) Les RESSOURCES (eau, petrole, minerais) provoquent des conflits. 2) Le RECHAUFFEMENT climatique touche plus les pays pauvres que les pays riches. 3) Les NEGOCIATIONS climatiques (COP) sont des rapports de force entre Etats. 4) La TRANSITION energetique redistribue le pouvoir (fin du petrole = fin de la puissance des pays petroliers). En gros : l\'environnement est une question de justice, de pouvoir et de survie.' },
                    { question: 'C\'est quoi les COP ?', answer: 'COP = Conference des Parties. C\'est la grande reunion ANNUELLE ou les pays negocient sur le climat. COP21 (Paris, 2015) : accord historique, objectif de limiter le rechauffement a +1.5°C / +2°C. MAIS les engagements sont VOLONTAIRES (pas de sanctions). Resultat : les emissions continuent d\'augmenter. En gros : les COP sont utiles pour mettre le climat sur la table, mais les resultats sont insuffisants. Mots difficiles : "COP" = Conference of the Parties, reunion des pays signataires de la convention climat de l\'ONU.' },
                    { question: 'C\'est quoi le rechauffement climatique ?', answer: 'La temperature moyenne de la Terre augmente a cause des GAZ A EFFET DE SERRE (CO2, methane) emis par l\'homme : industrie, transports, agriculture, deforestation. Consequences : fonte des glaces, montee des eaux, evenements extremes (canicules, inondations, ouragans), disparition d\'especes. Le GIEC (groupe d\'experts de l\'ONU) dit : si on ne fait rien, +3 a +4°C en 2100. En gros : on rend la planete plus chaude, et les consequences sont deja visibles.' },
                    { question: 'Qui est responsable du rechauffement ?', answer: 'Les pays RICHES ont emis le plus de CO2 dans l\'histoire (USA, Europe, Japon). Mais aujourd\'hui, les plus gros emetteurs sont : la CHINE (n°1), les USA (n°2), l\'INDE (n°3). Les pays PAUVRES emettent peu mais SUBISSENT le plus (montee des eaux = Bangladesh, secheresses = Sahel). C\'est une question de JUSTICE CLIMATIQUE : ceux qui polluent le moins souffrent le plus. En gros : la responsabilite est historiquement du Nord, mais les consequences touchent surtout le Sud.' },
                    { question: 'C\'est quoi la transition energetique ?', answer: 'Passer des energies FOSSILES (petrole, charbon, gaz = polluantes et finies) aux energies RENOUVELABLES (solaire, eolien, hydraulique = propres et infinies). Problemes : 1) Les pays petroliers (Arabie Saoudite, Russie) RESISTENT car leur pouvoir depend du petrole. 2) Les energies renouvelables necessitent des MINERAIS rares (lithium, cobalt) → nouveaux conflits. 3) Le NUCLEAIRE divise : propre en CO2 mais dangereux (Tchernobyl, Fukushima). En gros : changer d\'energie = changer de geopolitique.' },
                    { question: 'C\'est quoi les conflits lies a l\'eau ?', answer: 'L\'eau douce = 3% de l\'eau sur Terre. Elle est INEGALEMENT repartie. CONFLITS : le Nil (Egypte vs Ethiopie : barrage de la Renaissance, l\'Ethiopie retient l\'eau). Le Jourdain (Israel vs Jordanie vs Palestine). Le Tigre et l\'Euphrate (Turquie vs Syrie vs Irak). D\'ici 2050, 2 milliards de personnes pourraient manquer d\'eau. En gros : l\'eau est le "petrole du XXIe siecle" — source de conflits futurs. Mots difficiles : "stress hydrique" = quand un pays n\'a pas assez d\'eau pour ses besoins.' },
                    { question: 'C\'est quoi le developpement durable ?', answer: 'Concept du rapport Brundtland (1987) : "Un developpement qui repond aux besoins du present SANS compromettre la capacite des generations futures." Il repose sur 3 PILIERS : 1) ECONOMIQUE (croissance). 2) SOCIAL (egalite, education, sante). 3) ENVIRONNEMENTAL (protection de la nature). En gros : se developper OUI, mais pas n\'importe comment. Il faut penser au futur.' },
                    { question: 'C\'est quoi les Accords de Paris (2015) ?', answer: 'Lors de la COP21 a Paris, 196 pays signent un accord : limiter le rechauffement a +2°C (idealement +1.5°C). Chaque pays fixe ses propres OBJECTIFS (NDC). Les USA de Trump se retirent (2017) puis reviennent (Biden, 2021). Critique : les engagements sont NON CONTRAIGNANTS (pas de punition si on ne respecte pas). En 2024, on est sur une trajectoire de +2.5 a +3°C. En gros : un accord historique mais insuffisant. Les promesses ne sont pas tenues.' }
                ],
                quiz: [
                    { question: 'La COP21 (Paris, 2015) fixe un objectif de :', options: ['+1°C', '+1.5 a +2°C', '+3°C', '+5°C'], correctIndex: 1, explanation: 'L\'accord de Paris vise a limiter le rechauffement a +2°C, idealement +1.5°C par rapport a l\'ere preindustrielle.' },
                    { question: 'Le premier emetteur mondial de CO2 est :', options: ['Les USA', 'L\'Inde', 'La Chine', 'La Russie'], correctIndex: 2, explanation: 'La Chine est le premier emetteur de CO2 au monde, suivie des USA et de l\'Inde.' },
                    { question: 'Le concept de developpement durable date de :', options: ['1972', '1987', '2000', '2015'], correctIndex: 1, explanation: 'Le rapport Brundtland (1987) definit le developpement durable : repondre aux besoins sans compromettre le futur.' },
                    { question: 'Un conflit lie a l\'eau oppose :', options: ['France et Allemagne', 'Egypte et Ethiopie (barrage du Nil)', 'USA et Canada', 'Japon et Coree'], correctIndex: 1, explanation: 'L\'Ethiopie construit le barrage de la Renaissance sur le Nil, ce qui inquiete l\'Egypte qui depend du fleuve.' },
                    { question: 'La justice climatique signifie :', options: ['Punir les pollueurs', 'Les pays qui polluent le moins souffrent le plus du rechauffement', 'Les pays riches doivent payer', 'Tout le monde pollue egalement'], correctIndex: 1, explanation: 'La justice climatique souligne que les pays pauvres (qui emettent peu) subissent le plus les consequences du rechauffement cause par les pays riches.' },
                    { question: 'La transition energetique c\'est :', options: ['Arreter toute industrie', 'Passer des energies fossiles aux renouvelables', 'Construire plus de centrales nucleaires', 'Reduire la population'], correctIndex: 1, explanation: 'La transition energetique = passer du petrole/charbon/gaz au solaire/eolien/hydraulique pour reduire les emissions de CO2.' }
                ]
            },

            // ================================================================
            // SECTION 6 : L'ENJEU DE LA CONNAISSANCE
            // ================================================================
            {
                id: 'enjeu-connaissance',
                title: 'L\'enjeu de la connaissance',
                icon: '\uD83D\uDCA1',
                content: '<h3>Le savoir comme instrument de puissance</h3>'
                    + '<ul>'
                    + '<li><strong>La connaissance</strong> = un outil de pouvoir et d\'emancipation</li>'
                    + '<li><strong>Le cyberespace</strong> = un nouvel espace de conflits et de liberte</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Pourquoi la connaissance est un enjeu de puissance ?', answer: 'Celui qui SAIT a du POUVOIR. Exemples : 1) La bombe atomique (projet Manhattan, 1945) = le savoir scientifique donne la suprematie militaire. 2) Les BREVETS : une entreprise qui detient un brevet controle un marche (vaccins COVID, semi-conducteurs). 3) Les UNIVERSITES : attirer les meilleurs etudiants = former les futurs dirigeants (Harvard, MIT, Polytechnique). 4) L\'ESPIONNAGE : voler des secrets = gagner du pouvoir. En gros : savoir = pouvoir. Depuis toujours.' },
                    { question: 'C\'est quoi le cyberespace ?', answer: 'Le cyberespace = l\'espace NUMERIQUE cree par Internet. Ce n\'est pas un espace physique mais il a des consequences REELLES. Enjeux : 1) LIBERTE : Internet permet de s\'informer, de communiquer, de militer. 2) SURVEILLANCE : les Etats et les entreprises collectent nos DONNEES (NSA, GAFAM). 3) CONFLITS : cyberattaques, desinformation, fake news. 4) INEGALITES : la fracture numerique (tout le monde n\'a pas acces a Internet). En gros : le cyberespace est le nouveau territoire de pouvoir du XXIe siecle.' },
                    { question: 'C\'est quoi les GAFAM ?', answer: 'GAFAM = Google, Apple, Facebook (Meta), Amazon, Microsoft. Ce sont les 5 geants du NUMERIQUE americain. Leur pouvoir : ils controlent nos DONNEES, nos communications, nos achats, nos informations. Ils sont parfois plus puissants que des ETATS (le budget d\'Apple > le PIB de nombreux pays). Enjeu : faut-il les REGULER ? L\'Europe essaie avec le RGPD (2018) et le Digital Services Act (2022). En gros : les GAFAM sont devenus des superpuissances numeriques.' },
                    { question: 'C\'est quoi la desinformation ?', answer: 'La DESINFORMATION = diffuser volontairement de FAUSSES informations pour manipuler l\'opinion. Outils : les reseaux sociaux (partage viral), les bots (faux comptes automatises), les deepfakes (videos truquees par IA). Exemples : ingérence russe dans les elections americaines (2016), fake news sur le COVID (anti-vaccins). En gros : la desinformation est une ARME. Elle destabilise les democraties. Mots difficiles : "deepfake" = video truquee par intelligence artificielle, tres realiste.' },
                    { question: 'C\'est quoi la fracture numerique ?', answer: 'La FRACTURE NUMERIQUE = l\'inegalite d\'acces a Internet et aux technologies. A L\'ECHELLE MONDIALE : les pays pauvres (Afrique subsaharienne) ont peu d\'acces. A L\'ECHELLE NATIONALE : les zones rurales, les personnes agees, les pauvres sont moins connectes. Consequences : exclusion de l\'education, de l\'emploi, de l\'information. En gros : ne pas avoir Internet en 2024, c\'est etre EXCLU de la societe. Mots difficiles : "fracture" = coupure, separation. La fracture numerique SEPARE ceux qui ont acces au numerique et ceux qui ne l\'ont pas.' },
                    { question: 'C\'est quoi la guerre de l\'information ?', answer: 'Les Etats utilisent l\'INFORMATION comme arme : 1) PROPAGANDE : diffuser une vision favorable de soi-meme (Russia Today, CGTN chinoise). 2) CENSURE : bloquer l\'information (la Chine avec le "Great Firewall", la Russie qui bloque les medias occidentaux). 3) CYBERATTAQUES : pirater des systemes pour destabiliser (attaque de SolarWinds 2020). 4) INFLUENCE : manipuler les reseaux sociaux pour orienter l\'opinion. En gros : l\'information est le NERF de la guerre moderne.' },
                    { question: 'C\'est quoi le soft power du savoir ?', answer: 'Les pays utilisent l\'EDUCATION et la RECHERCHE pour rayonner : CLASSEMENTS UNIVERSITAIRES : les USA dominent (Harvard, MIT, Stanford). La France a ses Grandes Ecoles (Polytechnique, HEC, ENS). La Chine investit massivement. ECHANGES ETUDIANTS : Erasmus (Europe), bourses d\'excellence = attirer les talents. RECHERCHE : le pays qui trouve le vaccin COVID gagne en prestige. En gros : avoir les meilleures universites = attirer les meilleurs cerveaux = dominer l\'economie mondiale.' },
                    { question: 'C\'est quoi l\'intelligence artificielle comme enjeu geopolitique ?', answer: 'L\'IA est la TECHNOLOGIE qui va dominer le XXIe siecle. Course entre : USA (OpenAI, Google, Meta), CHINE (Baidu, DeepSeek), EUROPE (en retard). Enjeux : 1) MILITAIRE : drones autonomes, surveillance. 2) ECONOMIQUE : automatisation, productivite. 3) ETHIQUE : biais, surveillance de masse, emplois detruits. 4) SOUVERAINETE : dependre de l\'IA d\'un autre pays = dependance strategique. En gros : le pays qui maitrise l\'IA dominera le monde. C\'est la nouvelle course aux armements.' }
                ],
                quiz: [
                    { question: 'GAFAM signifie :', options: ['Un acronyme militaire', 'Google, Apple, Facebook, Amazon, Microsoft', 'Un accord commercial', 'Un organisme de l\'ONU'], correctIndex: 1, explanation: 'Les GAFAM sont les 5 geants du numerique americain. Leur pouvoir depasse parfois celui des Etats.' },
                    { question: 'La fracture numerique c\'est :', options: ['Une panne d\'Internet', 'L\'inegalite d\'acces au numerique', 'Un virus informatique', 'La fin d\'Internet'], correctIndex: 1, explanation: 'La fracture numerique separe ceux qui ont acces aux technologies et ceux qui en sont exclus (pays pauvres, zones rurales, personnes agees).' },
                    { question: 'Le RGPD (2018) est :', options: ['Un accord militaire', 'Un reglement europeen sur la protection des donnees personnelles', 'Un traite commercial', 'Un programme spatial'], correctIndex: 1, explanation: 'Le RGPD (Reglement General sur la Protection des Donnees) protege les donnees personnelles des citoyens europeens face aux entreprises du numerique.' },
                    { question: 'Un deepfake c\'est :', options: ['Un faux compte sur les reseaux sociaux', 'Une video truquee par intelligence artificielle', 'Un virus informatique', 'Un moteur de recherche'], correctIndex: 1, explanation: 'Un deepfake est une video ou un audio genere par IA, si realiste qu\'il est difficile de distinguer le vrai du faux.' },
                    { question: 'La course a l\'IA oppose principalement :', options: ['France et Allemagne', 'USA et Chine', 'Russie et Japon', 'Inde et Bresil'], correctIndex: 1, explanation: 'Les USA (OpenAI, Google) et la Chine (Baidu, DeepSeek) dominent la course a l\'intelligence artificielle. L\'Europe est en retard.' },
                    { question: 'Le "Great Firewall" designe :', options: ['Le mur de Trump', 'La censure d\'Internet en Chine', 'Un logiciel antivirus', 'Un pare-feu militaire'], correctIndex: 1, explanation: 'Le "Great Firewall" (jeu de mots avec la Grande Muraille) designe le systeme de censure d\'Internet mis en place par le gouvernement chinois.' },
                    { question: 'Le projet Manhattan (1945) illustre :', options: ['La construction de gratte-ciels', 'Le savoir scientifique comme arme de puissance (bombe atomique)', 'Un programme spatial', 'La fracture numerique'], correctIndex: 1, explanation: 'Le projet Manhattan (bombe atomique) montre que la connaissance scientifique donne un avantage militaire et geopolitique decisif.' }
                ]
            }
        ]
    });
})();
