// hlp.js — Donnees HLP Terminale (Humanites, Litterature et Philosophie)
// Format pedagogique adapte dys/TSA : phrases courtes, exemples concrets, mots difficiles expliques
(function() {
    if (!window.StudFlow || !window.StudFlow.subjects) return;

    window.StudFlow.subjects.register({
        id: 'hlp',
        name: 'HLP',
        icon: '\uD83D\uDCDC',
        color: 'peach',
        sections: [

            // ================================================================
            // SECTION 1 : LA RECHERCHE DE SOI
            // ================================================================
            {
                id: 'recherche-soi',
                title: 'La recherche de soi',
                icon: '\uD83E\uDDE0',
                content: '<h3>Education, transmission et emancipation</h3>'
                    + '<ul>'
                    + '<li><strong>Comment devient-on soi-meme ?</strong></li>'
                    + '<li><strong>Le role de l\'education, de la culture, des autres</strong></li>'
                    + '</ul>',
                flashcards: [
                    { question: 'C\'est quoi "la recherche de soi" en HLP ?', answer: 'C\'est une des grandes questions du programme : COMMENT on devient qui on est ? Ca touche a : l\'EDUCATION (ce qu\'on nous apprend), les EXPERIENCES (ce qu\'on vit), la CULTURE (ce qu\'on lit, regarde, ecoute), les AUTRES (famille, amis, societe). En gros : "qui suis-je ?" n\'a pas de reponse simple. On se construit tout au long de la vie.' },
                    { question: 'C\'est quoi l\'education selon Rousseau ?', answer: 'Jean-Jacques ROUSSEAU (Emile, 1762) dit : l\'homme est BON par nature, c\'est la SOCIETE qui le corrompt. L\'education doit laisser l\'enfant se developper NATURELLEMENT, par l\'EXPERIENCE et la curiosite. Pas de livres avant 12 ans ! Il doit toucher, sentir, explorer. En gros : Rousseau dit "laissez l\'enfant etre enfant." L\'education doit suivre la NATURE, pas la forcer. Mots difficiles : "corrompre" = rendre mauvais, abimer.' },
                    { question: 'C\'est quoi l\'education selon Kant ?', answer: 'KANT (Reflexions sur l\'education, 1803) dit : "L\'homme est la seule creature qui doive etre EDUQUEE." Sans education, l\'homme reste un ANIMAL. L\'education doit developper la RAISON et l\'AUTONOMIE. Etre autonome = penser par SOI-MEME, ne pas suivre les autres sans reflechir. En gros : pour Kant, l\'education = apprendre a penser seul. Mots difficiles : "autonomie" = se donner ses propres regles (auto = soi, nomos = loi).' },
                    { question: 'C\'est quoi la "culture" qui nous forme ?', answer: 'La culture = TOUT ce qui n\'est pas la nature : les livres, les films, les traditions, la langue, les valeurs. On est FORME par notre culture sans s\'en rendre compte. Exemple : un Francais et un Japonais ne pensent pas pareil, non pas parce qu\'ils sont "differents" biologiquement, mais parce que leurs CULTURES les ont formes differemment. En gros : la culture est comme des lunettes — elle change la facon dont on voit le monde.' },
                    { question: 'C\'est quoi l\'emancipation ?', answer: 'S\'EMANCIPER = se liberer d\'une tutelle, d\'une autorite, d\'un conditionnement. Exemples : l\'emancipation des FEMMES (droit de vote, 1944 en France). L\'emancipation des ESCLAVES (abolition, 1848). L\'emancipation INTELLECTUELLE (penser par soi-meme, esprit critique). En gros : s\'emanciper = devenir LIBRE. C\'est le but de l\'education selon les Lumieres. Mots difficiles : "tutelle" = autorite qui controle quelqu\'un (comme un tuteur legal).' },
                    { question: 'C\'est quoi l\'autobiographie comme recherche de soi ?', answer: 'Ecrire sur SA VIE pour COMPRENDRE qui on est. Les Confessions de Rousseau (1782) : "Je veux montrer un homme dans toute la verite de la nature." Montaigne (Essais, 1580) : "Je suis moi-meme la matiere de mon livre." L\'autobiographie = un miroir. En ecrivant, on se DECOUVRE. En gros : ecrire sur soi = se chercher soi-meme. Mots difficiles : "introspection" = regarder en soi, s\'analyser.' },
                    { question: 'Montaigne et les Essais : pourquoi c\'est important ?', answer: 'MONTAIGNE (1533-1592) ecrit les Essais = un livre ou il parle de TOUT (l\'education, la mort, l\'amitie, les cannibales) en partant de LUI-MEME. Il "s\'essaie" = il se teste, il reflechit a voix haute. Phrase celebre : "Que sais-je ?" = le doute comme methode. En gros : Montaigne invente le genre de l\'ESSAI. Il prouve qu\'on peut penser librement, sans dogme. Mots difficiles : "essai" = tentative, test. Montaigne essaie ses idees comme on essaie un vetement.' }
                ],
                quiz: [
                    { question: 'Rousseau pense que l\'homme est naturellement :', options: ['Mauvais', 'Bon', 'Indifferent', 'Rationnel'], correctIndex: 1, explanation: 'Rousseau dit que l\'homme est BON par nature et que c\'est la societe qui le corrompt.' },
                    { question: 'Pour Kant, le but de l\'education est :', options: ['Obeir aux adultes', 'Apprendre a penser par soi-meme (autonomie)', 'Devenir riche', 'Suivre la religion'], correctIndex: 1, explanation: 'Kant veut que l\'education developpe l\'autonomie = la capacite de penser et de juger par soi-meme.' },
                    { question: '"Que sais-je ?" est la devise de :', options: ['Descartes', 'Rousseau', 'Montaigne', 'Voltaire'], correctIndex: 2, explanation: 'Montaigne adopte le doute comme methode : "Que sais-je ?" invite a rester humble face a la connaissance.' },
                    { question: 'S\'emanciper signifie :', options: ['Obeir', 'Se liberer d\'une autorite', 'Se soumettre', 'Emigrer'], correctIndex: 1, explanation: 'L\'emancipation = devenir libre, sortir d\'une tutelle (intellectuelle, politique, sociale).' },
                    { question: 'Les Confessions de Rousseau sont :', options: ['Un roman', 'Une autobiographie', 'Un traite de science', 'Une piece de theatre'], correctIndex: 1, explanation: 'Rousseau ecrit sur sa propre vie pour se montrer "dans toute la verite de la nature." C\'est une autobiographie fondatrice.' }
                ]
            },

            // ================================================================
            // SECTION 2 : L'HUMANITE EN QUESTION
            // ================================================================
            {
                id: 'humanite-question',
                title: 'L\'humanite en question',
                icon: '\u2696\uFE0F',
                content: '<h3>Progres, violence et condition humaine</h3>',
                flashcards: [
                    { question: 'C\'est quoi "l\'humanite en question" en HLP ?', answer: 'Le deuxieme grand theme du programme. Questions : 1) Qu\'est-ce qui fait de nous des HUMAINS ? 2) Le PROGRES rend-il l\'homme meilleur ? 3) L\'homme est-il capable de BARBARIE ? 4) Comment vivre ENSEMBLE malgre nos differences ? En gros : ce theme interroge ce qui nous rend humains — et ce qui peut nous rendre INHUMAINS.' },
                    { question: 'C\'est quoi les Lumieres ?', answer: 'Mouvement intellectuel du XVIIIe siecle (Voltaire, Diderot, Rousseau, Montesquieu). Idees cles : la RAISON doit guider l\'homme (pas la religion ou la superstition). La TOLERANCE (accepter les differences). Le PROGRES (la science et l\'education ameliorent l\'humanite). Les DROITS DE L\'HOMME. En gros : les Lumieres = utiliser sa raison pour ameliorer le monde. Mots difficiles : "Lumieres" = en reference a la lumiere de la raison qui dissipe l\'obscurantisme (l\'ignorance).' },
                    { question: 'Le progres rend-il l\'homme meilleur ?', answer: 'POUR : les Lumieres (XVIIIe) croient au progres. La science, la medecine, l\'education ameliorent la vie. Esperance de vie : 30 ans au Moyen Age → 80 ans aujourd\'hui. CONTRE : le XXe siecle montre que le progres peut servir le MAL. La science a cree la bombe atomique, les gaz de combat, la surveillance de masse. Auschwitz = la barbarie INDUSTRIELLE. En gros : le progres technique ne garantit PAS le progres moral. On peut etre tres avance techniquement et tres cruel.' },
                    { question: 'C\'est quoi la banalite du mal (Hannah Arendt) ?', answer: 'Hannah ARENDT assiste au proces d\'EICHMANN (nazi responsable de la deportation des Juifs, Jerusalem, 1961). Elle decouvre que ce n\'est PAS un monstre mais un BUREAUCRATE banal qui "obeissait aux ordres." Elle invente le concept de "BANALITE DU MAL" : le mal n\'est pas toujours spectaculaire. Il peut etre commis par des gens ORDINAIRES qui ne pensent pas. En gros : le pire mal vient souvent de gens qui ne REFLECHISSENT PAS. Mots difficiles : "banalite" = caractere ordinaire, pas extraordinaire.' },
                    { question: 'C\'est quoi l\'humanisme ?', answer: 'L\'HUMANISME = un mouvement qui place l\'HOMME au centre. Deux sens : 1) HISTORIQUE (XVIe siecle, Renaissance) : Erasme, Rabelais, Montaigne. Retour aux textes antiques, confiance en l\'homme, education. 2) PHILOSOPHIQUE : toute pensee qui defend la dignite, la liberte et les droits de l\'etre humain. En gros : l\'humanisme = l\'homme est capable de grandeur. Il merite respect et liberte.' },
                    { question: 'C\'est quoi la Declaration des droits de l\'homme (1789) ?', answer: 'Texte fondateur de la Revolution francaise. Article 1 : "Les hommes naissent et demeurent LIBRES et EGAUX en droits." Elle affirme : la LIBERTE (d\'opinion, de religion, d\'expression), l\'EGALITE (devant la loi), la PROPRIETE, la RESISTANCE A L\'OPPRESSION. Critique : en 1789, les "hommes" = les hommes BLANCS RICHES. Les femmes, les esclaves, les pauvres sont exclus. Olympe de Gouges ecrit en 1791 la Declaration des droits de la FEMME. En gros : un texte revolutionnaire mais incomplet.' },
                    { question: 'C\'est quoi le transhumanisme ?', answer: 'Le TRANSHUMANISME = l\'idee d\'utiliser la technologie pour AMELIORER l\'etre humain. Exemples : implants cerebraux (Neuralink, Elon Musk), modification genetique, intelligence artificielle. POUR : guerir des maladies, vivre plus longtemps, augmenter les capacites. CONTRE : inegalites (seuls les riches y auront acces), perte d\'humanite, "jouer a Dieu." En gros : le transhumanisme pose LA question : jusqu\'ou peut-on modifier l\'homme sans perdre ce qui fait de nous des humains ?' },
                    { question: 'Comment les ecrivains temoignent-ils de la violence ?', answer: 'La litterature TEMOIGNE de ce que l\'homme fait subir a l\'homme : Primo LEVI (Si c\'est un homme, 1947) : temoignage des camps nazis. "Est-ce un homme, celui qui travaille dans la boue, qui ne connait pas de repos ?" Aime CESAIRE (Cahier d\'un retour au pays natal, 1939) : denonce la colonisation et le racisme. Albert CAMUS (La Peste, 1947) : allegorie du nazisme, l\'homme face au mal. En gros : la litterature dit ce que les mots ordinaires ne peuvent pas exprimer. Elle garde la MEMOIRE de la souffrance.' }
                ],
                quiz: [
                    { question: 'La "banalite du mal" selon Arendt signifie :', options: ['Le mal est toujours spectaculaire', 'Le mal peut etre commis par des gens ordinaires qui ne reflechissent pas', 'Le mal n\'existe pas', 'Seuls les monstres font le mal'], correctIndex: 1, explanation: 'Arendt montre avec le cas Eichmann que le mal peut venir de gens banals qui obeissent sans penser.' },
                    { question: 'Les Lumieres croient en :', options: ['La religion comme guide unique', 'La raison, la tolerance et le progres', 'Le retour au Moyen Age', 'L\'obeissance aux rois'], correctIndex: 1, explanation: 'Les Lumieres (XVIIIe) placent la RAISON au centre : elle eclaire l\'homme et le libere de l\'ignorance.' },
                    { question: 'L\'humanisme de la Renaissance met au centre :', options: ['Dieu', 'L\'homme', 'La nature', 'La technologie'], correctIndex: 1, explanation: 'L\'humanisme place l\'HOMME au centre de la reflexion : sa dignite, sa liberte, son education.' },
                    { question: 'Le transhumanisme veut :', options: ['Revenir a la nature', 'Ameliorer l\'humain par la technologie', 'Interdire la science', 'Supprimer les emotions'], correctIndex: 1, explanation: 'Le transhumanisme veut utiliser la technologie (IA, genetique, implants) pour depasser les limites humaines.' },
                    { question: 'Primo Levi temoigne de :', options: ['La Revolution francaise', 'Les camps de concentration nazis', 'La colonisation', 'La guerre d\'Algerie'], correctIndex: 1, explanation: 'Primo Levi, survivant d\'Auschwitz, ecrit Si c\'est un homme (1947) pour temoigner de l\'horreur des camps.' },
                    { question: 'L\'article 1 de la DDHC (1789) affirme :', options: ['La superiorite de la France', 'Les hommes naissent libres et egaux en droits', 'Le droit divin des rois', 'La liberte du commerce'], correctIndex: 1, explanation: '"Les hommes naissent et demeurent libres et egaux en droits." Texte fondateur, meme s\'il etait incomplet a l\'epoque.' },
                    { question: 'La bombe atomique illustre :', options: ['Le progres moral de l\'humanite', 'Que le progres technique ne garantit pas le progres moral', 'La superiorite de la science', 'La fin des guerres'], correctIndex: 1, explanation: 'La bombe atomique montre que la science peut servir le mal. Le progres technique n\'implique pas le progres moral.' }
                ]
            },

            // ================================================================
            // SECTION 3 : LES EXPRESSIONS DE LA SENSIBILITE
            // ================================================================
            {
                id: 'expressions-sensibilite',
                title: 'Les expressions de la sensibilite',
                icon: '\uD83C\uDFA8',
                content: '<h3>Art, litterature, emotions et sublime</h3>',
                flashcards: [
                    { question: 'C\'est quoi "les expressions de la sensibilite" en HLP ?', answer: 'C\'est un theme du programme de Terminale (semestre 1). Question centrale : COMMENT l\'homme exprime-t-il ses SENTIMENTS ? A travers : l\'ART (peinture, musique, sculpture), la LITTERATURE (poesie, roman), le CORPS (danse, cri, larmes). La sensibilite = la capacite a ressentir des emotions et a etre touche par le monde. En gros : ce theme demande comment les humains transforment leurs emotions en oeuvres.' },
                    { question: 'C\'est quoi le sublime ?', answer: 'Le SUBLIME = une emotion TRES FORTE provoquee par quelque chose de grand, de puissant, qui depasse l\'homme. Exemples : une tempete en mer, une montagne immense, un coucher de soleil grandiose. Edmund BURKE (1757) : le sublime est lie a la TERREUR et a la FASCINATION. On a peur, mais on est captive. KANT (1790) : le sublime montre que la RAISON humaine est plus grande que la nature. En gros : le sublime = quand la beaute devient ecrasante, presque effrayante. Mots difficiles : "sublime" = au-dessus de tout, qui provoque un choc emotionnel.' },
                    { question: 'C\'est quoi l\'esthetique ?', answer: 'L\'ESTHETIQUE = la branche de la philosophie qui etudie le BEAU et l\'ART. Questions : qu\'est-ce qui est beau ? Le beau est-il universel ou subjectif ? L\'art doit-il etre beau ? KANT (Critique de la faculte de juger, 1790) : le beau plait de facon DESINTERESSEE (on ne veut pas posseder l\'objet, on apprecie juste). HEGEL : l\'art est une facon pour l\'ESPRIT de se connaitre lui-meme. En gros : l\'esthetique = penser la beaute et l\'art avec des outils philosophiques.' },
                    { question: 'Beaute vs laideur dans l\'art : c\'est quoi le debat ?', answer: 'Pendant longtemps, l\'art devait etre BEAU (ideal grec, Renaissance). Puis des artistes ont montre que le LAID peut etre artistique : Victor HUGO (preface de Cromwell, 1827) : le grotesque et le sublime vont ensemble. BAUDELAIRE (Une Charogne, 1857) : un poeme sur un cadavre en decomposition → la poesie peut parler du degoutant. Art contemporain : Duchamp expose un urinoir (Fontaine, 1917). En gros : l\'art moderne dit que la beaute n\'est PAS obligatoire. L\'art peut choquer, deranger, questionner.' },
                    { question: 'C\'est quoi la sensibilite en litterature ?', answer: 'La SENSIBILITE en litterature = exprimer des EMOTIONS sinceres, intimes, profondes. Mouvement cle : le ROMANTISME (XIXe siecle). Le "moi" est au centre. On parle de ses souffrances, de ses passions. Auteurs : ROUSSEAU (Les Reveries du promeneur solitaire, 1782) : pionnier, il raconte ses emotions face a la nature. MUSSET (Nuits, 1835) : la douleur amoureuse comme source de creation. LAMARTINE ("Le Lac", 1820) : le temps qui passe et le souvenir amoureux. En gros : les Romantiques disent "mes sentiments comptent, ils MERITENT d\'etre ecrits."' },
                    { question: 'Baudelaire et la sensibilite : pourquoi c\'est cle ?', answer: 'Charles BAUDELAIRE (Les Fleurs du mal, 1857) revolutionne la poesie. Il montre que la BEAUTE peut naitre du MAL, de la laideur, de la souffrance. "Spleen" = un ennui profond, une melancolie ecrasante. Il cherche l\'IDEAL (la beaute parfaite) mais retombe toujours dans le spleen. Poemes cles : "Correspondances" (les sens se melangent), "L\'Albatros" (le poete incompris). En gros : Baudelaire = la sensibilite MODERNE. Il ose ecrire sur le mal, le deuil, la ville, la drogue. Mots difficiles : "spleen" = mot anglais pour une tristesse profonde sans raison precise.' },
                    { question: 'L\'art peut-il changer nos emotions ?', answer: 'OUI selon beaucoup de philosophes et d\'artistes : La CATHARSIS (Aristote) : le theatre PURGE les emotions. En voyant la tragedie sur scene, le spectateur libere sa peur et sa pitie. La MUSIQUE agit directement sur le corps (chair de poule, larmes, joie). Nietzsche : la musique atteint les emotions SANS passer par la raison. L\'art ENGAGE peut changer les mentalites : Guernica de Picasso (1937) denonce la guerre. En gros : l\'art ne fait pas que representer les emotions, il les PROVOQUE et peut les TRANSFORMER. Mots difficiles : "catharsis" = purification des emotions par le spectacle.' },
                    { question: 'Qu\'est-ce que le gout et peut-on le discuter ?', answer: 'Le GOUT = la capacite a juger ce qui est beau ou non. Question celebre : "des gouts et des couleurs, on ne discute pas" — VRAI ou FAUX ? HUME (1757) : le gout peut s\'EDUQUER. Certaines personnes ont un gout plus raffine (les critiques d\'art). KANT : le jugement de gout est SUBJECTIF mais pretend a l\'UNIVERSEL ("c\'est beau" = je pense que tout le monde devrait trouver ca beau). BOURDIEU (La Distinction, 1979) : le gout depend de la CLASSE SOCIALE. Les riches et les pauvres n\'aiment pas les memes choses. En gros : le gout n\'est pas naturel, il est construit par l\'education et le milieu social.' }
                ],
                quiz: [
                    { question: 'Le sublime selon Burke est lie a :', options: ['Le calme et la serenite', 'La terreur et la fascination', 'L\'humour et la legerete', 'La raison pure'], correctIndex: 1, explanation: 'Burke (1757) dit que le sublime provoque a la fois la terreur et la fascination face a la grandeur de la nature.' },
                    { question: 'Baudelaire dans Les Fleurs du mal montre que :', options: ['La poesie doit rester classique', 'La beaute peut naitre du mal et de la laideur', 'L\'art doit copier la nature', 'Le poete doit etre heureux'], correctIndex: 1, explanation: 'Baudelaire revolutionne la poesie en montrant que la beaute peut surgir du mal, de la souffrance, de la ville.' },
                    { question: 'La catharsis selon Aristote c\'est :', options: ['La creation artistique', 'La purification des emotions par le spectacle', 'Un type de peinture', 'Une technique de meditation'], correctIndex: 1, explanation: 'Pour Aristote, la tragedie purge les emotions du spectateur (peur, pitie). C\'est la catharsis.' },
                    { question: 'Pour Kant, le jugement de beaute est :', options: ['Purement objectif', 'Subjectif mais pretend a l\'universalite', 'Impossible', 'Reserve aux artistes'], correctIndex: 1, explanation: 'Kant dit que quand on juge "c\'est beau", c\'est subjectif mais on pense que tout le monde devrait etre d\'accord.' },
                    { question: 'Le "spleen" chez Baudelaire c\'est :', options: ['La joie de vivre', 'Un ennui profond et une melancolie ecrasante', 'Un style de musique', 'Un organe du corps'], correctIndex: 1, explanation: 'Le spleen = melancolie profonde, ennui existentiel. C\'est le contraire de l\'ideal que Baudelaire cherche en vain.' }
                ]
            },

            // ================================================================
            // SECTION 4 : LES METAMORPHOSES DU MOI
            // ================================================================
            {
                id: 'metamorphoses-moi',
                title: 'Les metamorphoses du moi',
                icon: '\uD83E\uDE9E',
                content: '<h3>Identite, memoire, transformations du sujet</h3>',
                flashcards: [
                    { question: 'C\'est quoi "les metamorphoses du moi" en HLP ?', answer: 'C\'est un theme du programme de Terminale (semestre 2). Question centrale : COMMENT l\'identite se TRANSFORME au fil du temps ? Le "moi" n\'est pas FIXE. Il change avec : les EXPERIENCES (voyages, rencontres, epreuves), le TEMPS (on n\'est pas la meme personne a 15 ans et a 40 ans), les AUTRES (les regards, les relations nous modifient), la MEMOIRE (nos souvenirs construisent qui on est). En gros : "je" est un autre, comme dit Rimbaud. L\'identite est un processus, pas un etat.' },
                    { question: 'C\'est quoi la memoire et l\'identite chez Proust ?', answer: 'Marcel PROUST (A la recherche du temps perdu, 1913-1927). Idee cle : la MEMOIRE INVOLONTAIRE. En goutant une madeleine trempee dans du the, le narrateur retrouve tout son PASSE (souvenirs d\'enfance). La memoire volontaire (chercher a se souvenir) ne marche pas bien. C\'est la memoire INVOLONTAIRE (un gout, une odeur, un son) qui fait revenir le passe dans toute sa richesse. En gros : nos souvenirs font ce que nous sommes. Proust montre que le passe n\'est jamais totalement perdu. Mots difficiles : "memoire involontaire" = un souvenir qui revient tout seul, sans qu\'on le cherche.' },
                    { question: 'C\'est quoi la duree chez Bergson ?', answer: 'Henri BERGSON (Essai sur les donnees immediates de la conscience, 1889). Le temps VECU (la "duree") est different du temps de l\'HORLOGE. Quand on s\'ennuie, 5 minutes durent une heure. Quand on s\'amuse, une heure passe en 5 minutes. Notre MOI profond vit dans cette duree, pas dans le temps mesurable. Le moi est un FLUX continu, comme une melodie : chaque note colore les suivantes. En gros : pour Bergson, le "moi" est un mouvement continu, pas une chose fixe. Mots difficiles : "duree" (chez Bergson) = le temps tel qu\'on le ressent interieurement.' },
                    { question: 'C\'est quoi l\'autobiographie et l\'autofiction ?', answer: 'AUTOBIOGRAPHIE = ecrire SA PROPRE vie en disant la VERITE. Pacte autobiographique (Philippe LEJEUNE) : l\'auteur promet de dire vrai. Exemples : Rousseau (Les Confessions), Sartre (Les Mots). AUTOFICTION = melanger sa vie reelle avec de la FICTION. Le "je" du texte ressemble a l\'auteur mais il invente aussi. Terme invente par Serge DOUBROVSKY (Fils, 1977). Annie ERNAUX (Les Annees, 2008) : elle raconte sa vie a travers la memoire collective (photos, objets, evenements). En gros : l\'autobiographie dit "voici ma vie telle qu\'elle fut." L\'autofiction dit "voici ma vie reinventee."' },
                    { question: 'Annie Ernaux : pourquoi c\'est important ?', answer: 'Annie ERNAUX (Prix Nobel 2022). Elle ecrit sur sa vie mais de facon SOCIALE : elle montre comment son identite a ete formee par sa CLASSE SOCIALE (famille ouvriere), son GENRE (femme dans une societe patriarcale), son EPOQUE (les annees 60-70). Oeuvres cles : La Place (1983) = la mort de son pere, le fossé entre elle (intellectuelle) et lui (ouvrier). Les Annees (2008) = une autobiographie IMPERSONNELLE, elle dit "elle" au lieu de "je." En gros : Ernaux montre que le "moi" est aussi un produit de la societe. Mots difficiles : "transfuge de classe" = quelqu\'un qui change de classe sociale (comme Ernaux, d\'ouvriere a intellectuelle).' },
                    { question: 'Le moi a l\'ere du numerique : quels enjeux ?', answer: 'Le NUMERIQUE transforme l\'identite : les RESEAUX SOCIAUX creent un "moi" public, une image construite (selfies, filtres, stories). L\'AVATAR = une identite virtuelle qui peut etre tres differente du moi reel. Le CYBERHARCÉLEMENT peut detruire l\'image de soi. L\'oubli est devenu IMPOSSIBLE (tout reste sur Internet). Questions philosophiques : le moi en ligne est-il un "vrai" moi ? La multiplication des profils fragmente-t-elle l\'identite ? En gros : le numerique permet de se REINVENTER mais aussi de se PERDRE. L\'identite devient un SPECTACLE permanent.' },
                    { question: 'Genre et identite : c\'est quoi le debat ?', answer: 'La question du GENRE interroge : l\'identite est-elle determinee par la BIOLOGIE ou par la CULTURE ? Simone de BEAUVOIR (Le Deuxieme Sexe, 1949) : "On ne nait pas femme, on le devient." Le genre est une CONSTRUCTION SOCIALE (ce que la societe attend d\'un homme ou d\'une femme). Judith BUTLER (Trouble dans le genre, 1990) : le genre est une PERFORMANCE, un role qu\'on joue. Debat actuel : identites non-binaires, transidentite, questionnement des normes. En gros : le genre n\'est pas seulement biologique, il est aussi construit par la societe et les normes.' },
                    { question: 'Rimbaud : "Je est un autre" — qu\'est-ce que ca veut dire ?', answer: 'Arthur RIMBAUD ecrit en 1871 (a 16 ans !) : "Je est un autre." C\'est une phrase REVOLUTIONNAIRE. Elle signifie : le "moi" n\'est pas unitaire, il n\'est pas simple. Il y a en nous des forces, des pensees, des emotions qui nous DEPASSENT. Le poete ne CONTROLE pas son inspiration : quelque chose parle A TRAVERS lui. Lien avec la PSYCHANALYSE (Freud) : l\'inconscient montre que le moi ne se connait pas lui-meme. En gros : on croit se connaitre, mais une partie de nous nous echappe toujours.' }
                ],
                quiz: [
                    { question: 'La "madeleine de Proust" illustre :', options: ['La cuisine francaise', 'La memoire involontaire declenchee par une sensation', 'Une recette de patisserie', 'La memoire volontaire'], correctIndex: 1, explanation: 'Chez Proust, une sensation (le gout de la madeleine) declenche involontairement un flot de souvenirs oublies.' },
                    { question: 'L\'autofiction est un genre invente par :', options: ['Proust', 'Ernaux', 'Doubrovsky', 'Rousseau'], correctIndex: 2, explanation: 'Serge Doubrovsky invente le terme "autofiction" avec son roman Fils (1977) : melange de vie reelle et de fiction.' },
                    { question: '"On ne nait pas femme, on le devient" est de :', options: ['Judith Butler', 'Simone de Beauvoir', 'Annie Ernaux', 'Virginia Woolf'], correctIndex: 1, explanation: 'Simone de Beauvoir ecrit cette phrase dans Le Deuxieme Sexe (1949). Le genre est une construction sociale, pas seulement biologique.' },
                    { question: 'Pour Bergson, la "duree" c\'est :', options: ['Le temps de l\'horloge', 'Le temps vecu et ressenti interieurement', 'La duree d\'un film', 'Le temps objectif de la physique'], correctIndex: 1, explanation: 'Bergson distingue le temps mesurable (horloge) de la duree = le temps tel qu\'on le VIT (subjectif, continu, qualitatif).' },
                    { question: '"Je est un autre" est une phrase de :', options: ['Baudelaire', 'Rimbaud', 'Proust', 'Sartre'], correctIndex: 1, explanation: 'Rimbaud ecrit "Je est un autre" en 1871. Le moi n\'est pas simple ni transparent : des forces inconscientes nous traversent.' }
                ]
            }
        ]
    });
})();
