// quizbac1.js — Quiz Bac Francais : Poesie & Mouvements (4 sections, 100 quiz)
(function() {
    if (!window.StudFlow || !window.StudFlow.subjects) return;

    window.StudFlow.subjects.register({
        id: 'quizbac1',
        name: 'Quiz Bac : Poesie & Mouvements',
        icon: '\uD83C\uDFAF',
        color: 'accent',
        sections: [
            {
                id: 'poesie',
                title: 'La Poesie',
                icon: '\u270F\uFE0F',
                content: '<h3>Versification et metrique</h3>'
                    + '<ul>'
                    + '<li><strong>L\'alexandrin</strong> : vers de 12 syllabes, le plus noble de la poesie francaise. Il comporte une cesure a l\'hemistiche (6/6). Hugo en libere la structure avec le trimetre romantique (4/4/4).</li>'
                    + '<li><strong>L\'octosyllabe</strong> : vers de 8 syllabes, frequent dans la poesie medievale et les chansons. Plus leger et rapide que l\'alexandrin.</li>'
                    + '<li><strong>Le decasyllabe</strong> : vers de 10 syllabes, dominant dans la poesie medievale (cesure 4/6 ou 6/4). Utilise par Ronsard avant la generalisation de l\'alexandrin.</li>'
                    + '<li><strong>La cesure</strong> : pause rythmique a l\'interieur du vers. Dans l\'alexandrin classique, elle se situe apres la 6e syllabe et delimite deux hemistiches egaux.</li>'
                    + '<li><strong>L\'enjambement</strong> : la phrase deborde d\'un vers sur le suivant sans pause syntaxique. Le rejet isole un element court au debut du vers suivant ; le contre-rejet anticipe un element a la fin du vers precedent.</li>'
                    + '</ul>'
                    + '<h3>Rimes et sonorites</h3>'
                    + '<ul>'
                    + '<li><strong>Rime plate (AABB)</strong> : deux vers consecutifs riment ensemble. Frequente dans le theatre classique et les fables.</li>'
                    + '<li><strong>Rime croisee (ABAB)</strong> : les rimes alternent. Disposition courante dans le quatrain lyrique.</li>'
                    + '<li><strong>Rime embrassee (ABBA)</strong> : les rimes s\'encadrent. Disposition typique du sonnet dans les quatrains.</li>'
                    + '<li><strong>Qualite de la rime</strong> : pauvre (1 son commun), suffisante (2 sons), riche (3 sons ou plus).</li>'
                    + '</ul>'
                    + '<h3>Formes poetiques fixes</h3>'
                    + '<ul>'
                    + '<li><strong>Le sonnet</strong> : 14 vers en 2 quatrains + 2 tercets. Importe d\'Italie par la Pleiade (Petrarque). La chute (dernier vers) porte la pointe du poeme.</li>'
                    + '<li><strong>La ballade</strong> : 3 strophes + 1 envoi, avec un refrain. Forme medievale pratiquee par Villon et Charles d\'Orleans.</li>'
                    + '<li><strong>Le rondeau</strong> : poeme a forme circulaire avec reprise du premier vers. Forme medievale legere.</li>'
                    + '<li><strong>L\'ode</strong> : poeme lyrique de ton eleve, souvent compose de strophes regulieres. Ronsard et Du Bellay la pratiquent dans la tradition de Pindare et Horace.</li>'
                    + '<li><strong>Le vers libre</strong> : vers affranchi de la metrique reguliere, sans rime obligatoire. Inaugure par Rimbaud et Laforgue, developpe au XXe siecle.</li>'
                    + '<li><strong>Le poeme en prose</strong> : texte poetique sans vers ni rime. Aloysius Bertrand (Gaspard de la Nuit) en est le precurseur, Baudelaire le consacre avec Le Spleen de Paris.</li>'
                    + '</ul>'
                    + '<h3>Grands mouvements poetiques</h3>'
                    + '<ul>'
                    + '<li><strong>La Pleiade (1549-1570)</strong> : groupe de sept poetes (Ronsard, Du Bellay) qui enrichissent la langue francaise et imitent les modeles antiques. Manifeste : Defense et Illustration de la langue francaise (1549).</li>'
                    + '<li><strong>Le Parnasse (1866-1876)</strong> : mouvement pronant "l\'art pour l\'art", la perfection formelle et l\'impersonnalite. Chefs de file : Leconte de Lisle, Heredia, Gautier.</li>'
                    + '<li><strong>Le symbolisme (1886)</strong> : mouvement qui privilegie la suggestion, la musicalite et le symbole plutot que la description directe. Verlaine, Rimbaud, Mallarme en sont les figures majeures.</li>'
                    + '<li><strong>Le surrealisme (1924)</strong> : mouvement fonde par Breton qui explore l\'inconscient, le reve et l\'ecriture automatique. Poetes : Eluard, Aragon, Desnos.</li>'
                    + '</ul>'
                    + '<h3>Fonctions de la poesie</h3>'
                    + '<ul>'
                    + '<li><strong>Fonction lyrique</strong> : expression des sentiments personnels (amour, deuil, melancolie). Du Bellay, Lamartine, Eluard.</li>'
                    + '<li><strong>Fonction engagee</strong> : la poesie comme arme politique et sociale. Hugo (Les Chatiments), Eluard (Liberte), Prevert.</li>'
                    + '<li><strong>Fonction descriptive</strong> : celebration de la beaute du monde. Parnassiens, Ponge (Le Parti pris des choses).</li>'
                    + '<li><strong>Fonction experimentale</strong> : travail sur le langage et les formes. Apollinaire (calligrammes), Queneau (Oulipo).</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Qu\'est-ce qu\'un alexandrin et comment se structure-t-il ?', answer: 'L\'alexandrin est un vers de 12 syllabes, le plus prestigieux de la poesie francaise classique. Il comporte une cesure a l\'hemistiche, le divisant en deux groupes de 6 syllabes (6/6). Victor Hugo innove avec le trimetre romantique (4/4/4).' },
                    { question: 'Quelle est la difference entre rime plate, croisee et embrassee ?', answer: 'La rime plate suit le schema AABB (deux vers consecutifs riment). La rime croisee alterne selon le schema ABAB. La rime embrassee encadre selon le schema ABBA. Le sonnet classique utilise des rimes embrassees dans les quatrains.' },
                    { question: 'Qu\'est-ce que la Pleiade et quel est son manifeste ?', answer: 'La Pleiade est un groupe de sept poetes du XVIe siecle, mene par Ronsard et Du Bellay. Leur manifeste est la Defense et Illustration de la langue francaise (1549) de Du Bellay, qui prone l\'enrichissement du francais et l\'imitation des modeles antiques.' },
                    { question: 'Quelle est la structure du sonnet ?', answer: 'Le sonnet se compose de 14 vers repartis en deux quatrains (ABBA ABBA) et deux tercets (CCD EDE ou CCD EED). La "chute" ou "pointe" se situe dans le dernier vers. Cette forme a ete importee d\'Italie au XVIe siecle par la Pleiade.' },
                    { question: 'Qu\'est-ce que le symbolisme en poesie ?', answer: 'Le symbolisme est un mouvement poetique ne vers 1886 qui refuse la description directe du reel au profit de la suggestion, de la musicalite et du symbole. Verlaine prone la "musique avant toute chose", Mallarme cultive l\'hermetisme et Rimbaud la voyance.' },
                    { question: 'Quelle difference entre enjambement, rejet et contre-rejet ?', answer: 'L\'enjambement est le debordement de la phrase d\'un vers sur le suivant. Le rejet est le cas ou un element bref est rejete au debut du vers suivant, le mettant en relief. Le contre-rejet anticipe un element du vers suivant a la fin du vers precedent.' },
                    { question: 'Qu\'est-ce que le Parnasse et sa doctrine ?', answer: 'Le Parnasse (vers 1866) est un mouvement pronant "l\'art pour l\'art" : la poesie recherche la beaute formelle, la perfection technique et l\'impersonnalite. Les poetes parnassiens (Leconte de Lisle, Heredia, Gautier) rejettent le lyrisme sentimental romantique.' },
                    { question: 'Qui est considere comme le pere du poeme en prose ?', answer: 'Aloysius Bertrand est le precurseur du poeme en prose avec Gaspard de la Nuit (1842). Baudelaire consacre le genre avec Le Spleen de Paris (1869), recueil de "petits poemes en prose" inspires de la vie moderne parisienne.' },
                    { question: 'Qu\'est-ce que l\'ecriture automatique surrealiste ?', answer: 'L\'ecriture automatique est une technique definie par Andre Breton dans le Manifeste du surrealisme (1924). Elle consiste a ecrire sans controle de la raison, sans preoccupation esthetique, pour laisser l\'inconscient s\'exprimer librement, hors de toute censure morale.' },
                    { question: 'Quelles sont les quatre grandes fonctions de la poesie ?', answer: 'La poesie assume une fonction lyrique (expression des sentiments), engagee (combat politique et social), descriptive (celebration du monde visible) et experimentale (exploration du langage). Un meme poete peut exercer plusieurs de ces fonctions.' }
                ],
                quiz: [
                    // correctIndex: 0 (6 total: q1, q5, q10, q14, q21, q24)
                    // correctIndex: 1 (6 total: q2, q6, q9, q16, q18, q22)
                    // correctIndex: 2 (7 total: q3, q7, q11, q13, q17, q19, q23)
                    // correctIndex: 3 (6 total: q4, q8, q12, q15, q20, q25)
                    { question: 'Combien de syllabes compte un alexandrin ?', options: ['12 syllabes', '10 syllabes', '8 syllabes', '14 syllabes'], correctIndex: 0, explanation: 'L\'alexandrin est un vers de 12 syllabes, divise en deux hemistiches de 6 syllabes par la cesure.' },
                    { question: 'Qui a ecrit la Defense et Illustration de la langue francaise (1549) ?', options: ['Ronsard', 'Du Bellay', 'Montaigne', 'Marot'], correctIndex: 1, explanation: 'Joachim Du Bellay publie ce manifeste en 1549, programme de la Pleiade pour enrichir la langue francaise en imitant les Anciens.' },
                    { question: 'Quel est le schema de rimes embrassees ?', options: ['AABB', 'ABAB', 'ABBA', 'ABCD'], correctIndex: 2, explanation: 'Les rimes embrassees suivent le schema ABBA, ou le premier vers rime avec le quatrieme et le deuxieme avec le troisieme.' },
                    { question: 'Qui a fonde le surrealisme avec le Manifeste de 1924 ?', options: ['Eluard', 'Aragon', 'Apollinaire', 'Breton'], correctIndex: 3, explanation: 'Andre Breton publie le Manifeste du surrealisme en 1924, definissant l\'ecriture automatique et l\'exploration de l\'inconscient.' },
                    { question: 'Quel mouvement poetique prone "l\'art pour l\'art" ?', options: ['Le Parnasse', 'Le symbolisme', 'Le romantisme', 'Le surrealisme'], correctIndex: 0, explanation: 'Le Parnasse, avec Leconte de Lisle et Heredia, defend la perfection formelle et l\'impersonnalite contre le lyrisme romantique.' },
                    { question: 'Quelle figure consiste a prolonger la phrase au-dela de la fin du vers ?', options: ['La cesure', 'L\'enjambement', 'L\'anaphore', 'L\'alliteration'], correctIndex: 1, explanation: 'L\'enjambement est le debordement syntaxique d\'un vers sur le suivant, rompant la concordance entre metre et syntaxe.' },
                    { question: 'Quel poete a ecrit le recueil Les Fleurs du mal (1857) ?', options: ['Verlaine', 'Rimbaud', 'Baudelaire', 'Mallarme'], correctIndex: 2, explanation: 'Charles Baudelaire publie Les Fleurs du mal en 1857, recueil condamne pour outrage aux bonnes moeurs. Il fonde la modernite poetique.' },
                    { question: 'Quel poete surrealiste a ecrit Liberte (1942), poeme de la Resistance ?', options: ['Aragon', 'Breton', 'Desnos', 'Eluard'], correctIndex: 3, explanation: 'Paul Eluard ecrit Liberte en 1942, poeme engage parachute par la RAF sur la France occupee, devenu symbole de la Resistance.' },
                    { question: 'Le vers "Je fais souvent ce reve etrange et penetrant" de Verlaine est un :', options: ['Decasyllabe', 'Alexandrin', 'Octosyllabe', 'Vers libre'], correctIndex: 1, explanation: 'Ce vers celebre de Mon reve familier (Poemes saturniens) compte 12 syllabes, c\'est un alexandrin classique.' },
                    { question: 'Quel procede consiste a repeter un mot en debut de vers ?', options: ['L\'anaphore', 'L\'alliteration', 'L\'assonance', 'La paronomase'], correctIndex: 0, explanation: 'L\'anaphore est la repetition d\'un meme mot ou groupe de mots en debut de vers ou de phrase, creant un effet d\'insistance.' },
                    { question: 'Quelle est la structure classique du sonnet ?', options: ['3 quatrains + 1 distique', '4 tercets + 1 distique', '2 quatrains + 2 tercets', '2 sizains + 1 distique'], correctIndex: 2, explanation: 'Le sonnet regulier se compose de deux quatrains (4+4 vers) et deux tercets (3+3 vers), soit 14 vers au total.' },
                    { question: 'Qu\'est-ce qu\'un calligramme ?', options: ['Un poeme sans ponctuation', 'Un poeme en prose illustre', 'Un acrostiche decoratif', 'Un poeme dont les vers forment un dessin'], correctIndex: 3, explanation: 'Le calligramme, invente par Apollinaire (Calligrammes, 1918), est un poeme dont la disposition graphique des mots dessine l\'objet evoque.' },
                    { question: 'Quel poete est l\'auteur des Contemplations (1856) ?', options: ['Lamartine', 'Musset', 'Hugo', 'Vigny'], correctIndex: 2, explanation: 'Victor Hugo publie Les Contemplations en 1856, recueil divise en "Autrefois" et "Aujourd\'hui" autour de la mort de sa fille Leopoldine.' },
                    { question: 'Quelle est la cesure classique de l\'alexandrin ?', options: ['Apres la 6e syllabe', 'Apres la 5e syllabe', 'Apres la 4e syllabe', 'Apres la 8e syllabe'], correctIndex: 0, explanation: 'Dans l\'alexandrin classique, la cesure tombe apres la 6e syllabe, partageant le vers en deux hemistiches egaux de 6 syllabes.' },
                    { question: 'Quelle forme poetique medievale comporte 3 strophes, un envoi et un refrain ?', options: ['Le rondeau', 'Le sonnet', 'L\'ode', 'La ballade'], correctIndex: 3, explanation: 'La ballade medievale se compose de trois strophes et d\'un envoi, avec un refrain repete a la fin de chaque strophe. Villon en est le maitre.' },
                    { question: 'Rimbaud dans sa Lettre du voyant (1871) affirme que le poete doit :', options: ['Imiter les Anciens', 'Se faire voyant par un dereglement de tous les sens', 'Respecter la metrique classique', 'Cultiver l\'impersonnalite'], correctIndex: 1, explanation: 'Rimbaud theorise la poesie comme exploration de l\'inconnu par un "long, immense et raisonne dereglement de tous les sens".' },
                    { question: 'Quel poete du Parnasse a ecrit les Trophees (1893), recueil de sonnets ?', options: ['Leconte de Lisle', 'Gautier', 'Heredia', 'Banville'], correctIndex: 2, explanation: 'Jose-Maria de Heredia publie Les Trophees en 1893, recueil de 118 sonnets d\'une perfection formelle exemplaire, chef-d\'oeuvre du Parnasse.' },
                    { question: 'Qu\'appelle-t-on un "rejet" en versification ?', options: ['Le retour a la rime initiale', 'Un element bref rejete au debut du vers suivant', 'La suppression d\'une syllabe', 'Le refrain d\'une ballade'], correctIndex: 1, explanation: 'Le rejet est un type d\'enjambement ou un mot ou groupe bref est repousse au debut du vers suivant, le mettant en valeur.' },
                    { question: 'Verlaine ecrit dans son Art poetique (1884) : "De la musique avant toute chose". A quel mouvement se rattache-t-il ?', options: ['Le Parnasse', 'Le romantisme', 'Le symbolisme', 'Le surrealisme'], correctIndex: 2, explanation: 'Verlaine est un poete symboliste qui privilegie la musicalite, la suggestion et l\'impression plutot que la description precise.' },
                    { question: 'Quel recueil de Baudelaire a fonde le poeme en prose moderne ?', options: ['Les Fleurs du mal', 'Les Paradis artificiels', 'Curiosites esthetiques', 'Le Spleen de Paris'], correctIndex: 3, explanation: 'Le Spleen de Paris (1869), sous-titre Petits poemes en prose, consacre le genre du poeme en prose en le liant a la vie urbaine moderne.' },
                    { question: 'Quel poete a ecrit Le Parti pris des choses (1942) ?', options: ['Ponge', 'Prevert', 'Char', 'Michaux'], correctIndex: 0, explanation: 'Francis Ponge publie Le Parti pris des choses en 1942, recueil ou il decrit des objets quotidiens (galet, pain, huitre) avec une precision poetique.' },
                    { question: 'Quel poete a invente le terme "surrealisme" en 1917 ?', options: ['Breton', 'Apollinaire', 'Tzara', 'Eluard'], correctIndex: 1, explanation: 'Guillaume Apollinaire forge le mot "surrealisme" en 1917 pour qualifier sa piece Les Mamelles de Tiresias. Breton reprend le terme en 1924.' },
                    { question: 'Le sonnet "Heureux qui, comme Ulysse, a fait un beau voyage" est de :', options: ['Ronsard', 'Marot', 'Du Bellay', 'Montaigne'], correctIndex: 2, explanation: 'Ce sonnet celebre figure dans Les Regrets (1558) de Du Bellay, recueil ecrit pendant son sejour desenchante a Rome.' },
                    { question: 'Qu\'est-ce qu\'une rime riche ?', options: ['Une rime portant sur au moins 3 sons communs', 'Une rime sur un seul son vocalique', 'Une rime entre un mot rare et un mot courant', 'Une rime sur 2 sons communs'], correctIndex: 0, explanation: 'Une rime est riche quand elle porte sur trois phonemes ou plus en commun (ex : "tendresse"/"ivresse"). La rime pauvre n\'a qu\'un son, la suffisante en a deux.' },
                    { question: 'Quel poeme de Ronsard commence par "Mignonne, allons voir si la rose" ?', options: ['Les Amours', 'Sonnets pour Helene', 'Hymnes', 'Odes'], correctIndex: 3, explanation: 'Ce celebre poeme figure dans les Odes (1550-1552) de Ronsard. Il illustre le theme du carpe diem en comparant la beaute feminine a la fragilite de la rose.' }
                ]
            },
            {
                id: 'lumieres',
                title: 'Le Siecle des Lumieres',
                icon: '\uD83D\uDD6F\uFE0F',
                content: '<h3>Les philosophes des Lumieres</h3>'
                    + '<ul>'
                    + '<li><strong>Voltaire (1694-1778)</strong> : philosophe, ecrivain et polemiste. Defenseur de la tolerance et de la liberte d\'expression. Auteur de Candide, Traite sur la tolerance, Lettres philosophiques. Symbole de l\'esprit critique des Lumieres.</li>'
                    + '<li><strong>Rousseau (1712-1778)</strong> : philosophe genevois, auteur du Contrat social et d\'Emile. Il prone la souverainete du peuple et une education naturelle. Sa pensee influence la Revolution francaise.</li>'
                    + '<li><strong>Montesquieu (1689-1755)</strong> : magistrat et philosophe. Auteur des Lettres persanes (1721) et de De l\'esprit des lois (1748), ou il theorise la separation des pouvoirs legislatif, executif et judiciaire.</li>'
                    + '<li><strong>Diderot (1713-1784)</strong> : philosophe et encyclopediste. Directeur de l\'Encyclopedie avec d\'Alembert. Auteur de Jacques le fataliste, Le Neveu de Rameau, Supplement au Voyage de Bougainville.</li>'
                    + '<li><strong>Beaumarchais (1732-1799)</strong> : dramaturge et homme d\'affaires. Le Mariage de Figaro (1784) critique les privileges de la noblesse et annonce la Revolution.</li>'
                    + '<li><strong>Condorcet (1743-1794)</strong> : mathematicien et philosophe. Defenseur de l\'instruction publique, du droit des femmes et de l\'abolition de l\'esclavage. Auteur de l\'Esquisse d\'un tableau historique des progres de l\'esprit humain.</li>'
                    + '</ul>'
                    + '<h3>Concepts fondamentaux</h3>'
                    + '<ul>'
                    + '<li><strong>La raison</strong> : instrument principal de connaissance, opposee aux superstitions, aux prejuges et au fanatisme religieux.</li>'
                    + '<li><strong>Le progres</strong> : croyance en l\'amelioration continue de la condition humaine grace aux sciences, aux arts et a l\'education.</li>'
                    + '<li><strong>La tolerance</strong> : respect de la liberte de pensee, de croyance et d\'expression. Voltaire en est le champion ("Ecrasez l\'infame").</li>'
                    + '<li><strong>Le droit naturel</strong> : droits inherents a tout etre humain (liberte, egalite, propriete), anterieurs aux lois positives.</li>'
                    + '<li><strong>Le contrat social</strong> : theorie selon laquelle la legitimite politique repose sur un pacte entre les citoyens (Rousseau, Locke).</li>'
                    + '<li><strong>La separation des pouvoirs</strong> : principe theorise par Montesquieu pour eviter le despotisme : pouvoir legislatif, executif et judiciaire doivent etre distincts.</li>'
                    + '</ul>'
                    + '<h3>Formes litteraires des Lumieres</h3>'
                    + '<ul>'
                    + '<li><strong>Le conte philosophique</strong> : recit fictif, souvent ironique, qui illustre une these philosophique. Voltaire excelle dans ce genre (Candide, Zadig, Micromegas).</li>'
                    + '<li><strong>L\'essai</strong> : texte argumentatif ou l\'auteur expose ses idees de facon personnelle et libre.</li>'
                    + '<li><strong>Le roman epistolaire</strong> : roman compose de lettres. Montesquieu (Lettres persanes), Laclos (Les Liaisons dangereuses).</li>'
                    + '<li><strong>L\'article d\'encyclopedie</strong> : texte didactique et critique visant a diffuser le savoir et a combattre les prejuges.</li>'
                    + '<li><strong>Le dialogue philosophique</strong> : confrontation d\'idees entre personnages fictifs. Diderot (Le Neveu de Rameau, Supplement au Voyage de Bougainville).</li>'
                    + '</ul>'
                    + '<h3>Contexte historique</h3>'
                    + '<ul>'
                    + '<li><strong>L\'Ancien Regime</strong> : monarchie absolue, societe d\'ordres (clerge, noblesse, tiers etat), privileges et inegalites.</li>'
                    + '<li><strong>La censure</strong> : controle royal sur les publications. L\'Encyclopedie est interdite a deux reprises. Voltaire est emprisonne a la Bastille et exile.</li>'
                    + '<li><strong>Les salons</strong> : lieux de sociabilite intellectuelle tenus par des femmes de la noblesse ou de la bourgeoisie, ou se diffusent les idees nouvelles.</li>'
                    + '<li><strong>La Revolution (1789)</strong> : aboutissement politique des idees des Lumieres : Declaration des droits de l\'homme et du citoyen, abolition des privileges.</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Qu\'est-ce que le conte philosophique et qui en est le maitre ?', answer: 'Le conte philosophique est un recit fictif, souvent bref et ironique, qui sert a illustrer une these philosophique. Voltaire en est le maitre inconteste avec Candide (critique de l\'optimisme), Zadig et Micromegas. Le genre mele fiction divertissante et reflexion critique.' },
                    { question: 'Qu\'est-ce que la separation des pouvoirs selon Montesquieu ?', answer: 'Montesquieu theorise dans De l\'esprit des lois (1748) que le pouvoir politique doit etre divise en trois branches distinctes : legislatif (faire les lois), executif (les appliquer) et judiciaire (juger). Cette separation previent le despotisme et garantit la liberte.' },
                    { question: 'Quel est le projet de l\'Encyclopedie de Diderot et d\'Alembert ?', answer: 'L\'Encyclopedie (1751-1772) est un dictionnaire raisonne des sciences, des arts et des metiers en 28 volumes. Son objectif est de rassembler et diffuser l\'ensemble des connaissances humaines pour combattre l\'ignorance, les prejuges et le fanatisme.' },
                    { question: 'Quelle est la these de Rousseau dans Du contrat social (1762) ?', answer: 'Rousseau affirme que la legitimite politique repose sur un pacte entre les citoyens, qui alienent leur liberte naturelle au profit de la volonte generale. Le peuple est souverain et la loi est l\'expression de la volonte generale. Toute autorite illegitime releve de la tyrannie.' },
                    { question: 'Que denonce Voltaire dans Candide (1759) ?', answer: 'Voltaire denonce l\'optimisme philosophique de Leibniz (represente par Pangloss : "tout est pour le mieux dans le meilleur des mondes possibles") face a la realite du mal : guerres, tremblements de terre, esclavage, fanatisme. La conclusion prone l\'action : "il faut cultiver notre jardin".' },
                    { question: 'Qu\'est-ce que le despotisme eclaire ?', answer: 'Le despotisme eclaire est un mode de gouvernement ou un monarque absolu s\'inspire des idees des Lumieres pour reformer son Etat (progres, education, tolerance) sans partager le pouvoir. Exemples : Frederic II de Prusse, Catherine II de Russie, avec qui Voltaire et Diderot correspondaient.' },
                    { question: 'Quel role jouent les salons au XVIIIe siecle ?', answer: 'Les salons sont des lieux de sociabilite intellectuelle tenus par des femmes de la noblesse ou de la haute bourgeoisie. Philosophes, ecrivains et artistes s\'y retrouvent pour debattre des idees nouvelles. Ils contribuent a la diffusion des Lumieres en dehors des institutions officielles.' },
                    { question: 'Quel est le stratageme narratif des Lettres persanes de Montesquieu ?', answer: 'Montesquieu fait decouvrir la France a deux voyageurs persans fictifs, Usbek et Rica, qui echangent des lettres. Le regard etranger permet de denoncer les travers de la societe francaise (monarchie absolue, fanatisme, injustices) par l\'ironie et le decentrement culturel.' },
                    { question: 'Pourquoi l\'Encyclopedie a-t-elle ete censuree ?', answer: 'L\'Encyclopedie a ete interdite a deux reprises (1752 et 1759) par le pouvoir royal et l\'Eglise. Ses articles remettaient en cause les dogmes religieux, critiquaient l\'absolutisme et diffusaient des idees jugees subversives. Malesherbes, directeur de la Librairie, en a secretement protege la publication.' },
                    { question: 'Qu\'est-ce que le droit naturel pour les philosophes des Lumieres ?', answer: 'Le droit naturel designe les droits inherents a tout etre humain en vertu de sa nature : liberte, egalite, propriete, surete. Ces droits sont anterieurs et superieurs aux lois positives. Les Lumieres les opposent aux privileges de naissance et a l\'arbitraire royal.' }
                ],
                quiz: [
                    // correctIndex: 0 (6 total: q1, q6, q10, q15, q21, q24)
                    // correctIndex: 1 (6 total: q2, q7, q11, q16, q19, q22)
                    // correctIndex: 2 (7 total: q3, q8, q12, q17, q20, q23, q25)
                    // correctIndex: 3 (6 total: q4, q5, q9, q13, q14, q18)
                    { question: 'Quel philosophe est l\'auteur de Candide (1759) ?', options: ['Voltaire', 'Rousseau', 'Diderot', 'Montesquieu'], correctIndex: 0, explanation: 'Voltaire publie Candide en 1759, conte philosophique qui satirise l\'optimisme de Leibniz a travers les aventures desastreuses du heros.' },
                    { question: 'Quel ouvrage monumental Diderot et d\'Alembert ont-ils dirige ?', options: ['Le Dictionnaire philosophique', 'L\'Encyclopedie', 'Le Contrat social', 'Les Lettres philosophiques'], correctIndex: 1, explanation: 'L\'Encyclopedie (1751-1772) est un dictionnaire raisonne des sciences, des arts et des metiers en 28 volumes, synthese des savoirs des Lumieres.' },
                    { question: 'Qui theorise la separation des pouvoirs dans De l\'esprit des lois (1748) ?', options: ['Voltaire', 'Rousseau', 'Montesquieu', 'Diderot'], correctIndex: 2, explanation: 'Montesquieu distingue les pouvoirs legislatif, executif et judiciaire dans De l\'esprit des lois, principe fondateur des democraties modernes.' },
                    { question: 'Dans les Lettres persanes, Montesquieu utilise le regard etranger pour :', options: ['Celebrer la monarchie francaise', 'Raconter un voyage reel en Perse', 'Comparer les religions monotheistes', 'Denoncer les travers de la societe francaise par l\'ironie'], correctIndex: 3, explanation: 'Le regard naif de voyageurs persans permet a Montesquieu de critiquer la societe francaise (religion, politique, moeurs) par le procede de la defamiliarisation.' },
                    { question: 'Quelle est la conclusion de Candide de Voltaire ?', options: ['Le bonheur est dans la foi', 'La nature est bonne', 'La raison gouverne le monde', 'Il faut cultiver notre jardin'], correctIndex: 3, explanation: '"Il faut cultiver notre jardin" est la morale pragmatique de Candide : plutot que de philosopher, il faut agir concretement et travailler.' },
                    { question: 'Le contrat social de Rousseau affirme que la souverainete appartient :', options: ['Au peuple', 'Au monarque eclaire', 'A l\'aristocratie', 'Aux philosophes'], correctIndex: 0, explanation: 'Rousseau pose que le peuple est le seul souverain legitime, et que la loi doit etre l\'expression de la volonte generale des citoyens.' },
                    { question: 'Quel genre litteraire Voltaire a-t-il porte a sa perfection ?', options: ['Le roman epistolaire', 'Le conte philosophique', 'Le dialogue des morts', 'L\'autobiographie'], correctIndex: 1, explanation: 'Voltaire est le maitre du conte philosophique, recit court et ironique illustrant une these (Candide, Zadig, Micromegas, L\'Ingenu).' },
                    { question: 'La devise implicite des Lumieres selon Kant est :', options: ['Egalite, liberte, fraternite', 'Cogito ergo sum (Je pense donc je suis)', 'Sapere aude (Ose savoir)', 'Connais-toi toi-meme'], correctIndex: 2, explanation: 'Kant definit les Lumieres dans son essai de 1784 par la devise "Sapere aude" : aie le courage de te servir de ton propre entendement.' },
                    { question: 'Quel philosophe defend l\'education naturelle de l\'enfant dans Emile (1762) ?', options: ['Voltaire', 'Diderot', 'Condorcet', 'Rousseau'], correctIndex: 3, explanation: 'Rousseau dans Emile ou De l\'education prone une education respectant la nature de l\'enfant, loin des contraintes sociales et de la corruption urbaine.' },
                    { question: 'Comment s\'appelle le procede ou un auteur feint l\'ignorance pour mieux critiquer ?', options: ['L\'ironie socratique', 'L\'antiphrase', 'La litote', 'L\'euphemisme'], correctIndex: 0, explanation: 'L\'ironie socratique consiste a feindre la naivete pour pousser l\'interlocuteur a reveler ses contradictions. Voltaire l\'utilise abondamment.' },
                    { question: 'Quel philosophe des Lumieres a ete emprisonne a la Bastille ?', options: ['Montesquieu', 'Voltaire', 'Rousseau', 'Condorcet'], correctIndex: 1, explanation: 'Voltaire est emprisonne a la Bastille en 1717-1718 pour des ecrits satiriques contre le Regent, puis une seconde fois en 1726 avant son exil en Angleterre.' },
                    { question: 'Quelle oeuvre de Diderot est un dialogue philosophique sur le determinisme et la liberte ?', options: ['Le Neveu de Rameau', 'La Religieuse', 'Jacques le fataliste', 'Le Reve de d\'Alembert'], correctIndex: 2, explanation: 'Jacques le fataliste et son maitre interroge, a travers un recit picaresque, la question du determinisme : "Tout est ecrit la-haut" repete Jacques.' },
                    { question: 'Que signifie "Ecrasez l\'infame", formule celebre de Voltaire ?', options: ['Renversez la monarchie', 'Eliminez la pauvrete', 'Detruisez l\'Encyclopedie rivale', 'Combattez le fanatisme et la superstition'], correctIndex: 3, explanation: '"L\'infame" designe pour Voltaire le fanatisme religieux, l\'intolerance et la superstition. Cette formule est son cri de guerre philosophique.' },
                    { question: 'Quel texte de Voltaire plaide pour la liberte de conscience apres l\'affaire Calas ?', options: ['Candide', 'Lettres philosophiques', 'Dictionnaire philosophique', 'Traite sur la tolerance'], correctIndex: 3, explanation: 'Le Traite sur la tolerance (1763) est ecrit par Voltaire pour defendre Jean Calas, protestant injustement condamne, et plaider pour la tolerance religieuse.' },
                    { question: 'Quel philosophe defend les droits des femmes et l\'abolition de l\'esclavage ?', options: ['Condorcet', 'Voltaire', 'Diderot', 'Montesquieu'], correctIndex: 0, explanation: 'Condorcet est l\'un des premiers a defendre le droit de vote des femmes et l\'abolition de l\'esclavage, positions tres avancees pour son epoque.' },
                    { question: 'Comment Voltaire critique-t-il l\'esclavage dans Candide ?', options: ['Par une comparaison avec l\'Antiquite', 'Par le recit poignant du negre de Surinam', 'Par un dialogue entre maitres et esclaves', 'Par un discours philosophique abstrait'], correctIndex: 1, explanation: 'L\'episode du negre de Surinam (chapitre 19) est un moment celebre ou un esclave mutile denonce le prix humain du sucre, demolissant l\'optimisme de Pangloss.' },
                    { question: 'Les Lettres philosophiques de Voltaire (1734) font l\'eloge de quel pays ?', options: ['La Prusse', 'La Hollande', 'L\'Angleterre', 'La Suisse'], correctIndex: 2, explanation: 'Les Lettres philosophiques (ou Lettres anglaises) font l\'eloge de la tolerance religieuse, de la liberte politique et du commerce en Angleterre, critiquant implicitement la France.' },
                    { question: 'Quel ouvrage de Rousseau commence par "L\'homme est ne libre, et partout il est dans les fers" ?', options: ['Emile', 'Les Confessions', 'Discours sur l\'inegalite', 'Du contrat social'], correctIndex: 3, explanation: 'Cette phrase celebre ouvre Du contrat social (1762) de Rousseau, ou il pose les fondements de la souverainete populaire et de la volonte generale.' },
                    { question: 'L\'Encyclopedie est sous-titree :', options: ['Dictionnaire universel des arts', 'Dictionnaire raisonne des sciences, des arts et des metiers', 'Somme philosophique du siecle', 'Recueil critique des savoirs humains'], correctIndex: 1, explanation: 'Le titre complet est "Encyclopedie, ou Dictionnaire raisonne des sciences, des arts et des metiers", soulignant sa vocation systematique et critique.' },
                    { question: 'Quel est le role de Pangloss dans Candide ?', options: ['Le heros principal', 'Le serviteur fidele', 'Le maitre optimiste qui repete que tout est pour le mieux', 'Le sage qui guide Candide vers la verite'], correctIndex: 2, explanation: 'Pangloss est la caricature du philosophe optimiste leibnizien. Malgre les catastrophes, il maintient que "tout est pour le mieux dans le meilleur des mondes possibles".' },
                    { question: 'Quel type de regard Montesquieu utilise-t-il dans les Lettres persanes pour produire un effet critique ?', options: ['Le regard etranger qui defamiliarise', 'Le regard retrospectif d\'un historien', 'Le regard scientifique d\'un naturaliste', 'Le regard prophetique d\'un visionnaire'], correctIndex: 0, explanation: 'Le regard naif de Persans decouvrant la France permet de rendre etranges et ridicules des pratiques habituelles, procedant par defamiliarisation satirique.' },
                    { question: 'Beaumarchais, dans Le Mariage de Figaro, fait dire a Figaro dans son monologue de l\'acte V :', options: ['Que la noblesse est juste et necessaire', 'Que le comte n\'a fait que se donner la peine de naitre', 'Que la Revolution est inevitable', 'Qu\'il faut obeir aux maitres'], correctIndex: 1, explanation: 'Figaro lance : "Vous vous etes donne la peine de naitre, et rien de plus." Cette critique des privileges de naissance annonce les idees revolutionnaires.' },
                    { question: 'Quelle oeuvre de Rousseau est consideree comme la premiere autobiographie moderne ?', options: ['Du contrat social', 'Emile', 'Les Confessions', 'Les Reveries du promeneur solitaire'], correctIndex: 2, explanation: 'Les Confessions (publiees en 1782-1789) inaugurent l\'autobiographie moderne par leur projet de transparence absolue : "Je veux montrer a mes semblables un homme dans toute la verite de la nature".' },
                    { question: 'Quel philosophe a entretenu une correspondance celebre avec Frederic II de Prusse ?', options: ['Voltaire', 'Rousseau', 'Montesquieu', 'Diderot'], correctIndex: 0, explanation: 'Voltaire entretient une longue correspondance et un sejour chez Frederic II de Prusse (1750-1753), incarnation du despotisme eclaire.' },
                    { question: 'Dans le Supplement au Voyage de Bougainville, Diderot oppose :', options: ['La foi et la raison', 'La monarchie et la republique', 'L\'etat de nature et la civilisation europeenne', 'Les anciens et les modernes'], correctIndex: 2, explanation: 'Diderot oppose la liberte naturelle des Tahitiens a la civilisation europeenne corrompue, questionnant la colonisation et les moeurs sexuelles occidentales.' }
                ]
            },
            {
                id: 'romantisme',
                title: 'Le Romantisme',
                icon: '\uD83C\uDF39',
                content: '<h3>Les grands auteurs romantiques</h3>'
                    + '<ul>'
                    + '<li><strong>Victor Hugo (1802-1885)</strong> : figure majeure du romantisme francais. Poete (Les Contemplations, Les Chatiments), dramaturge (Hernani, Ruy Blas), romancier (Les Miserables, Notre-Dame de Paris). Il theorise le drame romantique dans la Preface de Cromwell (1827).</li>'
                    + '<li><strong>Alphonse de Lamartine (1790-1869)</strong> : premier grand poete romantique francais. Les Meditations poetiques (1820) inaugurent le lyrisme romantique. "Le Lac" est son poeme le plus celebre.</li>'
                    + '<li><strong>Alfred de Musset (1810-1857)</strong> : poete et dramaturge du "mal du siecle". Auteur des Nuits, de Lorenzaccio, de La Confession d\'un enfant du siecle. Sa liaison tumultueuse avec George Sand marque son oeuvre.</li>'
                    + '<li><strong>Alfred de Vigny (1797-1863)</strong> : poete et romancier, incarnation du romantisme aristocratique et philosophique. Auteur de Stello, Chatterton, Les Destinees. Theme de la solitude du genie.</li>'
                    + '<li><strong>Chateaubriand (1768-1848)</strong> : precurseur du romantisme avec Rene (1802) et Le Genie du christianisme. Les Memoires d\'outre-tombe sont son chef-d\'oeuvre autobiographique.</li>'
                    + '<li><strong>Gerard de Nerval (1808-1855)</strong> : poete onirique, auteur des Chimeres, de Sylvie et des Filles du feu. Il explore le reve, la folie et le souvenir a la frontiere du romantisme et du symbolisme.</li>'
                    + '<li><strong>Theophile Gautier (1811-1872)</strong> : passe du romantisme au Parnasse. Auteur de Mademoiselle de Maupin et d\'Emaux et Camees. Il lance la formule "l\'art pour l\'art".</li>'
                    + '<li><strong>George Sand (1804-1876)</strong> : romanciere engagee, feministe avant l\'heure. Auteur d\'Indiana, de La Mare au diable. Elle defend la liberte des femmes et les classes populaires.</li>'
                    + '</ul>'
                    + '<h3>Themes romantiques</h3>'
                    + '<ul>'
                    + '<li><strong>Le mal du siecle</strong> : sentiment de melancolie, de desillusion et d\'ennui qui frappe la jeunesse post-napoleonienne, privee de grands ideaux. Musset en fait la theorie dans La Confession d\'un enfant du siecle (1836).</li>'
                    + '<li><strong>La nature-refuge</strong> : la nature comme miroir de l\'ame, lieu de consolation et de communion. Lamartine au lac du Bourget, Hugo dans la campagne normande.</li>'
                    + '<li><strong>La passion</strong> : l\'amour absolu, devorant, impossible. Musset et Sand, Hernani et Dona Sol, Quasimodo et Esmeralda.</li>'
                    + '<li><strong>La revolte</strong> : refus des conventions sociales, de la mediocrite bourgeoise. Le heros romantique est un marginal, un exile, un revolte.</li>'
                    + '<li><strong>Le lyrisme personnel</strong> : l\'expression du "moi" intime, des sentiments et des emotions. "Ah ! frappe-toi le coeur, c\'est la qu\'est le genie" (Musset).</li>'
                    + '</ul>'
                    + '<h3>Principes et manifestes</h3>'
                    + '<ul>'
                    + '<li><strong>La Preface de Cromwell (1827)</strong> : manifeste du drame romantique par Hugo. Melange du grotesque et du sublime, rejet des unites classiques, liberte en art.</li>'
                    + '<li><strong>Racine et Shakespeare (1823-1825)</strong> : Stendhal defend le romantisme comme "l\'art de presenter aux peuples les oeuvres litteraires qui sont susceptibles de leur donner le plus de plaisir possible dans l\'etat actuel de leurs habitudes".</li>'
                    + '<li><strong>La bataille d\'Hernani (1830)</strong> : premiere de la piece de Hugo a la Comedie-Francaise, qui oppose violemment partisans du classicisme et jeunes romantiques menes par Gautier.</li>'
                    + '</ul>'
                    + '<h3>Contexte historique</h3>'
                    + '<ul>'
                    + '<li><strong>Post-Revolution et Empire</strong> : la generation romantique grandit dans le desenchantement qui suit la chute de Napoleon (1815).</li>'
                    + '<li><strong>Restauration et monarchie de Juillet</strong> : le romantisme s\'epanouit entre 1820 et 1850, periode de bouleversements politiques (revolutions de 1830 et 1848).</li>'
                    + '<li><strong>Engagement politique</strong> : Hugo evolue du royalisme au republicanisme. Lamartine est chef du gouvernement provisoire en 1848.</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Qu\'est-ce que le "mal du siecle" romantique ?', answer: 'Le mal du siecle est un sentiment de melancolie, de vide existentiel et de desillusion qui touche la jeunesse francaise apres la chute de Napoleon. Prives de grandes causes, les jeunes gens sombrent dans l\'ennui et le desespoir. Musset en fait le diagnostic dans La Confession d\'un enfant du siecle (1836).' },
                    { question: 'Quel est le contenu de la Preface de Cromwell de Hugo (1827) ?', answer: 'Hugo y theorise le drame romantique : melange du grotesque et du sublime, rejet des trois unites classiques, liberte totale de creation. Il prone un theatre qui reflite la totalite du reel, sans les contraintes artificielles du classicisme. C\'est le manifeste du romantisme theatral.' },
                    { question: 'Qu\'est-ce que la bataille d\'Hernani (1830) ?', answer: 'La premiere d\'Hernani de Hugo a la Comedie-Francaise le 25 fevrier 1830 provoque un affrontement entre classiques (partisans des regles) et romantiques (jeunes artistes, dont Gautier en gilet rouge). C\'est la victoire symbolique du romantisme au theatre.' },
                    { question: 'Pourquoi Lamartine est-il considere comme le fondateur du lyrisme romantique ?', answer: 'Les Meditations poetiques (1820) de Lamartine inaugurent le romantisme en poesie. Le poeme "Le Lac" exprime la fuite du temps et le souvenir amoureux dans un cadre naturel. Pour la premiere fois, un poete dit "je" avec une sincerite emotionnelle totale.' },
                    { question: 'Qui est le precurseur du romantisme francais avec Rene (1802) ?', answer: 'Chateaubriand est le precurseur du romantisme francais. Son court recit Rene (1802) met en scene un jeune homme en proie au "vague des passions", melancolie indefinissable qui deviendra le mal du siecle. Le Genie du christianisme rehabilite le sentiment religieux.' },
                    { question: 'Quel est le theme central de Lorenzaccio de Musset ?', answer: 'Lorenzaccio (1834) traite de l\'impossibilite de l\'action politique et morale. Lorenzo de Medicis s\'est corrompu en feignant la debauche pour approcher le tyran Alexandre. Son assassinat s\'avere inutile car le peuple ne se revolte pas. C\'est un drame de la desillusion politique.' },
                    { question: 'Comment la nature fonctionne-t-elle dans la poesie romantique ?', answer: 'La nature romantique est un miroir de l\'ame du poete : elle reflete ses emotions, ses joies et ses tourments. Elle est aussi un refuge contre la societe. Le lac de Lamartine, la campagne de Hugo, les paysages de Nerval sont des projections du "moi" interieur sur le monde exterieur.' },
                    { question: 'Quelle est la particularite du romantisme de Nerval ?', answer: 'Nerval explore les territoires du reve, de la folie et du souvenir avec une intensite unique. Les Chimeres (sonnets hermetiques) et Les Filles du feu melent mythologie personnelle et references esoteriques. Il se situe a la frontiere du romantisme et du symbolisme, annoncant la poesie moderne.' },
                    { question: 'Quel est l\'engagement politique de Victor Hugo ?', answer: 'Hugo evolue du royalisme au republicanisme. Elu depute en 1848, il s\'oppose au coup d\'Etat de Napoleon III (1851) et s\'exile pendant 19 ans a Jersey puis Guernesey. Les Chatiments (1853) attaquent le tyran. Il incarne l\'ecrivain engage, defenseur des opprimes et de la Republique.' },
                    { question: 'Comment Stendhal definit-il le romantisme dans Racine et Shakespeare ?', answer: 'Stendhal definit le romantisme comme l\'art qui correspond aux gouts et aux besoins du public contemporain, par opposition au classicisme qui imite des modeles perimes. Le romantique est moderne, le classique est desuet. Il prone une litterature vivante, adaptee a son epoque.' }
                ],
                quiz: [
                    // correctIndex: 0 (6 total: q1, q5, q9, q14, q19, q22)
                    // correctIndex: 1 (6 total: q2, q6, q10, q16, q20, q24)
                    // correctIndex: 2 (7 total: q3, q7, q11, q15, q17, q21, q25)
                    // correctIndex: 3 (6 total: q4, q8, q12, q13, q18, q23)
                    { question: 'Quel recueil de Lamartine est considere comme l\'acte de naissance du romantisme poetique francais ?', options: ['Les Meditations poetiques', 'Les Destinees', 'Les Contemplations', 'Les Nuits'], correctIndex: 0, explanation: 'Les Meditations poetiques (1820) de Lamartine inaugurent le lyrisme romantique en France avec des poemes comme "Le Lac".' },
                    { question: 'La Preface de Cromwell (1827) est un manifeste de :', options: ['Stendhal', 'Hugo', 'Lamartine', 'Musset'], correctIndex: 1, explanation: 'Victor Hugo theorise dans la Preface de Cromwell le drame romantique : melange du grotesque et du sublime, rejet des regles classiques.' },
                    { question: 'Quel evenement de 1830 symbolise la victoire du romantisme au theatre ?', options: ['La revolution de Juillet', 'La publication de Rene', 'La bataille d\'Hernani', 'La mort de Chateaubriand'], correctIndex: 2, explanation: 'La premiere d\'Hernani de Hugo le 25 fevrier 1830 provoque un affrontement legendaire entre classiques et romantiques a la Comedie-Francaise.' },
                    { question: 'Qui a theorise le "mal du siecle" dans La Confession d\'un enfant du siecle ?', options: ['Hugo', 'Chateaubriand', 'Vigny', 'Musset'], correctIndex: 3, explanation: 'Musset analyse dans La Confession d\'un enfant du siecle (1836) la melancolie de la generation post-napoleonienne, privee de grands ideaux.' },
                    { question: 'Quel roman de Chateaubriand met en scene un heros melancolique precurseur du romantisme ?', options: ['Rene', 'Les Memoires d\'outre-tombe', 'Atala', 'Le Genie du christianisme'], correctIndex: 0, explanation: 'Rene (1802) presente un jeune homme en proie au "vague des passions", prefigurant le mal du siecle romantique.' },
                    { question: 'Les Contemplations de Hugo (1856) sont divisees en deux parties articulees autour de :', options: ['La Revolution de 1848', 'La mort de sa fille Leopoldine', 'Son exil a Guernesey', 'La bataille d\'Hernani'], correctIndex: 1, explanation: 'Les Contemplations se divisent en "Autrefois" (1830-1843) et "Aujourd\'hui" (1843-1856), la cesure etant la noyade de Leopoldine le 4 septembre 1843.' },
                    { question: 'Quel poeme de Lamartine evoque la fuite du temps au bord du lac du Bourget ?', options: ['L\'Isolement', 'Le Vallon', 'Le Lac', 'L\'Automne'], correctIndex: 2, explanation: '"Le Lac" (Meditations poetiques, 1820) est une elegie ou le poete implore le temps de suspendre son vol au souvenir d\'un amour perdu.' },
                    { question: 'Quelle romanciere romantique defend la liberte des femmes dans Indiana (1832) ?', options: ['Madame de Stael', 'Louise Colet', 'Delphine de Girardin', 'George Sand'], correctIndex: 3, explanation: 'George Sand, dans Indiana (1832), denonce la condition des femmes dans le mariage et revendique leur droit a la passion et a la liberte.' },
                    { question: 'Le drame romantique selon Hugo melange :', options: ['Le grotesque et le sublime', 'Vers et prose exclusivement', 'La tragedie grecque et la farce', 'Le recit et le dialogue'], correctIndex: 0, explanation: 'Hugo theorise dans la Preface de Cromwell le melange du grotesque (laid, comique) et du sublime (beau, noble) pour representer la totalite du reel.' },
                    { question: 'Quel poete romantique a ecrit Les Chimeres, sonnets hermetiques proches du symbolisme ?', options: ['Musset', 'Nerval', 'Gautier', 'Vigny'], correctIndex: 1, explanation: 'Gerard de Nerval publie Les Chimeres (1854), sonnets enigmatiques melant mythologie, reve et folie, qui annoncent le symbolisme.' },
                    { question: 'Dans Ruy Blas de Hugo, le heros est un :', options: ['Noble deguise en valet', 'Roi en exil', 'Valet amoureux de la reine d\'Espagne', 'Bouffon de cour philosophe'], correctIndex: 2, explanation: 'Ruy Blas est un valet qui, par un stratageme, accede au pouvoir et tombe amoureux de la reine d\'Espagne, illustrant le melange des conditions sociales cher a Hugo.' },
                    { question: 'Theophile Gautier a lance la formule :', options: ['Le genie est une longue patience', 'Je est un autre', 'Ah frappe-toi le coeur c\'est la qu\'est le genie', 'L\'art pour l\'art'], correctIndex: 3, explanation: 'Gautier formule "l\'art pour l\'art" dans la preface de Mademoiselle de Maupin (1835), refusant toute utilite morale ou sociale a l\'art.' },
                    { question: 'Quel recueil de Hugo attaque Napoleon III apres le coup d\'Etat de 1851 ?', options: ['Les Contemplations', 'La Legende des siecles', 'Les Orientales', 'Les Chatiments'], correctIndex: 3, explanation: 'Les Chatiments (1853) sont un recueil de poesie satirique et vengeresse ecrit en exil, ou Hugo denonce "Napoleon le petit" et la tyrannie.' },
                    { question: 'Qui a ecrit Stello (1832), roman sur la condition maudite du poete ?', options: ['Vigny', 'Hugo', 'Musset', 'Lamartine'], correctIndex: 0, explanation: 'Alfred de Vigny dans Stello illustre par trois exemples historiques la these que le poete est toujours incompris et persecute par la societe.' },
                    { question: 'Quel poeme de Musset commence par "Les plus desesperes sont les chants les plus beaux" ?', options: ['Nuit de decembre', 'Nuit d\'octobre', 'Nuit de mai', 'Nuit d\'aout'], correctIndex: 2, explanation: 'La Nuit de mai (1835) contient ce vers celebre, dialogue entre le Poete et la Muse sur la souffrance creatrice.' },
                    { question: 'Stendhal, dans Racine et Shakespeare, definit le romantisme comme :', options: ['L\'imitation des modeles grecs et latins', 'L\'art qui presente au public ce qui lui donne le plus de plaisir dans l\'etat actuel de ses habitudes', 'Le melange du grotesque et du sublime', 'La primaute du sentiment sur la raison'], correctIndex: 1, explanation: 'Stendhal propose une definition pragmatique : est romantique ce qui est moderne et adapte aux gouts contemporains, par opposition au classicisme desuet.' },
                    { question: 'Quel poete romantique portait un gilet rouge a la premiere d\'Hernani ?', options: ['Musset', 'Nerval', 'Gautier', 'Vigny'], correctIndex: 2, explanation: 'Theophile Gautier arbora un celebre gilet rouge lors de la bataille d\'Hernani (1830), devenu symbole de la provocation romantique.' },
                    { question: 'Les Memoires d\'outre-tombe de Chateaubriand sont un genre :', options: ['Epistolaire', 'Romanesque', 'Dramatique', 'Autobiographique'], correctIndex: 3, explanation: 'Les Memoires d\'outre-tombe (publication posthume 1849-1850) sont le chef-d\'oeuvre autobiographique de Chateaubriand, somme de sa vie et de son epoque.' },
                    { question: 'Quel theme est central dans "Le Lac" de Lamartine ?', options: ['La fuite irreversible du temps', 'La revolte politique', 'L\'exotisme oriental', 'La solitude du genie'], correctIndex: 0, explanation: '"Le Lac" est une meditation sur le temps qui passe et l\'amour ephemere. Le poete implore la nature de garder la memoire du bonheur perdu.' },
                    { question: 'Lorenzaccio de Musset se deroule dans quelle ville ?', options: ['Paris', 'Florence', 'Venise', 'Rome'], correctIndex: 1, explanation: 'Lorenzaccio (1834) se passe a Florence sous la tyrannie d\'Alexandre de Medicis, que Lorenzo projette d\'assassiner.' },
                    { question: 'Hugo en exil a ecrit depuis :', options: ['Londres et Bruxelles', 'Geneve et Lausanne', 'Jersey et Guernesey', 'Bruxelles et Berlin'], correctIndex: 2, explanation: 'Hugo s\'exile apres le coup d\'Etat de 1851, d\'abord a Jersey (1852-1855) puis a Guernesey (1855-1870), ou il ecrit Les Chatiments, Les Contemplations et Les Miserables.' },
                    { question: 'Quel est le sens du "vague des passions" chez Chateaubriand ?', options: ['Un malaise indefini, desir sans objet precis', 'L\'instabilite amoureuse', 'La nostalgie de la monarchie', 'L\'attrait pour les voyages lointains'], correctIndex: 0, explanation: 'Le "vague des passions" est un etat d\'ame indefini, un desir sans objet precis, une melancolie que Chateaubriand decrit dans Le Genie du christianisme et illustre dans Rene.' },
                    { question: 'Quel courant succede au romantisme dans la seconde moitie du XIXe siecle ?', options: ['Le surrealisme', 'Le classicisme', 'Le dadaisme', 'Le realisme'], correctIndex: 3, explanation: 'Le realisme (Balzac, Flaubert, Stendhal) succede au romantisme vers 1850, en pronant une representation objective et fidele de la societe contemporaine.' },
                    { question: 'Quel personnage de Hugo incarne la misere et la redemption dans Les Miserables ?', options: ['Hernani', 'Jean Valjean', 'Ruy Blas', 'Quasimodo'], correctIndex: 1, explanation: 'Jean Valjean, ancien bagnard, incarne le theme hugolien de la redemption par la bonte. Les Miserables (1862) est le grand roman social de Hugo.' },
                    { question: 'Mademoiselle de Maupin de Gautier (1835) est celebre pour :', options: ['Son lyrisme melancolique', 'Sa peinture realiste du peuple', 'Sa preface pronant l\'art pour l\'art', 'Sa critique de la monarchie'], correctIndex: 2, explanation: 'La preface de Mademoiselle de Maupin (1835) est un texte fondateur de la doctrine de l\'art pour l\'art, rejetant toute fonction utilitaire de la litterature.' }
                ]
            },
            {
                id: 'realnat',
                title: 'Realisme & Naturalisme',
                icon: '\uD83C\uDFED',
                content: '<h3>Les auteurs realistes</h3>'
                    + '<ul>'
                    + '<li><strong>Honore de Balzac (1799-1850)</strong> : auteur de La Comedie humaine, ensemble de plus de 90 romans et nouvelles qui dressent un panorama complet de la societe francaise. Le Pere Goriot, Eugenie Grandet, Illusions perdues. Il invente le retour des personnages d\'un roman a l\'autre.</li>'
                    + '<li><strong>Stendhal (1783-1842)</strong> : romancier de l\'ambition et de l\'analyse psychologique. Le Rouge et le Noir (1830), La Chartreuse de Parme (1839). Il definit le roman comme "un miroir qui se promene le long d\'un chemin".</li>'
                    + '<li><strong>Gustave Flaubert (1821-1880)</strong> : maitre du style impersonnel et du mot juste. Madame Bovary (1857), L\'Education sentimentale (1869), Salammbo. Il est juge pour "outrage a la morale publique" apres Madame Bovary.</li>'
                    + '<li><strong>Guy de Maupassant (1850-1893)</strong> : nouvelliste et romancier, disciple de Flaubert. Boule de Suif (1880), Bel-Ami (1885), Une Vie (1883), Le Horla. Maitre de la nouvelle realiste et fantastique.</li>'
                    + '</ul>'
                    + '<h3>Les auteurs naturalistes</h3>'
                    + '<ul>'
                    + '<li><strong>Emile Zola (1840-1902)</strong> : chef de file du naturalisme. Auteur des Rougon-Macquart, cycle de 20 romans qui etudie une famille sous le Second Empire. Germinal, L\'Assommoir, Nana, Au Bonheur des Dames. Il theorise le roman experimental dans Le Roman experimental (1880).</li>'
                    + '<li><strong>Les freres Goncourt</strong> : Edmond (1822-1896) et Jules (1830-1870). Romanciers et chroniqueurs, ils fondent l\'Academie Goncourt. Germinie Lacerteux (1865) est un roman naturaliste avant la lettre.</li>'
                    + '<li><strong>Joris-Karl Huysmans (1848-1907)</strong> : d\'abord naturaliste (Les Soeurs Vatard), il rompt avec le mouvement dans A rebours (1884), roman decadent qui influencera les symbolistes.</li>'
                    + '</ul>'
                    + '<h3>Concepts et methodes</h3>'
                    + '<ul>'
                    + '<li><strong>La mimesis</strong> : representation fidele du reel. Le roman realiste vise a "faire concurrence a l\'etat civil" (Balzac).</li>'
                    + '<li><strong>Le milieu social</strong> : l\'individu est determine par son environnement social, economique et familial. Le roman analyse les rapports entre l\'individu et la societe.</li>'
                    + '<li><strong>Le type</strong> : personnage representatif d\'une categorie sociale (l\'avare, le parvenu, la bourgeoise de province). Balzac peint des types qui transcendent l\'individuel.</li>'
                    + '<li><strong>Le roman experimental</strong> : Zola applique la methode scientifique au roman. L\'ecrivain observe, hypothese et verifie, comme un medecin (Claude Bernard). Le naturalisme etudie l\'heredite et le milieu.</li>'
                    + '<li><strong>Le determinisme</strong> : doctrine selon laquelle le comportement humain est determine par l\'heredite biologique et le milieu social. C\'est le fondement scientifique du naturalisme.</li>'
                    + '</ul>'
                    + '<h3>Techniques narratives</h3>'
                    + '<ul>'
                    + '<li><strong>La description balzacienne</strong> : longues descriptions detaillees des lieux et des personnages, revelant leur condition sociale et leur psychologie. La pension Vauquer dans Le Pere Goriot en est l\'exemple canonique.</li>'
                    + '<li><strong>Le style impersonnel de Flaubert</strong> : l\'auteur s\'efface derriere son recit, evitant tout jugement moral explicite. "L\'artiste doit etre dans son oeuvre comme Dieu dans la creation, invisible et tout-puissant."</li>'
                    + '<li><strong>Le discours indirect libre</strong> : technique narrative qui mele la voix du narrateur et les pensees du personnage sans marqueurs explicites. Flaubert en est le maitre.</li>'
                    + '<li><strong>La documentation de Zola</strong> : Zola se documente minutieusement avant chaque roman (descente dans les mines pour Germinal, enquete aux Halles pour Le Ventre de Paris), methode quasi journalistique.</li>'
                    + '</ul>'
                    + '<h3>Oeuvres cles</h3>'
                    + '<ul>'
                    + '<li><strong>Madame Bovary (1857)</strong> : Emma Bovary, femme d\'un medecin de campagne, reve d\'une vie romanesque et se perd dans l\'adultere et les dettes. Chef-d\'oeuvre du realisme par sa precision stylistique.</li>'
                    + '<li><strong>Germinal (1885)</strong> : roman de la condition ouvriere dans les mines du Nord. Etienne Lantier decouvre la misere et mene une greve. Le roman le plus engage de Zola.</li>'
                    + '<li><strong>Le Pere Goriot (1835)</strong> : a la pension Vauquer, le vieux Goriot est depouille par ses filles. Rastignac decouvre les lois implacables de la societe parisienne. Roman d\'apprentissage et critique sociale.</li>'
                    + '<li><strong>Bel-Ami (1885)</strong> : Georges Duroy, parvenu sans scrupules, gravit les echelons sociaux en seduisant les femmes. Maupassant y peint la corruption de la presse et de la politique sous la IIIe Republique.</li>'
                    + '</ul>',
                flashcards: [
                    { question: 'Qu\'est-ce que le "roman experimental" selon Zola ?', answer: 'Dans Le Roman experimental (1880), Zola applique au roman la methode experimentale du medecin Claude Bernard. L\'ecrivain place un personnage dans un milieu determine et observe les effets de l\'heredite et du milieu sur son comportement. Le roman devient un instrument d\'investigation scientifique.' },
                    { question: 'Qu\'est-ce que La Comedie humaine de Balzac ?', answer: 'La Comedie humaine est un ensemble de plus de 90 romans et nouvelles qui dressent un panorama de la societe francaise sous la Restauration et la monarchie de Juillet. Balzac invente le retour des personnages d\'une oeuvre a l\'autre, creant un univers fictionnel unifie.' },
                    { question: 'Qu\'est-ce que le style impersonnel de Flaubert ?', answer: 'Flaubert prone l\'effacement total de l\'auteur derriere son oeuvre. Le narrateur ne porte aucun jugement moral explicite sur ses personnages. "L\'artiste doit etre dans son oeuvre comme Dieu dans la creation, invisible et tout-puissant." Le texte parle de lui-meme par sa seule construction.' },
                    { question: 'Qu\'est-ce que le discours indirect libre ?', answer: 'Le discours indirect libre est une technique narrative qui rapporte les pensees ou paroles d\'un personnage sans guillemets ni verbe introducteur, en les fondant dans le recit du narrateur. Flaubert en est le maitre. Exemple : "Comme elle serait heureuse bientot !" (pensee d\'Emma Bovary).' },
                    { question: 'Qu\'est-ce que le determinisme naturaliste ?', answer: 'Le determinisme naturaliste postule que le comportement humain est entierement conditionne par deux facteurs : l\'heredite biologique (les genes, les tares familiales) et le milieu social (l\'environnement, l\'education, la classe sociale). Zola etudie ces mecanismes dans les Rougon-Macquart.' },
                    { question: 'Pourquoi Flaubert a-t-il ete juge apres Madame Bovary ?', answer: 'En 1857, Flaubert est poursuivi pour "outrage a la morale publique et religieuse et aux bonnes moeurs" apres la publication de Madame Bovary en feuilleton. L\'accusation porte sur les scenes d\'adultere. Il est acquitte, ce qui assure le succes du roman.' },
                    { question: 'Quelle est la methode de documentation de Zola ?', answer: 'Zola mene une enquete quasi journalistique avant chaque roman : il descend dans les mines pour Germinal, visite les grands magasins pour Au Bonheur des Dames, se rend aux Halles pour Le Ventre de Paris. Il constitue des dossiers preparatoires detailles sur les lieux, les metiers et les personnages.' },
                    { question: 'Quelle formule de Stendhal definit le roman realiste ?', answer: 'Stendhal definit le roman comme "un miroir qui se promene le long d\'un chemin" (Le Rouge et le Noir). Cette metaphore exprime l\'ambition realiste de refleter fidelement la realite sociale, sans la transformer ni l\'embellir.' },
                    { question: 'Qu\'est-ce que la technique du "retour des personnages" chez Balzac ?', answer: 'Balzac fait reapparaitre les memes personnages d\'un roman a l\'autre dans La Comedie humaine. Rastignac, par exemple, apparait dans Le Pere Goriot comme etudiant, puis dans d\'autres romans comme homme politique. Ce procede cree un univers fictionnel unifie et donne l\'illusion de la realite.' },
                    { question: 'Comment distinguer realisme et naturalisme ?', answer: 'Le realisme (Balzac, Flaubert, Stendhal) vise la representation fidele de la societe. Le naturalisme (Zola) va plus loin en appliquant la methode scientifique : il etudie l\'heredite et le determinisme social de maniere experimentale. Le naturalisme est un realisme scientifique et systematique.' }
                ],
                quiz: [
                    // correctIndex: 0 (6 total: q1, q6, q10, q15, q19, q24)
                    // correctIndex: 1 (6 total: q2, q7, q11, q16, q20, q22)
                    // correctIndex: 2 (7 total: q3, q8, q12, q14, q17, q21, q25)
                    // correctIndex: 3 (6 total: q4, q5, q9, q13, q18, q23)
                    { question: 'Quel est le sous-titre des Rougon-Macquart de Zola ?', options: ['Histoire naturelle et sociale d\'une famille sous le Second Empire', 'Scenes de la vie parisienne', 'La comedie humaine du XIXe siecle', 'Chronique des classes laborieuses'], correctIndex: 0, explanation: 'Les Rougon-Macquart portent le sous-titre "Histoire naturelle et sociale d\'une famille sous le Second Empire", soulignant la methode scientifique de Zola.' },
                    { question: 'Quelle formule celebre de Stendhal definit le roman ?', options: ['Le roman est l\'histoire de la vie', 'Le roman est un miroir qui se promene le long d\'un chemin', 'Le roman est la science de l\'ame', 'Le roman est une fenetre ouverte sur le monde'], correctIndex: 1, explanation: 'Stendhal compare le roman a un miroir dans Le Rouge et le Noir, exprimant l\'ambition realiste de refleter fidelement la realite.' },
                    { question: 'Combien de romans composent le cycle des Rougon-Macquart ?', options: ['10', '15', '20', '25'], correctIndex: 2, explanation: 'Les Rougon-Macquart forment un cycle de 20 romans publies entre 1871 et 1893, etudiant l\'heredite et le milieu social d\'une famille sur cinq generations.' },
                    { question: 'Madame Bovary de Flaubert a ete poursuivie en justice pour :', options: ['Plagiat d\'un roman anglais', 'Critique du gouvernement imperial', 'Diffamation d\'un medecin de campagne', 'Outrage a la morale publique'], correctIndex: 3, explanation: 'Flaubert est poursuivi en 1857 pour "outrage a la morale publique" a cause des scenes d\'adultere. Il est acquitte, ce qui fait le succes du roman.' },
                    { question: 'Quel est le principe du "retour des personnages" chez Balzac ?', options: ['Les personnages reviennent d\'entre les morts', 'Les personnages reviennent a leur point de depart', 'Les personnages changent de nom entre les romans', 'Les memes personnages reapparaissent d\'un roman a l\'autre'], correctIndex: 3, explanation: 'Balzac fait reapparaitre ses personnages dans differents romans de La Comedie humaine, creant un univers fictionnel interconnecte et unifie.' },
                    { question: 'Quel roman de Zola depeint la condition des mineurs du Nord de la France ?', options: ['Germinal', 'L\'Assommoir', 'La Bete humaine', 'Nana'], correctIndex: 0, explanation: 'Germinal (1885) decrit la misere des mineurs et une greve violente. Zola s\'est documente en descendant dans les mines du bassin houiller du Nord.' },
                    { question: 'Qu\'est-ce que le discours indirect libre ?', options: ['Un dialogue entre le narrateur et le lecteur', 'Un melange de la voix du narrateur et des pensees du personnage sans marqueurs', 'Le monologue interieur d\'un personnage entre guillemets', 'Un discours rapporte avec un verbe introducteur'], correctIndex: 1, explanation: 'Le discours indirect libre fond les pensees du personnage dans le recit du narrateur sans guillemets ni verbe de parole. Flaubert en fait un usage magistral.' },
                    { question: 'L\'Assommoir de Zola traite de :', options: ['La prostitution a Paris', 'La speculation boursiere', 'L\'alcoolisme dans le milieu ouvrier', 'La vie des mineurs'], correctIndex: 2, explanation: 'L\'Assommoir (1877) decrit la decheance de Gervaise par l\'alcoolisme dans le milieu ouvrier parisien. C\'est le premier roman sur le peuple ecrit dans sa langue.' },
                    { question: 'Quel personnage de Balzac decouvre les lois de la societe parisienne dans Le Pere Goriot ?', options: ['Vautrin', 'Goriot', 'Bianchon', 'Rastignac'], correctIndex: 3, explanation: 'Eugene de Rastignac est le jeune provincial ambitieux qui, a la pension Vauquer, decouvre la cruaute des rapports sociaux parisiens. Il lance : "A nous deux maintenant, Paris !"' },
                    { question: 'Flaubert compare l\'artiste a Dieu dans son oeuvre, c\'est-a-dire :', options: ['Invisible et tout-puissant', 'Omnipotent et vengeur', 'Misericordieux et present', 'Absent et indifferent'], correctIndex: 0, explanation: '"L\'artiste doit etre dans son oeuvre comme Dieu dans la creation, invisible et tout-puissant" : l\'auteur s\'efface derriere le texte, sans intervenir ni juger.' },
                    { question: 'Quel roman de Maupassant met en scene un arriviste qui utilise les femmes pour gravir l\'echelle sociale ?', options: ['Une Vie', 'Bel-Ami', 'Pierre et Jean', 'Mont-Oriol'], correctIndex: 1, explanation: 'Bel-Ami (1885) suit l\'ascension de Georges Duroy, seducteur sans scrupules qui utilise ses conquetes feminines pour devenir un homme de pouvoir dans la presse parisienne.' },
                    { question: 'Le Roman experimental (1880) de Zola s\'inspire de la methode de quel medecin ?', options: ['Pasteur', 'Charcot', 'Claude Bernard', 'Laennec'], correctIndex: 2, explanation: 'Zola transpose au roman la methode experimentale definie par Claude Bernard dans son Introduction a la medecine experimentale (1865) : observer, hypothequer, verifier.' },
                    { question: 'Quel est le theme central de Madame Bovary ?', options: ['L\'ambition politique d\'une femme', 'La lutte des classes en province', 'La condition ouvriere sous Louis-Philippe', 'L\'illusion romanesque et ses consequences destructrices'], correctIndex: 3, explanation: 'Emma Bovary, nourrie de lectures romanesques, reve d\'une vie passionnee que la realite provinciale ne peut satisfaire. Le "bovarysme" designe cette insatisfaction chronique entre reve et realite.' },
                    { question: 'Quelle nouvelle de Maupassant, publiee en 1880, lance sa carriere ?', options: ['Le Horla', 'La Parure', 'Boule de Suif', 'La Ficelle'], correctIndex: 2, explanation: 'Boule de Suif (1880), publiee dans le recueil Les Soirees de Medan, raconte l\'hypocrisie de bourgeois qui exploitent une prostituee pendant la guerre de 1870.' },
                    { question: 'Le Rouge et le Noir de Stendhal (1830) se sous-titre :', options: ['Chronique de 1830', 'Scenes de la vie de province', 'Roman d\'apprentissage', 'Chronique du XIXe siecle'], correctIndex: 0, explanation: 'Le Rouge et le Noir porte le sous-titre "Chronique de 1830", ancrant le roman de Julien Sorel dans son contexte historique : Restauration, conflits de classe.' },
                    { question: 'Qui a ecrit Germinie Lacerteux (1865), oeuvre precurseur du naturalisme ?', options: ['Zola', 'Les freres Goncourt', 'Maupassant', 'Huysmans'], correctIndex: 1, explanation: 'Les freres Goncourt publient Germinie Lacerteux en 1865, roman inspire de la vie secrete de leur servante. Il est considere comme precurseur du naturalisme.' },
                    { question: 'Quel concept balzacien consiste a creer des personnages representatifs d\'une classe sociale ?', options: ['Le heros romantique', 'Le personnage picaresque', 'Le type', 'L\'anti-heros'], correctIndex: 2, explanation: 'Le "type" balzacien est un personnage qui concentre les traits caracteristiques d\'une categorie sociale entiere (l\'avare, le parvenu, la bourgeoise de province).' },
                    { question: 'Nana de Zola (1880) depeint :', options: ['La vie paysanne en Provence', 'L\'education d\'une jeune fille bourgeoise', 'La vie des marins bretons', 'La prostitution et la decadence du Second Empire'], correctIndex: 3, explanation: 'Nana raconte l\'ascension et la chute d\'une courtisane parisienne dont la beaute corrompt et ruine les hommes, metaphore de la decomposition du Second Empire.' },
                    { question: 'Quel procede narratif revele la psychologie des personnages chez Stendhal ?', options: ['L\'analyse psychologique et le monologue interieur', 'La description exhaustive des lieux', 'Le monologue interieur en flux de conscience', 'La multiplication des points de vue'], correctIndex: 0, explanation: 'Stendhal excelle dans l\'analyse psychologique de ses personnages par le monologue interieur, revelant leurs calculs, leurs emotions et leurs contradictions.' },
                    { question: 'Quel roman de Huysmans marque la rupture avec le naturalisme ?', options: ['Les Soeurs Vatard', 'A rebours', 'En rade', 'La-bas'], correctIndex: 1, explanation: 'A rebours (1884) rompt avec le naturalisme : le personnage des Esseintes s\'enferme dans un monde d\'artifice et de raffinement. Ce roman influence les symbolistes et les decadents.' },
                    { question: 'La description de la pension Vauquer au debut du Pere Goriot illustre quel principe realiste ?', options: ['Le personnage determine le lieu', 'L\'auteur doit imaginer librement les lieux', 'Le decor revele la condition sociale et morale de ses habitants', 'La nature reflete les sentiments'], correctIndex: 2, explanation: 'Chez Balzac, le decor est un prolongement du personnage : la pension Vauquer, sordide et etriquee, revele la misere et la mediocrite de ses pensionnaires.' },
                    { question: 'Quel personnage de Zola mene la greve dans Germinal ?', options: ['Gervaise Macquart', 'Etienne Lantier', 'Jacques Lantier', 'Claude Lantier'], correctIndex: 1, explanation: 'Etienne Lantier, ouvrier mineur, decouvre la misere des corons et organise une greve violente contre la compagnie miniere dans Germinal (1885).' },
                    { question: 'Une Vie de Maupassant (1883) raconte :', options: ['L\'ascension d\'un journaliste arriviste', 'L\'aventure coloniale en Afrique', 'La vie d\'un marin normand', 'La desillusion progressive d\'une jeune femme de la petite noblesse'], correctIndex: 3, explanation: 'Une Vie suit Jeanne, jeune aristocrate normande dont les reves de bonheur se brisent un a un (mariage decevant, trahisons, solitude). C\'est le premier roman de Maupassant.' },
                    { question: 'Le "bovarysme" designe :', options: ['Le gout pour les descriptions minutieuses', 'L\'ennui provincial en general', 'La passion pour les romans d\'amour', 'La tendance a se concevoir autre que ce que l\'on est'], correctIndex: 0, explanation: 'Le bovarysme, concept forge par Jules de Gaultier, designe le pouvoir qu\'a l\'homme de se concevoir autre qu\'il n\'est, a l\'image d\'Emma Bovary prisonniere de ses illusions romanesques.' },
                    { question: 'Quelle oeuvre de Balzac ouvre La Comedie humaine et presente le retour des personnages ?', options: ['Eugenie Grandet', 'Illusions perdues', 'Le Pere Goriot', 'La Peau de chagrin'], correctIndex: 2, explanation: 'Le Pere Goriot (1835) est le roman ou Balzac met en place pour la premiere fois le procede du retour des personnages, fondateur de l\'unite de La Comedie humaine.' }
                ]
            }
        ]
    });
})();
